//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XRXMLElementParser.h"

@class NSManagedObject;

@interface XRPackageElementParserBase : XRXMLElementParser
{
    NSManagedObject *_managedObject;
}

@property(retain, nonatomic) NSManagedObject *managedObject; // @synthesize managedObject=_managedObject;
- (void).cxx_destruct;
- (id)valueForUndefinedKey:(id)arg1;
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;
- (id)managedObjectModel;

@end

