//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface XRPackageInstrumentCapabilityRequirement : NSObject
{
    int _minVersion;
    NSString *_capabilityIdentifier;
}

@property(readonly) int minVersion; // @synthesize minVersion=_minVersion;
@property(readonly) NSString *capabilityIdentifier; // @synthesize capabilityIdentifier=_capabilityIdentifier;
- (void).cxx_destruct;
- (id)initWithCapabilityIdentifier:(id)arg1 minVersion:(int)arg2;

@end

