//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XRXMLElementParser.h"

@class NSString;

@interface XRPackageDisableElementParser : XRXMLElementParser
{
    NSString *_reason;
    NSString *_platform;
    XRXMLElementParser *_predicate;
}

+ (id)_elementNameToKVCMap;
+ (id)_elementNameToClassMap;
@property(retain, nonatomic) XRXMLElementParser *predicate; // @synthesize predicate=_predicate;
@property(copy) NSString *platform; // @synthesize platform=_platform;
@property(copy) NSString *reason; // @synthesize reason=_reason;
- (void).cxx_destruct;
- (void)_handleCompletion;
- (id)platformSet;

@end

