//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPackaging/XRPackagedUserInterfaceProvider.h>

#import "XRPackagedAugmentation.h"

@class NSString, XRPackage;

@interface XRPackagedAugmentation : XRPackagedUserInterfaceProvider <XRPackagedAugmentation>
{
}

+ (id)fetchRequest;

// Remaining properties
@property(nonatomic) BOOL optional; // @dynamic optional;
@property(retain, nonatomic) XRPackage *package; // @dynamic package;
@property(copy, nonatomic) NSString *purpose; // @dynamic purpose;
@property(copy, nonatomic) NSString *sliceType; // @dynamic sliceType;

@end

