//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

#import "XRPackagedUserInterfaceDefinedParameter.h"

@class NSString, XRPackagedDefinedParameterConstraint, XRPackagedUserInterfaceProvider;

@interface XRPackagedUserInterfaceDefinedParameter : NSManagedObject <XRPackagedUserInterfaceDefinedParameter>
{
}

+ (id)fetchRequest;
- (id)nameWithoutBindingSyntax;
- (id)defineAsMetaConstraint;
- (id)defineAsBooleanConstraint;
- (id)defineAsEnumConstraint;

// Remaining properties
@property(retain, nonatomic) XRPackagedDefinedParameterConstraint *constraint; // @dynamic constraint;
@property(copy, nonatomic) NSString *name; // @dynamic name;
@property(retain, nonatomic) XRPackagedUserInterfaceProvider *provider; // @dynamic provider;

@end

