//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPackaging/XRPackagedUserInterfaceProvider.h>

@class NSArray, NSSet, NSString, XRPackage;

@interface XRPackagedInstrument : XRPackagedUserInterfaceProvider
{
}

+ (id)fetchRequest;
- (id)targetCheckForPlatform:(id)arg1 targetType:(id)arg2;
- (id)recordModeCheckForPlatform:(id)arg1 recordingMode:(id)arg2;
- (id)newPlatformEnable;
- (id)newAssertionCheck;
- (id)newPlatformServiceCheck;
- (id)newCapabilityCheck;
- (id)newRecordModeCapabilityCheck;
- (id)newRecordModeEnable;
- (id)newTargetTypePreflight;
- (id)newAugmentationReference;

// Remaining properties
@property(readonly) NSSet *activatesAugmentations; // @dynamic activatesAugmentations;
@property(readonly) NSArray *assertionChecks; // @dynamic assertionChecks;
@property BOOL beta; // @dynamic beta;
@property(readonly) NSArray *capabilityChecks; // @dynamic capabilityChecks;
@property(retain) NSString *category; // @dynamic category;
@property short defaultDeckHeight; // @dynamic defaultDeckHeight;
@property BOOL deprecated; // @dynamic deprecated;
@property(retain) NSString *icon; // @dynamic icon;
@property(retain) XRPackage *package; // @dynamic package;
@property(readonly) NSArray *platformEnableChecks; // @dynamic platformEnableChecks;
@property(readonly) NSSet *preflights; // @dynamic preflights;
@property(retain) NSString *purpose; // @dynamic purpose;
@property(readonly) NSArray *recordingModeChecks; // @dynamic recordingModeChecks;
@property(readonly) NSArray *serviceChecks; // @dynamic serviceChecks;
@property(readonly) NSArray *targetTypeChecks; // @dynamic targetTypeChecks;

@end

