//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPackaging/XRPackagedUserInterfaceGraphLaneTreatment.h>

@class NSString;

@interface XRPackagedUserInterfaceGraphLanePlot : XRPackagedUserInterfaceGraphLaneTreatment
{
}


// Remaining properties
@property(retain) NSString *colorFrom; // @dynamic colorFrom;
@property(retain) NSString *instanceBy; // @dynamic instanceBy;
@property(retain) NSString *instanceLabelFormat; // @dynamic instanceLabelFormat;
@property(retain) NSString *labelFrom; // @dynamic labelFrom;
@property(retain) NSString *qualifiedBy; // @dynamic qualifiedBy;
@property BOOL sortInstancesAscending; // @dynamic sortInstancesAscending;
@property(retain) NSString *valueFrom; // @dynamic valueFrom;
@end

