//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPackaging/XRPackagedUserInterfaceDetailSpec.h>

#import "XRPackagedUserInterfaceNarrativeSpec.h"

@class NSOrderedSet, NSString;

@interface XRPackagedUserInterfaceNarrativeSpec : XRPackagedUserInterfaceDetailSpec <XRPackagedUserInterfaceNarrativeSpec>
{
}

+ (id)fetchRequest;
- (id)newAnnotation;
- (unsigned long long)family;

// Remaining properties
@property(retain, nonatomic) NSOrderedSet *annotations; // @dynamic annotations;
@property(copy, nonatomic) NSString *narrativeFrom; // @dynamic narrativeFrom;
@property(copy, nonatomic) NSString *timeFrom; // @dynamic timeFrom;

@end

