//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

#import "XRPackagedAggregationMethodParameter.h"

@class NSString, XRPackagedAggregationMethod;

@interface XRPackagedAggregationMethodParameter : NSManagedObject <XRPackagedAggregationMethodParameter>
{
}

+ (id)fetchRequest;

// Remaining properties
@property(retain, nonatomic) XRPackagedAggregationMethod *method; // @dynamic method;
@property(copy, nonatomic) NSString *name; // @dynamic name;
@property(copy, nonatomic) NSString *value; // @dynamic value;

@end

