//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSURL, XRPackageBuildingContext, XRPackagedModeler;

@interface XRPackageGenerateDTAC : NSObject
{
    XRPackageBuildingContext *_context;
    NSURL *_outputURL;
    XRPackagedModeler *_modeler;
}

- (void).cxx_destruct;
- (BOOL)generate:(id *)arg1;
- (BOOL)_generateBindingRules:(id *)arg1;
- (id)initWithModeler:(id)arg1 context:(id)arg2;

@end

