//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPackaging/XRPackageElementParserBase.h>

#import "XRPackagedUserInterfaceAggregationMethodHolder.h"

@class XRXMLTextElementParser;

@interface XRPackageHistogramElementParser : XRPackageElementParserBase <XRPackagedUserInterfaceAggregationMethodHolder>
{
    XRXMLTextElementParser *_aggregationMethodElement;
}

+ (id)_elementNameToKVCMap;
+ (id)_elementNameToClassMap;
@property(retain, nonatomic) XRXMLTextElementParser *aggregationMethodElement; // @synthesize aggregationMethodElement=_aggregationMethodElement;
- (void).cxx_destruct;
- (int)methodColumnReferenceIsValid:(id)arg1;
- (id)method;
- (void)_handleStart;

@end

