//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XRXMLElementParser.h"

@class XRXMLTextElementParser;

@interface XRPackagePercentCapacityMethodElementParser : XRXMLElementParser
{
    long long _capacity;
    XRXMLTextElementParser *_columnToSumElement;
}

+ (id)_elementNameToKVCMap;
+ (id)_elementNameToClassMap;
@property(retain, nonatomic) XRXMLTextElementParser *columnToSumElement; // @synthesize columnToSumElement=_columnToSumElement;
@property(nonatomic) long long capacity; // @synthesize capacity=_capacity;
- (void).cxx_destruct;
- (void)_handleCompletion;
- (void)_handleStart;

@end

