//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface XRPackageKtraceCodeFilter : NSObject
{
    NSMutableDictionary *_subnodes;
    NSString *_nodeKey;
}

+ (id)codeFilterWithClass:(id)arg1 subclass:(id)arg2 code:(id)arg3;
@property(readonly, nonatomic) NSString *nodeKey; // @synthesize nodeKey=_nodeKey;
- (void).cxx_destruct;
- (void)enumerateFilterNotations:(CDUnknownBlockType)arg1;
- (id)deepCopy;
- (void)combineWithPeer:(id)arg1;

@end

