//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XRXMLElementParser.h"

@class NSString;

@interface XRPackageKtracePatternElementParser : XRXMLElementParser
{
    NSString *_kclass;
    NSString *_subclass;
    NSString *_code;
    NSString *_function;
    NSString *_CPU;
    NSString *_thread;
    NSString *_process;
    NSString *_arg1;
    NSString *_arg2;
    NSString *_arg3;
    NSString *_arg4;
    NSString *_arg5;
    NSString *_userBacktrace;
    NSString *_kernelBacktrace;
}

+ (id)_elementNameToKVCMap;
+ (id)_elementNameToClassMap;
@property(copy, nonatomic) NSString *kernelBacktrace; // @synthesize kernelBacktrace=_kernelBacktrace;
@property(copy, nonatomic) NSString *userBacktrace; // @synthesize userBacktrace=_userBacktrace;
@property(copy, nonatomic) NSString *arg5; // @synthesize arg5=_arg5;
@property(copy, nonatomic) NSString *arg4; // @synthesize arg4=_arg4;
@property(copy, nonatomic) NSString *arg3; // @synthesize arg3=_arg3;
@property(copy, nonatomic) NSString *arg2; // @synthesize arg2=_arg2;
@property(copy, nonatomic) NSString *arg1; // @synthesize arg1=_arg1;
@property(copy, nonatomic) NSString *process; // @synthesize process=_process;
@property(copy, nonatomic) NSString *thread; // @synthesize thread=_thread;
@property(copy, nonatomic) NSString *CPU; // @synthesize CPU=_CPU;
@property(copy, nonatomic) NSString *function; // @synthesize function=_function;
@property(copy, nonatomic) NSString *code; // @synthesize code=_code;
@property(copy, nonatomic) NSString *subclass; // @synthesize subclass=_subclass;
@property(copy, nonatomic) NSString *kclass; // @synthesize kclass=_kclass;
- (void).cxx_destruct;
- (void)_handleCompletion;

@end

