//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSArray, NSSet, NSString, XRPackagedModeler;

@protocol XRPackagedModelerOutput
- (NSArray *)attributeBindingConstraints;
- (NSArray *)parameterBindingInstructions;
- (NSSet *)optionalInputs;
- (NSSet *)requiredInputs;
- (NSSet *)bindingConstraints;
- (XRPackagedModeler *)modeler;
- (NSString *)schemaRef;
@end

