//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPackaging/XRPackagedPlatformCheck.h>

#import "XRPackagedPlatformServiceRequirementCheck.h"

@class NSString;

@interface XRPackagedPlatformServiceRequirementCheck : XRPackagedPlatformCheck <XRPackagedPlatformServiceRequirementCheck>
{
}

+ (id)fetchRequest;
- (BOOL)isServiceCheck;

// Remaining properties
@property(copy, nonatomic) NSString *capability; // @dynamic capability;
@property(nonatomic) int min; // @dynamic min;

@end

