//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPackaging/XRPackagedDefinedParameterConstraint.h>

#import "XRPackagedDefinedParameterEnumConstraint.h"

@class NSOrderedSet, NSString;

@interface XRPackagedDefinedParameterEnumConstraint : XRPackagedDefinedParameterConstraint <XRPackagedDefinedParameterEnumConstraint>
{
}

+ (id)fetchRequest;
- (id)newChoice;

// Remaining properties
@property(retain, nonatomic) NSOrderedSet *choices; // @dynamic choices;
@property(copy, nonatomic) NSString *title; // @dynamic title;

@end

