//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

#import "XRPackagedRollUpMethodParameter.h"

@class NSString, XRPackagedHierarchyLevel;

@interface XRPackagedRollUpMethodParameter : NSManagedObject <XRPackagedRollUpMethodParameter>
{
}

+ (id)fetchRequest;

// Remaining properties
@property(retain, nonatomic) XRPackagedHierarchyLevel *level; // @dynamic level;
@property(copy, nonatomic) NSString *name; // @dynamic name;
@property(copy, nonatomic) NSString *value; // @dynamic value;

@end

