//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

@class NSString, XRPackagedSchema;

@interface XRPackagedSchemaColumn : NSManagedObject
{
}

- (id)definition;

// Remaining properties
@property(retain) NSString *mnemonic; // @dynamic mnemonic;
@property(retain) XRPackagedSchema *schema; // @dynamic schema;

@end

