//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDistributedLock, XRPackageDistributionRegistryInternals;

@interface XRPackageDistributionRegistry : NSObject
{
    NSDistributedLock *_systemLock;
    XRPackageDistributionRegistryInternals *__x;
}

+ (BOOL)_cleanIfAbandonedLockURL:(id)arg1;
+ (BOOL)_getStandardDisconnectedError:(id *)arg1;
+ (BOOL)_useSingletonBehavior;
+ (id)registry;
+ (void)initialize;
- (void).cxx_destruct;
- (void)synchronizeWithRepos:(id)arg1 responder:(id)arg2;
- (id)urlForPackageIdentifier:(id)arg1 lockSet:(id)arg2;
- (BOOL)removeLockedPackageURL:(id)arg1 lockSet:(id)arg2 error:(id *)arg3;
- (void)cleanUpAbandonedLocks;
- (BOOL)installPackageDistribution:(id)arg1 identifier:(id)arg2 lockSet:(id)arg3 installedURL:(id *)arg4 error:(id *)arg5;
- (void)releaseLockedPackages:(id)arg1;
- (id)lockAllInstalledPackagesWithResponder:(id)arg1;
- (BOOL)_performUnderSystemLock:(CDUnknownBlockType)arg1;
- (id)_userInstalledRepoToUse:(id *)arg1;
- (id)_userAppSupportDirectoryToUse:(id *)arg1;
- (BOOL)connectWithError:(id *)arg1;
@property(readonly, nonatomic, getter=isConnected) BOOL connected;
- (id)init;

@end

