//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableDictionary, NSMutableSet, NSSet, NSString, XRPackagedSchemaDefinition;

@interface XRPackageKtraceModelingRuleSystem : NSObject
{
    NSMutableDictionary *_topLevelFilterNodes;
    NSMutableDictionary *_startConstraints;
    NSMutableDictionary *_endConstraints;
    NSMutableDictionary *_pointConstraints;
    NSMutableSet *_knownVariables;
    NSMutableDictionary *_columnToExpressionMapping;
    NSMutableDictionary *_columnToStringMap;
    NSMutableDictionary *_columnToKdebugStringVarMapping;
    BOOL _pointSystem;
    BOOL _intervalSystem;
    unsigned long long _serialNumber;
    XRPackagedSchemaDefinition *_outputSchema;
}

@property(retain, nonatomic) XRPackagedSchemaDefinition *outputSchema; // @synthesize outputSchema=_outputSchema;
@property(nonatomic) BOOL intervalSystem; // @synthesize intervalSystem=_intervalSystem;
@property(nonatomic) BOOL pointSystem; // @synthesize pointSystem=_pointSystem;
@property(nonatomic) unsigned long long serialNumber; // @synthesize serialNumber=_serialNumber;
- (void).cxx_destruct;
- (id)generatedRules;
- (void)setColumnAssignmentAsKdebugString:(id)arg1 expression:(id)arg2;
- (void)setStringMappedColumnAssignment:(id)arg1 mapping:(id)arg2 expression:(id)arg3;
- (void)setColumnAssignment:(id)arg1 expression:(id)arg2;
- (void)constrainPointField:(id)arg1 constraint:(id)arg2;
- (void)constrainIntervalEndField:(id)arg1 constraint:(id)arg2;
- (void)constrainIntervalStartField:(id)arg1 constraint:(id)arg2;
- (void)enumerateCodeFilterStrings:(CDUnknownBlockType)arg1;
- (void)addFilter:(id)arg1;
@property(readonly, nonatomic) NSString *pointThreadConstraint;
@property(readonly, nonatomic) NSArray *pointRuleColumnAssignmentActions;
@property(readonly, nonatomic) NSArray *endRuleColumnAssignmentActions;
- (id)_commonRuleColumnAssignmentActions;
@property(readonly, nonatomic) NSArray *endRuleOpenFactMatchConstraints;
@property(readonly, nonatomic) NSArray *pointRuleKdebugConstraints;
@property(readonly, nonatomic) NSArray *endRuleKdebugConstraints;
@property(readonly, nonatomic) NSString *pointRuleName;
@property(readonly, nonatomic) NSString *endRuleName;
@property(readonly, nonatomic) NSString *pointTimeVariableBinding;
@property(readonly, nonatomic) NSString *endTimeVariableBinding;
@property(readonly, nonatomic) NSString *startTimeVariableBinding;
@property(readonly, nonatomic) NSArray *startRuleOpenFactFieldAssignments;
@property(readonly, nonatomic) NSArray *pointRuleJoinPatterns;
@property(readonly, nonatomic) NSArray *endRuleJoinPatterns;
- (void)_appendKdebugStringJoinsIfNeeded:(id)arg1;
@property(readonly, nonatomic) NSArray *startRuleJoinPatterns;
@property(readonly, nonatomic) NSArray *startRuleKdebugConstraints;
@property(readonly, nonatomic) NSString *startRuleName;
@property(readonly, nonatomic) NSSet *knownVariables;
@property(readonly, nonatomic) BOOL requiresKdebugStrings;
- (id)init;

@end

