//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSFileHandle, NSManagedObjectContext, NSManagedObjectModel, NSMutableArray, NSMutableDictionary, NSMutableSet, NSPersistentStoreCoordinator, NSURL, XRCapabilityContext, XRPackage, XRPackageManager;

@interface XRPackageBuildingContext : NSObject
{
    NSManagedObjectModel *_packageMom;
    NSPersistentStoreCoordinator *_packageCoordinator;
    NSMutableDictionary *_sourceURLByDistributionURL;
    NSFileHandle *_knowledgeTemplatesFile;
    NSURL *__tempDir;
    NSMutableArray *_knowledgeRuleRefs;
    NSMutableSet *_tempURLsToCleanUp;
    BOOL _passed;
    NSDictionary *_implClassByEtype;
    NSFileHandle *_errorFile;
    NSURL *_urlBeingParsed;
    NSURL *_outputRootURL;
    XRPackage *_package;
    XRCapabilityContext *_implCapContext;
    XRPackageManager *_linkedPackages;
    NSMutableSet *_knownAugmentationIDs;
    NSFileHandle *_dependencyOutputFile;
    NSManagedObjectContext *_pkgContext;
}

@property(readonly, nonatomic) NSManagedObjectContext *pkgContext; // @synthesize pkgContext=_pkgContext;
@property(retain, nonatomic) NSFileHandle *dependencyOutputFile; // @synthesize dependencyOutputFile=_dependencyOutputFile;
@property(readonly, nonatomic) NSMutableSet *knownAugmentationIDs; // @synthesize knownAugmentationIDs=_knownAugmentationIDs;
@property(retain, nonatomic) XRPackageManager *linkedPackages; // @synthesize linkedPackages=_linkedPackages;
@property(retain, nonatomic) XRCapabilityContext *implCapContext; // @synthesize implCapContext=_implCapContext;
@property(retain, nonatomic) XRPackage *package; // @synthesize package=_package;
@property(nonatomic) BOOL passed; // @synthesize passed=_passed;
@property(copy, nonatomic) NSURL *outputRootURL; // @synthesize outputRootURL=_outputRootURL;
@property(copy, nonatomic) NSURL *urlBeingParsed; // @synthesize urlBeingParsed=_urlBeingParsed;
@property(retain, nonatomic) NSFileHandle *errorFile; // @synthesize errorFile=_errorFile;
@property(readonly, nonatomic) NSDictionary *implClassByEtype; // @synthesize implClassByEtype=_implClassByEtype;
- (void).cxx_destruct;
- (id)findAllDefinedTraceParameters;
- (BOOL)isExportedParameter:(id)arg1 scope:(id)arg2;
- (id)schemaDefinitionForRef:(id)arg1;
- (BOOL)saveStoresAndClose:(id *)arg1;
- (void)enumerateKnowledgeSourceRules:(CDUnknownBlockType)arg1;
- (void)addKnowledgeSourceRules:(id)arg1;
- (void)appendKnowledgeTemplateDefinition:(id)arg1;
- (id)createTemporaryDirectory;
- (BOOL)packageBuildingTemporaryDirectoryExists;
- (id)packageBuildingTemporaryDirectory;
- (void)prepareToReceiveNewPackage;
@property(readonly, nonatomic) NSManagedObjectModel *model;
- (void)reportURLAsDependency:(id)arg1;
- (BOOL)copySourceURL:(id)arg1 distributionURL:(id)arg2;
- (void)reportProblemWithDistributeURL:(id)arg1 lineNumber:(long long)arg2 column:(long long)arg3 failure:(id)arg4;
- (void)reportProblemWithElement:(id)arg1 failure:(id)arg2;

@end

