//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

#import "XRPackagedNarrativeAnnotation.h"

@class NSString, XRPackagedUserInterfaceNarrativeSpec;

@interface XRPackagedNarrativeAnnotation : NSManagedObject <XRPackagedNarrativeAnnotation>
{
}

+ (id)fetchRequest;

// Remaining properties
@property(copy, nonatomic) NSString *column; // @dynamic column;
@property(retain, nonatomic) XRPackagedUserInterfaceNarrativeSpec *spec; // @dynamic spec;

@end

