//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

#import "XRPackagedModelerOutput.h"

@class NSSet, NSString, XRPackagedModeler;

@interface XRPackagedModelerOutput : NSManagedObject <XRPackagedModelerOutput>
{
}

+ (id)fetchRequest;
- (id)attributeBindingConstraints;
- (id)parameterBindingInstructions;
- (id)newOptionaInput;
- (id)newRequiredInput;
- (id)newAttributeBindingConstraint;

// Remaining properties
@property(retain, nonatomic) NSSet *bindingConstraints; // @dynamic bindingConstraints;
@property(retain, nonatomic) XRPackagedModeler *modeler; // @dynamic modeler;
@property(retain, nonatomic) NSSet *optionalInputs; // @dynamic optionalInputs;
@property(retain, nonatomic) NSSet *requiredInputs; // @dynamic requiredInputs;
@property(copy, nonatomic) NSString *schemaRef; // @dynamic schemaRef;

@end

