//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XRXMLSimpleStringElementParser.h"

@class NSString;

@interface XRPackageListColumnElementParser : XRXMLSimpleStringElementParser
{
    NSString *_mnemonic;
}

@property(copy, nonatomic) NSString *mnemonic; // @synthesize mnemonic=_mnemonic;
- (void).cxx_destruct;
- (void)_handleCompletion;
@property(readonly, nonatomic) BOOL hidden;

@end

