//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPackaging/XRPackagedUserInterfaceGraphLaneTreatment.h>

#import "XRPackagedUserInterfaceGraphLaneHistogram.h"

@class XRPackagedAggregationMethod;

@interface XRPackagedUserInterfaceGraphLaneHistogram : XRPackagedUserInterfaceGraphLaneTreatment <XRPackagedUserInterfaceGraphLaneHistogram>
{
}

+ (id)fetchRequest;
- (id)parameterWithName:(id)arg1;
- (id)newParameter;

// Remaining properties
@property(retain, nonatomic) XRPackagedAggregationMethod *method; // @dynamic method;
@property(nonatomic) long long nanosecondsPerBucket; // @dynamic nanosecondsPerBucket;

@end

