//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XRXMLElementParser.h"

@class NSArray, NSMutableArray;

@interface XRPackageProductionSystemElementParser : XRXMLElementParser
{
    NSMutableArray *_rulePathElements;
}

+ (id)_elementNameToKVCMap;
+ (id)_elementNameToClassMap;
- (void).cxx_destruct;
- (void)_handleCompletion;
@property(readonly, nonatomic) NSArray *rulePathElements;
- (void)setRulePathElement:(id)arg1;
- (void)_handleStart;

@end

