//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "XRAnalysisCoreSpaceDirectory.h"

@class XRAnalysisCore, XRAnalysisCorePathManager, XRAnalysisCoreSpace, XRIntKeyedDictionary;

@interface _XRAnalysisCoreSpaceDirectory : NSObject <XRAnalysisCoreSpaceDirectory>
{
    XRAnalysisCorePathManager *_pathMan;
    XRIntKeyedDictionary *_coresByRunNumber;
    XRIntKeyedDictionary *_issueRespondersByRunNumber;
    XRAnalysisCore *_coreForNextRun;
    XRAnalysisCoreSpace *_space;
}

- (void).cxx_destruct;
- (void)abandonCoreForRunNumber:(long long)arg1;
- (BOOL)reinitializeWithNewPathManager:(id)arg1;
- (void)enumerateKnownCores:(CDUnknownBlockType)arg1;
- (long long)runNumberForCore:(id)arg1;
- (id)pathManager;
- (id)coreForNextRun;
- (void)engageCoreForNextRunWithRunNumber:(long long)arg1;
- (id)coreForRunNumber:(long long)arg1;
- (id)initWithSpace:(id)arg1 pathManager:(id)arg2;

@end

