//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface _XRDeviceAppWatcher : NSObject
{
    unsigned int _xcodeCount;
}

+ (id)SharedAppWatcher;
- (void)appExited:(id)arg1;
- (void)appLaunched:(id)arg1;
- (void)dealloc;
- (id)init;

@end

