//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDictionary.h"

@interface NSDictionary (XRStubInstrumentType)
+ (id)xr_stubInfoWithUUID:(id)arg1 name:(id)arg2 brushNames:(id)arg3 containedInPackageName:(id)arg4;
- (id)xr_containedInPackageName;
- (id)xr_stubBrushNames;
- (id)xr_stubName;
- (id)xr_stubUUID;
@end

