//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSError.h"

@interface NSError (XRError)
+ (id)attributeValidationErrorWithFormat:(id)arg1;
+ (id)requiredInputTablesMissingTap:(id)arg1;
+ (id)instrumentsPlugInErrorPrototypeForRun:(long long)arg1;
+ (id)forcedEventHorizonMovementErrorWithTime:(unsigned long long)arg1;
+ (id)tableDoesNotExistForTableID:(unsigned int)arg1;
+ (id)instrumentsPlugInErrorWithCode:(long long)arg1 descriptionWithFormat:(id)arg2;
+ (id)instrumentsPlugInErrorWithCode:(long long)arg1 recoverySuggestionWithFormat:(id)arg2;
+ (id)instrumentsPlugInErrorWithCode:(long long)arg1 description:(id)arg2 recoverySuggestion:(id)arg3;
+ (id)instrumentsPlugInErrorWithCode:(long long)arg1 description:(id)arg2;
+ (id)instrumentsPlugInErrorWithFormat:(id)arg1;
+ (id)instrumentsPlugInErrorWithCode:(long long)arg1;
@end

