//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSURL.h"

@interface NSURL (XRPlugInManager)
+ (id)xr_URLForInstalledPackageWithIdentifier:(id)arg1;
- (BOOL)xr_deleteInstalledDistribution:(id *)arg1;
- (BOOL)xr_isUserInstalledDistributionURL;
@end

