//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSURL.h"

@interface NSURL (XRResourceLocatorFactory)
+ (id)xr_interfaceStateURLForTrace:(id)arg1 globalFork:(long long)arg2 controllerFork:(long long)arg3 controller:(id)arg4;
+ (id)xr_interfaceModeURLForTrace:(id)arg1 globalFork:(long long)arg2 controllerFork:(long long)arg3 controller:(id)arg4;
- (BOOL)xr_isInterfaceStateURL;
- (id)xr_nodeLabelQuery;
- (id)xr_key;
- (long long)xr_controllerFork;
- (long long)xr_globalFork;
- (id)xr_controller;
- (BOOL)xr_isInterfaceModeURL;
- (BOOL)xr_isURLForTrace:(id)arg1;
- (BOOL)xr_isTraceURL;
- (id)xr_urlByAddingQuery:(id)arg1;
@end

