//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSString, PFTProcess, XRRecordModeOptions, XRRecordingOptions, XRTrace;

@interface PFTInstrumentCommand : NSObject <NSCoding>
{
    double _startTime;
    double _endTime;
    long long _runNumber;
    PFTProcess *_defaultExecProcess;
    PFTProcess *_defaultExistingProcess;
    unsigned long long _commandPurpose;
    BOOL _forCommandLine;
    NSString *_uuid;
    XRRecordModeOptions *_recordModeOptions;
    XRTrace *_trace;
    XRRecordingOptions *_recordingOptions;
}

+ (void)initialize;
@property(copy, nonatomic) XRRecordingOptions *recordingOptions; // @synthesize recordingOptions=_recordingOptions;
- (void).cxx_destruct;
- (id)uuid;
- (id)description;
- (unsigned long long)commandPurpose;
- (void)setCommandPurpose:(unsigned long long)arg1;
- (id)target;
- (id)defaultExistingProcess;
- (void)setDefaultExistingProcess:(id)arg1;
- (id)defaultExecProcess;
- (void)setDefaultExecProcess:(id)arg1;
- (id)trace;
- (void)setTrace:(id)arg1;
- (BOOL)isForCommandLine;
- (id)destination;
- (id)currentRunURL;
- (void)setRunNumber:(long long)arg1;
- (long long)runNumber;
- (double)endTime;
- (void)silentlySetStart:(double)arg1 end:(double)arg2;
- (void)markEnd;
- (double)startTime;
- (void)cancelStart;
- (void)markStart;
- (void)restoreFromTraceTemplateData:(id)arg1;
- (id)templateData;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initForCommandLine:(BOOL)arg1 andTrace:(id)arg2;

@end

