//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPlugIn/PFTInstrumentEvaluator.h>

@interface PFTInstrumentSimpleValidator : PFTInstrumentEvaluator
{
    BOOL _enabled;
}

@property(readonly, nonatomic) BOOL enabled; // @synthesize enabled=_enabled;
- (id)description;
- (BOOL)evaluateWithDevice:(id)arg1 variables:(id)arg2;
- (id)initWithEnableState:(BOOL)arg1 errorString:(id)arg2;
- (id)initWithEnableState:(BOOL)arg1;

@end

