//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPlugIn/XRAnalysisCoreUIDetailSpec.h>

#import "NSSecureCoding.h"

@class NSArray;

@interface XRAnalysisCoreUIProjectionDetailSpec : XRAnalysisCoreUIDetailSpec <NSSecureCoding>
{
    BOOL _dimensionsFormHierarchy;
    NSArray *_dimensions;
    NSArray *_aggregates;
}

+ (BOOL)supportsSecureCoding;
@property(nonatomic) BOOL dimensionsFormHierarchy; // @synthesize dimensionsFormHierarchy=_dimensionsFormHierarchy;
@property(copy, nonatomic) NSArray *aggregates; // @synthesize aggregates=_aggregates;
@property(copy, nonatomic) NSArray *dimensions; // @synthesize dimensions=_dimensions;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

