//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPlugIn/XRAnalysisCoreGraphTreatment.h>

#import "NSSecureCoding.h"

@class NSArray;

@interface XRAnalysisCoreHistogramTreatment : XRAnalysisCoreGraphTreatment <NSSecureCoding>
{
    unsigned long long _nanosecondsPerBucket;
    NSArray *_aggregates;
}

+ (BOOL)supportsSecureCoding;
@property(copy, nonatomic) NSArray *aggregates; // @synthesize aggregates=_aggregates;
@property(nonatomic) unsigned long long nanosecondsPerBucket; // @synthesize nanosecondsPerBucket=_nanosecondsPerBucket;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

