//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "NSSecureCoding.h"

@class NSArray, NSString, XRAnalysisCoreTableSpec;

@interface XRAnalysisCoreUIDetailSpec : NSObject <NSSecureCoding, NSCopying>
{
    BOOL _topLevel;
    BOOL _disabled;
    XRAnalysisCoreTableSpec *_tableSpec;
    NSString *_paneTitle;
    NSString *_onFocusDetail;
    NSArray *_selectionCriteria;
    NSString *_emptyContentSuggestion;
    NSString *_stabilizer;
    long long _order;
}

+ (BOOL)supportsSecureCoding;
@property(nonatomic) long long order; // @synthesize order=_order;
@property(copy, nonatomic) NSString *stabilizer; // @synthesize stabilizer=_stabilizer;
@property(copy, nonatomic) NSString *emptyContentSuggestion; // @synthesize emptyContentSuggestion=_emptyContentSuggestion;
@property(nonatomic, getter=isDisabled) BOOL disabled; // @synthesize disabled=_disabled;
@property(copy, nonatomic) NSArray *selectionCriteria; // @synthesize selectionCriteria=_selectionCriteria;
@property(nonatomic, getter=isTopLevel) BOOL topLevel; // @synthesize topLevel=_topLevel;
@property(copy, nonatomic) NSString *onFocusDetail; // @synthesize onFocusDetail=_onFocusDetail;
@property(copy, nonatomic) NSString *paneTitle; // @synthesize paneTitle=_paneTitle;
@property(copy, nonatomic) XRAnalysisCoreTableSpec *tableSpec; // @synthesize tableSpec=_tableSpec;
- (void).cxx_destruct;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

