//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSSecureCoding.h"

@class NSString, XRAnalysisCoreGraphTreatment, XRAnalysisCoreTableSpec;

@interface XRAnalysisCoreGraphSpec : NSObject <NSSecureCoding>
{
    BOOL _inverted;
    BOOL _disabled;
    XRAnalysisCoreTableSpec *_tableSpec;
    NSString *_title;
    NSString *_brush;
    NSString *_overrideColorName;
    NSString *_overrideTextColorName;
    unsigned long long _order;
    XRAnalysisCoreGraphTreatment *_bestTreatmentAboveMinutes;
    XRAnalysisCoreGraphTreatment *_bestTreatmentBelowMilliseconds;
    XRAnalysisCoreGraphTreatment *_bestTreatmentForNormalRange;
}

+ (BOOL)supportsSecureCoding;
@property(nonatomic, getter=isDisabled) BOOL disabled; // @synthesize disabled=_disabled;
@property(retain, nonatomic) XRAnalysisCoreGraphTreatment *bestTreatmentForNormalRange; // @synthesize bestTreatmentForNormalRange=_bestTreatmentForNormalRange;
@property(retain, nonatomic) XRAnalysisCoreGraphTreatment *bestTreatmentBelowMilliseconds; // @synthesize bestTreatmentBelowMilliseconds=_bestTreatmentBelowMilliseconds;
@property(retain, nonatomic) XRAnalysisCoreGraphTreatment *bestTreatmentAboveMinutes; // @synthesize bestTreatmentAboveMinutes=_bestTreatmentAboveMinutes;
@property(nonatomic) unsigned long long order; // @synthesize order=_order;
@property(copy, nonatomic) NSString *overrideTextColorName; // @synthesize overrideTextColorName=_overrideTextColorName;
@property(copy, nonatomic) NSString *overrideColorName; // @synthesize overrideColorName=_overrideColorName;
@property(nonatomic) BOOL inverted; // @synthesize inverted=_inverted;
@property(copy, nonatomic) NSString *brush; // @synthesize brush=_brush;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) XRAnalysisCoreTableSpec *tableSpec; // @synthesize tableSpec=_tableSpec;
- (void).cxx_destruct;
- (id)bestTreatmentForResolution:(unsigned long long)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

