//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class NSError, NSURL, XRAnalysisCoreSpace, XRSpaceDataToken;

@interface XRAnalysisCoreSpaceSealingOperation : NSOperation
{
    float _progress;
    NSError *_error;
    NSURL *_destinationURL;
    XRAnalysisCoreSpace *_space;
    XRSpaceDataToken *_directoryToken;
    id _capabilityContext;
}

@property(retain, nonatomic) id capabilityContext; // @synthesize capabilityContext=_capabilityContext;
@property(retain, nonatomic) XRSpaceDataToken *directoryToken; // @synthesize directoryToken=_directoryToken;
@property(retain, nonatomic) XRAnalysisCoreSpace *space; // @synthesize space=_space;
@property(retain, nonatomic) NSURL *destinationURL; // @synthesize destinationURL=_destinationURL;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(nonatomic) float progress; // @synthesize progress=_progress;
- (void).cxx_destruct;
- (void)main;

@end

