//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XRSpace.h"

@class NSNotificationCenter, NSOperation, NSOperationQueue, XRSpaceDataToken;

@interface XRAnalysisCoreSpace : XRSpace
{
    XRSpaceDataToken *_directoryTok;
    NSOperation *_maintenanceOp;
    id _observationToken;
    id <XRIssueResponder> _issueResponder;
    NSNotificationCenter *_notificationCenter;
}

@property(readonly, nonatomic) NSNotificationCenter *notificationCenter; // @synthesize notificationCenter=_notificationCenter;
@property(readonly, nonatomic) __weak id <XRIssueResponder> issueResponder; // @synthesize issueResponder=_issueResponder;
- (void).cxx_destruct;
- (void)dealloc;
- (id)spaceName;
- (BOOL)isSerial;
- (id)sealAndMoveToURL:(id)arg1;
- (id)afterOperation:(id)arg1 accessDirectory:(CDUnknownBlockType)arg2;
- (id)afterOperation:(id)arg1 priority:(long long)arg2 accessDirectory:(CDUnknownBlockType)arg3;
@property(readonly, nonatomic) NSOperationQueue *notificationCenterQueue;
- (id)initWithSourceURL:(id)arg1 issueResponder:(id)arg2;

@end

