//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPlugIn/XRStrategyInspectionCursor.h>

@interface XRAnalysisCoreInspectionCursor : XRStrategyInspectionCursor
{
    long long _runNumber;
    unsigned long long _count;
    unsigned long long _position;
    struct vector<XRAnalysisCoreInspectionCursorElement, std::__1::allocator<XRAnalysisCoreInspectionCursorElement>> _elements;
    unsigned int _tableID;
}

+ (id)cursorSatisfyingNavigator:(id)arg1 runNumber:(long long)arg2 core:(id)arg3;
@property(readonly) unsigned int tableID; // @synthesize tableID=_tableID;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)_moveBackward;
- (void)_moveForward;
- (BOOL)_canMoveBackward;
- (BOOL)_canMoveForward;
- (BOOL)_populateInspectionDataElements:(id)arg1;
- (unsigned long long)uuid;
- (union XRBookmark)bookmark;

@end

