//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPlugIn/XRAnalysisCoreUIDetailSpec.h>

#import "NSSecureCoding.h"

@class NSArray;

@interface XRAnalysisCoreUIListDetailSpec : XRAnalysisCoreUIDetailSpec <NSSecureCoding>
{
    BOOL _timeslice;
    NSArray *_columns;
}

+ (BOOL)supportsSecureCoding;
@property(nonatomic, getter=isTimeslice) BOOL timeslice; // @synthesize timeslice=_timeslice;
@property(copy, nonatomic) NSArray *columns; // @synthesize columns=_columns;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

