//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSSecureCoding.h"

@class NSArray, NSMutableArray, NSMutableDictionary, XRAnalysisCoreUIPlanEngineeringTypeOverride;

@interface XRAnalysisCoreUIPlan : NSObject <NSSecureCoding>
{
    NSMutableArray *_warnings;
    NSMutableDictionary *_detailsByProjectionName;
    NSMutableDictionary *_detailsByListName;
    NSArray *_orderedBrushNames;
    NSMutableDictionary *_graphsByBrush;
    NSMutableArray *_orderedDetails;
    XRAnalysisCoreUIPlanEngineeringTypeOverride *_engineeringTypeOverride;
}

+ (long long)version;
+ (BOOL)supportsSecureCoding;
- (void).cxx_destruct;
- (BOOL)resolution:(unsigned long long)arg1 differsFrom:(unsigned long long)arg2 brush:(id)arg3;
- (void)addDetailSpec:(id)arg1;
- (id)engineeringTypeOverride;
- (id)graphsWithBrushName:(id)arg1;
- (id)detailWithListName:(id)arg1;
- (id)detailWithProjectionName:(id)arg1;
- (void)enumerateGraphs:(CDUnknownBlockType)arg1;
- (void)enumerateDetails:(CDUnknownBlockType)arg1;
- (id)warnings;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (id)initWithPackagedUserInterfaceProvider:(id)arg1 recordingControlState:(id)arg2 target:(id)arg3;
- (id)initWithBasePlan:(id)arg1 projections:(id)arg2 lists:(id)arg3 graphs:(id)arg4 brushNames:(id)arg5;
- (id)initWithInstrumentTypeData:(id)arg1 recordingControlState:(id)arg2 target:(id)arg3;
- (void)_addWarningWithFormat:(id)arg1;

@end

