//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class XRAnalysisCore, XRAnalysisCorePathManager;

@protocol XRAnalysisCoreSpaceDirectory
- (void)abandonCoreForRunNumber:(long long)arg1;
- (BOOL)reinitializeWithNewPathManager:(XRAnalysisCorePathManager *)arg1;
- (XRAnalysisCorePathManager *)pathManager;
- (void)engageCoreForNextRunWithRunNumber:(long long)arg1;
- (XRAnalysisCore *)coreForNextRun;
- (XRAnalysisCore *)coreForRunNumber:(long long)arg1;
@end

