//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSSecureCoding.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface XRAnalysisCoreDepthOverride : NSObject <NSSecureCoding>
{
    BOOL _rangeCheck;
    BOOL _supportsHighlighting;
    BOOL _supportsWalking;
    long long _value;
    long long _minValue;
    long long _maxValue;
    NSString *_highlightingRoute;
}

+ (BOOL)supportsSecureCoding;
@property(nonatomic) BOOL supportsWalking; // @synthesize supportsWalking=_supportsWalking;
@property(retain, nonatomic) NSString *highlightingRoute; // @synthesize highlightingRoute=_highlightingRoute;
@property(nonatomic) BOOL supportsHighlighting; // @synthesize supportsHighlighting=_supportsHighlighting;
@property(nonatomic) long long maxValue; // @synthesize maxValue=_maxValue;
@property(nonatomic) long long minValue; // @synthesize minValue=_minValue;
@property(nonatomic) long long value; // @synthesize value=_value;
- (void).cxx_destruct;
- (BOOL)matchesDepth:(long long)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithMinValue:(long long)arg1 maxValue:(long long)arg2;
- (id)initWithValue:(long long)arg1;

@end

