//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, XRAnalysisCore, XRIntKeyedDictionary, XRRunListData;

@interface XRAugmentationManager : NSObject
{
    XRAnalysisCore *_coreForNextRun;
    XRRunListData *_runListData;
    XRIntKeyedDictionary *_uiPlansByEtype;
    NSMutableDictionary *_tableIDsBySpec;
}

- (void).cxx_destruct;
- (id)planForEngineeringType:(unsigned short)arg1 runNumber:(long long)arg2;
- (void)nextRunWasPromotedToRunNumber:(long long)arg1;
- (void)updateAugmentationsForNextRun:(id)arg1 controlState:(id)arg2 target:(id)arg3;
- (void)resetAnalysisCoreForNextRun:(id)arg1;
- (id)initWithRunData:(id)arg1;

@end

