//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSValueTransformer.h"

@interface XRBlockValueTransformer : NSValueTransformer
{
    CDUnknownBlockType _transform;
    CDUnknownBlockType _reverseTransform;
}

+ (id)valueTranformerWithTransform:(CDUnknownBlockType)arg1 reverseTransform:(CDUnknownBlockType)arg2;
- (void).cxx_destruct;
- (id)reverseTransformedValue:(id)arg1;
- (id)transformedValue:(id)arg1;
- (id)initWithTransform:(CDUnknownBlockType)arg1 reverseTransform:(CDUnknownBlockType)arg2;

@end

