//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSMutableDictionary;

@interface XRCallTreeInformation : NSObject <NSCoding>
{
    NSMutableDictionary *_callTreeInformation;
}

+ (void)initialize;
@property(retain, nonatomic) NSMutableDictionary *callTreeInformation; // @synthesize callTreeInformation=_callTreeInformation;
- (void).cxx_destruct;
- (id)createAllSamples;
- (void)addSamples:(id)arg1 toAddress:(unsigned long long)arg2;
- (void)setAddress:(unsigned long long)arg1 symbolData:(id)arg2 samples:(id)arg3;
- (void)enumerateAddressesWithBlock:(CDUnknownBlockType)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initFromLegacyDictionary:(id)arg1;
- (id)init;

@end

