//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface XRCallTreeViewControlBinding : NSObject
{
    BOOL _isSettingValue;
    NSString *_binding;
    id _controller;
    NSString *_controllerKeyPath;
}

@property(nonatomic) BOOL isSettingValue; // @synthesize isSettingValue=_isSettingValue;
@property(copy, nonatomic) NSString *controllerKeyPath; // @synthesize controllerKeyPath=_controllerKeyPath;
@property(retain, nonatomic) id controller; // @synthesize controller=_controller;
@property(copy, nonatomic) NSString *binding; // @synthesize binding=_binding;
- (void).cxx_destruct;

@end

