//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSFormatter, NSString, NSTableColumn, NSValueTransformer;

@interface XRColumnData : NSObject
{
    _Bool is_hidden;
    _Bool is_outline;
    _Bool is_last;
    NSTableColumn *column;
    NSArray *objectList;
    NSString *keypath;
    NSValueTransformer *transformer;
    NSFormatter *formatter;
}

- (void).cxx_destruct;

@end

