//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPlugIn/XRStrategyController.h>

@class NSMutableOrderedSet;

@interface XRCompositeStrategyController : XRStrategyController
{
    NSMutableOrderedSet *_subControllers;
}

+ (struct NSString *)strategyIdentifier;
- (void).cxx_destruct;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)removeSubController:(id)arg1;
- (void)addSubController:(id)arg1;
- (void)_regenerateFilteredObjects;
- (void)_regenerateAllObjects;
- (void)_refreshAllObjects;
- (void)_enumerateEngineeringTypeIDsOfInterest:(CDUnknownBlockType)arg1;
- (BOOL)getDataSource:(out struct NSObject **)arg1 forInstrument:(id)arg2;
- (void)dealloc;
- (id)initWithRunNumber:(long long)arg1 delegate:(id)arg2;

@end

