//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface XRCompressionInfoProviderBlocks : NSObject
{
    CDUnknownBlockType _symbolInfoLevelForIndex;
    CDUnknownBlockType _libraryNameForIndex;
}

@property(copy, nonatomic) CDUnknownBlockType libraryNameForIndex; // @synthesize libraryNameForIndex=_libraryNameForIndex;
@property(copy, nonatomic) CDUnknownBlockType symbolInfoLevelForIndex; // @synthesize symbolInfoLevelForIndex=_symbolInfoLevelForIndex;
- (void).cxx_destruct;

@end

