//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface XRCountingBacktraceSet : NSObject
{
    struct unordered_map<_CPPRawBacktrace, unsigned long, std::__1::hash<_CPPRawBacktrace>, std::__1::equal_to<_CPPRawBacktrace>, std::__1::allocator<std::__1::pair<const _CPPRawBacktrace, unsigned long>>> _backtraceMap;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)itemWithGreatestCount;
- (id)allItems;
- (void)addItemsFromSet:(id)arg1;
- (unsigned long long)countForItem:(id)arg1;
- (unsigned long long)countForAllItems;
- (void)addItem:(id)arg1;
- (void)addItem:(id)arg1 withCount:(unsigned long long)arg2;

@end

