//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray, NSNumber, NSString, XRInstrument;

@interface XRCountersSetupModel : NSObject
{
    XRInstrument *_instrument;
    BOOL _sampleByTime;
    BOOL _highFrequencySampling;
    NSNumber *_sampleRateEvents;
    NSString *_pmiEventAliasOrMnemonic;
    BOOL _kernelCallstacks;
    NSMutableArray *_eventsAndFormulas;
    NSString *_eventWarningString;
}

@property(retain, nonatomic) NSArray *eventsAndFormulas; // @synthesize eventsAndFormulas=_eventsAndFormulas;
@property(nonatomic) BOOL kernelCallstacks; // @synthesize kernelCallstacks=_kernelCallstacks;
@property(retain, nonatomic) NSString *eventWarningString; // @synthesize eventWarningString=_eventWarningString;
@property(retain, nonatomic) NSString *pmiEventAliasOrMnemonic; // @synthesize pmiEventAliasOrMnemonic=_pmiEventAliasOrMnemonic;
@property(retain, nonatomic) NSNumber *sampleRateEvents; // @synthesize sampleRateEvents=_sampleRateEvents;
@property(nonatomic) BOOL highFrequencySampling; // @synthesize highFrequencySampling=_highFrequencySampling;
@property(nonatomic) BOOL sampleByTime; // @synthesize sampleByTime=_sampleByTime;
@property(readonly, nonatomic) __weak XRInstrument *instrument; // @synthesize instrument=_instrument;
- (void).cxx_destruct;
- (BOOL)validateEventsAndFormulas;
- (id)modelStateDescription;
- (void)removeEventOrFormulaAtIndex:(unsigned long long)arg1;
- (void)removeEventOrFormulaNamed:(id)arg1;
- (void)removeEventOrFormula:(id)arg1;
- (void)addEventOrFormula:(id)arg1;
- (id)eventForAliasOrMnemonic:(id)arg1;
- (id)eventForMnemonic:(id)arg1;
- (void)setConfigurationOptions:(id)arg1;
- (id)configurationOptions;
- (id)initWithInstrument:(id)arg1;

@end

