//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface XRDeviceResourceToken : NSObject
{
    unsigned long long _managedResource;
}

@property unsigned long long managedResource; // @synthesize managedResource=_managedResource;
- (id)initWithManagedResource:(unsigned long long)arg1;

@end

