//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DTXConnection, NSKeyedUnarchiver, XRBacktraceRepository, XRDevice, XRRun;

@interface XRDTPSImporter : NSObject
{
    XRRun *_run;
    NSKeyedUnarchiver *_unarchiver;
    int _dtpsVersion;
    int _pid;
    double _startSecs;
    double _stopSecs;
    struct _XRDeviceTimeInfo _startTimeInfo;
    struct _XRDeviceTimeInfo _stopTimeInfo;
    XRDevice *_device;
    XRBacktraceRepository *_backtraceRepository;
    DTXConnection *_playbackConnection;
}

@property(readonly, retain) XRBacktraceRepository *backtraceRepository; // @synthesize backtraceRepository=_backtraceRepository;
@property(readonly) double stopSecs; // @synthesize stopSecs=_stopSecs;
@property(readonly) double startSecs; // @synthesize startSecs=_startSecs;
@property(readonly) int pid; // @synthesize pid=_pid;
@property(readonly) int dtpsVersion; // @synthesize dtpsVersion=_dtpsVersion;
@property(readonly, retain) XRDevice *device; // @synthesize device=_device;
@property(readonly, retain) NSKeyedUnarchiver *unarchiver; // @synthesize unarchiver=_unarchiver;
- (void).cxx_destruct;
- (void)endImport;
- (const struct _XRDeviceTimeInfo *)timeInfo:(BOOL)arg1;
- (void)replayMessages;
- (id)playbackConnection;
- (id)initWithFilePaths:(id)arg1 forRun:(id)arg2 error:(id *)arg3;
- (id)hostID;
- (void)displayError:(id)arg1 withInfo:(id)arg2;

@end

