//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPlugIn/XRInstrument.h>

@interface XRExtensionBasedInstrument : XRInstrument
{
}

- (id)extension;
- (id)initWithExtension:(id)arg1;
- (id)switchesReferencedInTableRequirements;

@end

