//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "XRComment.h"

@class NSArray, NSString, XRBacktraceRepository, XRCodeFragment, XRCountingBacktraceSet;

@interface XRHitComment : NSObject <XRComment>
{
    XRCodeFragment *_sourceFragment;
    XRCodeFragment *_disasmFragment;
    XRCodeFragment *_myFragment;
    long long _value;
    id _formatter;
    XRCountingBacktraceSet *_backtraces;
    id <NSObject> _context;
    double _percentage;
    id <CommonSymbol> _symbol;
    int _mergeCount;
    XRBacktraceRepository *_backtraceRepository;
}

@property(retain, nonatomic) XRCodeFragment *fragment; // @synthesize fragment=_myFragment;
@property(retain, nonatomic) XRCodeFragment *disasmFragment; // @synthesize disasmFragment=_disasmFragment;
@property(retain, nonatomic) XRCodeFragment *sourceFragment; // @synthesize sourceFragment=_sourceFragment;
- (void).cxx_destruct;
- (id)nextSymbols;
- (void)setNaturalDisplayType:(int)arg1;
@property(readonly) double importance;
@property(readonly, nonatomic) NSArray *dataItems;
- (BOOL)isMerged;
- (void)mergeWithComment:(id)arg1;
- (BOOL)canMergeWithComment:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)addStatisticsForComment:(id)arg1;
- (id)context;
- (id)backtraces;
- (id)stringWithType:(int)arg1;
- (id)formattedValue;
- (id)formattedPercentage;
- (id)formatValue:(long long)arg1;
- (long long)value;
- (id)initComment:(id)arg1 repository:(id)arg2 ofFragment:(id)arg3 value:(long long)arg4 formatter:(id)arg5 percentage:(double)arg6 backtraces:(id)arg7 context:(id)arg8 symbol:(id)arg9;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

