//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSURL;

@interface XRImportPlugIn : NSObject
{
    NSURL *_url;
}

+ (BOOL)canOpenURL:(id)arg1;
+ (id)importPlugInForURL:(id)arg1;
+ (id)plugIns;
+ (void)scanPlugIns;
- (void).cxx_destruct;
- (id)kdebugCodes;
- (id)productType;
- (id)productVersion;
- (id)deviceDescription;
- (id)rawDeviceDisplayName;
- (id)deviceDisplayName;
- (id)buildVersion;
- (id)deviceArchitecture;
- (id)cpuDescription;
- (int)numberOfPhysicalCpus;
- (int)numberOfCpus;
- (struct _CSTypeRef)createSymbolicatorForPid:(int)arg1;
- (id)execnameForPid:(int)arg1;
- (struct mach_timebase_info)machTimeBase;
- (unsigned long long)machAbsoluteTime;
- (double)stopTime;
- (double)startTime;
- (void)stopRecording:(id)arg1;
- (void)unpauseRecording:(id)arg1;
- (void)pauseRecording:(id)arg1;
- (void)endImporting:(id)arg1;
- (id)startImportingTableIDs:(id)arg1 runNumber:(long long)arg2 trace:(id)arg3;
- (id)preImportStaging;
- (id)initWithURL:(id)arg1;

@end

