//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSSecureCoding.h"
#import "XRSynchronizedDictionaryDelegate.h"

@class NSMutableDictionary, XRSynchronizedDictionary;

@interface XRInstrumentControlState : NSObject <XRSynchronizedDictionaryDelegate, NSSecureCoding>
{
    NSMutableDictionary *_state;
    XRSynchronizedDictionary *_switchAttributes;
    unsigned long long _changeCount;
    XRInstrumentControlState *_fallback;
}

+ (BOOL)automaticallyNotifiesObserversOfChangeCount;
+ (BOOL)supportsSecureCoding;
@property(retain, nonatomic) XRInstrumentControlState *fallback; // @synthesize fallback=_fallback;
@property(nonatomic) unsigned long long changeCount; // @synthesize changeCount=_changeCount;
- (void).cxx_destruct;
- (void)unshadowControlStates;
- (BOOL)evaluateExpression:(id)arg1 result:(id *)arg2 error:(id *)arg3;
- (BOOL)evaluatePredicate:(id)arg1 predicateResult:(char *)arg2 error:(id *)arg3;
- (void)addEntriesFromControlState:(id)arg1;
- (id)modeValueForControllerKey:(id)arg1;
- (void)setControllerKey:(id)arg1 modeValue:(id)arg2;
- (id)valueForUndefinedKey:(id)arg1;
- (id)_valueForUndefinedKey:(id)arg1;
- (void)setNilValueForKey:(id)arg1;
- (void)_setNilValueForKey:(id)arg1;
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;
- (void)_setKey:(id)arg1 value:(id)arg2;
- (void)synchronizedDictionary:(id)arg1 didSetObject:(id)arg2 forKey:(id)arg3;
@property(readonly, nonatomic) NSMutableDictionary *switchAttributes;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (id)initWithState:(id)arg1 switchAttributes:(id)arg2;

@end

