//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString, XRInstrument;

@protocol XRInspectorSource <NSObject>
- (NSString *)documentUUID;
- (NSArray *)dataElementsForInspector:(id)arg1;
- (void)inspectorDismissed:(id)arg1;

@optional
- (XRInstrument *)instrument;
@end

