//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"
#import "XRBrushProvider.h"
#import "XRSourceCommentScopeProvider.h"

@class NSArray, NSError, XRCallTreeInformation, XRTimeFlag, XRTrack, XRTrackOverlay;

@protocol XRInstrumentViewController <NSObject, XRSourceCommentScopeProvider, XRBrushProvider>
@property long long selectedBrushIndex;
@property(retain, nonatomic) NSError *nextRecordingStatus;
- (id <XRSearchTarget>)detailSearchTarget;
- (id <XRFilteredDataSource>)detailFilteredDataSource;
- (NSArray *)currentExtendedDetailMetaUI;
- (NSArray *)currentDisplaySettingsDetailMetaUI;
- (NSArray *)currentRecordSettingsDetailMetaUI;
- (void)instrumentDidChangeSwitches;
- (void)currentBrushBecameStale;
- (void)didRecordDataInTimeRange:(struct XRTimeRange)arg1;
- (void)eventHorizonAdvancedThroughRange:(struct XRTimeRange)arg1;
- (XRCallTreeInformation *)currentCallTreeFilter;
- (void)requestDocumentInspectFlag:(XRTimeFlag *)arg1;
- (BOOL)requestDocumentSetInspectionTime:(unsigned long long)arg1;
- (void)documentDidUpdateBaseFilterForRunNumber:(long long)arg1;
- (void)documentSetInspectionTime:(unsigned long long)arg1;
- (struct XRTimeRange)documentsSelectedTimeRange;
- (void)checkpointUI;
- (void)instrumentChangedTableRequirements;
- (void)instrumentWillBecomeInvalid;
- (id <XRContextContainer>)detailContextContainer;
- (BOOL)resolution:(unsigned long long)arg1 differsFrom:(unsigned long long)arg2 runNumber:(long long)arg3 strategy:(struct NSString *)arg4;
- (void)configureTrackOverlay:(XRTrackOverlay *)arg1;
- (void)configureTrack:(XRTrack *)arg1;
@end

