//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPlugIn/XRStrategyController.h>

@interface XRInstrumentStrategyController : XRStrategyController
{
}

- (void)_refreshAllObjects;
- (id)_modifyOrReplaceBaseUIPlan:(id)arg1;
- (id)_makeStrategyFilter;
- (void)_enumerateEngineeringTypeIDsOfInterest:(CDUnknownBlockType)arg1;

@end

