//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "XRFilteredDataSource.h"

@class NSString, XRLegacyInstrument;

@interface XRLegacyInstrumentFilteredSourceProxy : NSObject <XRFilteredDataSource>
{
    XRLegacyInstrument *_instrument;
}

@property(nonatomic) __weak XRLegacyInstrument *instrument; // @synthesize instrument=_instrument;
- (void).cxx_destruct;
- (id)selectedSearchContext;
- (id)searchContexts;
- (void)filterDetailWithTokens:(id)arg1 context:(id)arg2 matchesAny:(BOOL)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

