//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "XRComment.h"

@class NSArray, NSString, XRCodeFragment;

@interface XRMarkerComment : NSObject <XRComment>
{
    XRCodeFragment *_sourceFragment;
    XRCodeFragment *_disasmFragment;
    XRCodeFragment *_myFragment;
}

@property(retain, nonatomic) XRCodeFragment *fragment; // @synthesize fragment=_myFragment;
@property(retain, nonatomic) XRCodeFragment *disasmFragment; // @synthesize disasmFragment=_disasmFragment;
@property(retain, nonatomic) XRCodeFragment *sourceFragment; // @synthesize sourceFragment=_sourceFragment;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSArray *dataItems;
@property(readonly) double importance;
- (BOOL)isMerged;
- (void)mergeWithComment:(id)arg1;
- (BOOL)canMergeWithComment:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)stringWithType:(int)arg1;
- (id)initWithFragment:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

