//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSAlert.h"

@class NSError;

@interface XRMonitoredLaunchPanel : NSAlert
{
    NSError *_completionError;
}

+ (id)monitoredLaunchPanelWithProcess:(id)arg1 askUserToPerformAction:(BOOL)arg2;
@property(retain) NSError *completionError; // @synthesize completionError=_completionError;
- (void).cxx_destruct;
- (void)completeWithError:(id)arg1 action:(CDUnknownBlockType)arg2;
- (void)completeWithAction:(CDUnknownBlockType)arg1;
- (id)initWithProcess:(id)arg1 askUserToPerformAction:(BOOL)arg2;

@end

