//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSMutableArray;

@interface XRNextRecordingIssues : NSObject <NSCopying>
{
    NSMutableArray *_issues;
    NSMutableArray *_errors;
    NSMutableArray *_warnings;
}

@property(retain, nonatomic) NSMutableArray *warnings; // @synthesize warnings=_warnings;
@property(retain, nonatomic) NSMutableArray *errors; // @synthesize errors=_errors;
@property(retain, nonatomic) NSMutableArray *issues; // @synthesize issues=_issues;
- (void).cxx_destruct;
- (void)clearIssues;
- (void)addIssue:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

