//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPlugIn/XRStrategyController.h>

@interface XRPinnedStrategyController : XRStrategyController
{
}

- (void)removeAllObjects;
- (void)removeObject:(id)arg1;
- (void)addObject:(id)arg1;
- (void)_refreshAllObjects;
- (id)_makeStrategyFilter;
- (void)_enumerateEngineeringTypeIDsOfInterest:(CDUnknownBlockType)arg1;
- (BOOL)getDataSource:(out struct NSObject **)arg1 forInstrument:(id)arg2;
- (id)initWithRunNumber:(long long)arg1 delegate:(id)arg2;

@end

