//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class XRIntKeyedDictionary;

@interface XRProcessSet : NSObject
{
    struct _opaque_pthread_rwlock_t _lock;
    XRIntKeyedDictionary *_processesByPid;
}

- (void).cxx_destruct;
- (void)dealloc;
- (id)processForPid:(int)arg1;
- (void)addProcesses:(id)arg1;
- (id)init;

@end

