//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPlugIn/XRXMLInstrumentTypeData.h>

@interface XRPrototypeInstrumentTypeData : XRXMLInstrumentTypeData
{
}

- (id)iconURL;
- (void)loadExtensionPlugIn;
- (void)loadExtensionBundle;
- (id)instrumentClassName;
- (id)category;
- (unsigned int)deckUnits;
- (BOOL)beta;
- (BOOL)deprecated;
- (id)init;

@end

