//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPlugIn/PFTExtensionBasedInstrumentType.h>

@class NSURL;

@interface XRPrototypeInstrumentType : PFTExtensionBasedInstrumentType
{
    NSURL *_packageURL;
}

- (void).cxx_destruct;
- (id)requiredExtensionURLs;
- (id)initWithPlugIn:(id)arg1 data:(id)arg2 packageURL:(id)arg3;

@end

