//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@interface XRRecordingOptions : NSObject <NSCoding, NSCopying>
{
    BOOL _supportsDeferredMode;
    BOOL _supportsImmediateMode;
    BOOL _supportsWindowedMode;
    BOOL _supportsImportMode;
    unsigned long long _recordingMode;
    unsigned long long _timeLimit;
    unsigned long long _windowLimit;
    unsigned long long _lastUserAcknowledgedRecordingMode;
}

+ (void)initialize;
@property(nonatomic) unsigned long long lastUserAcknowledgedRecordingMode; // @synthesize lastUserAcknowledgedRecordingMode=_lastUserAcknowledgedRecordingMode;
@property(nonatomic) BOOL supportsImportMode; // @synthesize supportsImportMode=_supportsImportMode;
@property(nonatomic) BOOL supportsWindowedMode; // @synthesize supportsWindowedMode=_supportsWindowedMode;
@property(nonatomic) BOOL supportsImmediateMode; // @synthesize supportsImmediateMode=_supportsImmediateMode;
@property(nonatomic) BOOL supportsDeferredMode; // @synthesize supportsDeferredMode=_supportsDeferredMode;
@property(nonatomic) unsigned long long windowLimit; // @synthesize windowLimit=_windowLimit;
@property(nonatomic) unsigned long long timeLimit; // @synthesize timeLimit=_timeLimit;
@property(nonatomic) unsigned long long recordingMode; // @synthesize recordingMode=_recordingMode;
@property(readonly, nonatomic) BOOL isImport;
@property(readonly, nonatomic) BOOL isWindowed;
@property(readonly, nonatomic) BOOL isDeferred;
@property(readonly, nonatomic) BOOL isImmediate;
@property(readonly, nonatomic) BOOL isUnsupported;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

