//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSString;

@interface XRRecordingParameter : NSObject
{
    NSString *_metaType;
    NSString *_metaDescriptor;
    NSArray *_metaKeys;
    NSString *_mnemonic;
    NSString *_title;
    unsigned long long _valueType;
    id _defaultValue;
    NSDictionary *_choiceTitles;
    NSArray *_orderedChoices;
}

@property(retain) NSArray *orderedChoices; // @synthesize orderedChoices=_orderedChoices;
@property(retain) NSDictionary *choiceTitles; // @synthesize choiceTitles=_choiceTitles;
@property(retain) id defaultValue; // @synthesize defaultValue=_defaultValue;
@property unsigned long long valueType; // @synthesize valueType=_valueType;
@property(retain) NSString *title; // @synthesize title=_title;
@property(retain) NSString *mnemonic; // @synthesize mnemonic=_mnemonic;
- (void).cxx_destruct;
- (BOOL)getMetaParameterType:(id *)arg1 descriptor:(id *)arg2 keys:(id *)arg3;
- (void)setMetaType:(id)arg1 descriptor:(id)arg2 keys:(id)arg3;

@end

