//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSMutableArray, NSMutableDictionary, XRIntKeyedDictionary;

@interface XRRunListData : NSObject <NSCoding>
{
    NSMutableArray *_runNumbers;
    NSMutableDictionary *_runData;
    XRIntKeyedDictionary *_processSetByRunNumber;
    XRIntKeyedDictionary *_threadSetByRunNumber;
    XRIntKeyedDictionary *_usernameSetByRunNumber;
}

+ (void)initialize;
- (void).cxx_destruct;
- (struct CGRect)rectOfProperty:(id)arg1 forRunNumber:(long long)arg2;
- (void)setRect:(struct CGRect)arg1 ofProperty:(id)arg2 forRunNumber:(long long)arg3;
- (double)heightOfItem:(id)arg1 withDefaultHeight:(double)arg2 forRunNumber:(long long)arg3;
- (void)setHeight:(double)arg1 ofItem:(id)arg2 forRunNumber:(long long)arg3;
- (id)usernameForUID:(unsigned int)arg1 forRunNumber:(long long)arg2;
- (void)addUsername:(id)arg1 forUID:(unsigned int)arg2 forRunNumber:(long long)arg3;
- (void)setThreadsByTID:(id)arg1 forRunNumber:(long long)arg2;
- (id)threadsByTIDForRunNumber:(long long)arg1;
- (unsigned long long)threadIDForSerialNumber:(unsigned int)arg1 forRunNumber:(long long)arg2;
- (unsigned int)threadSerialNumberForID:(unsigned long long)arg1 forRunNumber:(long long)arg2;
- (id)inputFilterForKey:(id)arg1 forRunNumber:(long long)arg2;
- (void)setInputFilter:(id)arg1 forKey:(id)arg2 forRunNumber:(long long)arg3;
- (id)usernameSetForRunNumber:(long long)arg1;
- (id)processSetForRunNumber:(long long)arg1;
- (id)processWithPid:(int)arg1 forRunNumber:(long long)arg2;
- (id)processDataWithPid:(int)arg1 forRunNumber:(long long)arg2;
- (id)pidsForRunNumber:(long long)arg1;
- (id)processDatasForRunNumber:(long long)arg1;
- (void)addProcess:(id)arg1 forRunNumber:(long long)arg2;
- (id)logEventsForRunNumber:(long long)arg1;
- (void)addProcessLogEvents:(id)arg1 forRunNumber:(long long)arg2;
- (void)setAugmentationUIPlan:(id)arg1 forRunNumber:(long long)arg2 engineeringType:(unsigned short)arg3;
- (id)augmentationPlanForRunNumber:(long long)arg1 engineeringType:(unsigned short)arg2;
- (id)uiPlanForRunNumber:(long long)arg1 identifier:(id)arg2;
- (void)addUIPlan:(id)arg1 forRunNumber:(long long)arg2 identifier:(id)arg3;
- (id)recordingSettingsSummaryForRunNumber:(long long)arg1;
- (void)addRecordingSettingsSummary:(id)arg1 forRunNumber:(long long)arg2;
- (id)recordingInfoSummaryForRunNumber:(long long)arg1;
- (void)addRecordingInfoSummary:(id)arg1 forRunNumber:(long long)arg2;
- (id)recordingOptionsForRunNumber:(long long)arg1;
- (void)addRecordingOptions:(id)arg1 forRunNumber:(long long)arg2;
- (id)flagListForRunNumber:(long long)arg1;
- (void)removeFlag:(id)arg1 forRunNumber:(long long)arg2;
- (void)addFlag:(id)arg1 forRunNumber:(long long)arg2;
- (id)startStringForRunNumber:(long long)arg1;
- (id)startDateForRunNumber:(long long)arg1;
- (unsigned long long)startTimeForRunNumber:(long long)arg1;
- (void)addStartTime:(unsigned long long)arg1 forRunNumber:(long long)arg2;
- (BOOL)hasRunningTimeForRunNumber:(long long)arg1;
- (unsigned long long)runningTimeForRunNumber:(long long)arg1;
- (unsigned long long)inspectionTimeForRunNumber:(long long)arg1;
- (void)setInspectionTime:(unsigned long long)arg1 forRunNumber:(long long)arg2;
- (void)addRunningTime:(unsigned long long)arg1 forRunNumber:(long long)arg2;
- (id)stringOSVersionInfoForRunNumber:(long long)arg1;
- (id)osVersionForRunNumber:(long long)arg1;
- (void)addOSVersionData:(id)arg1 forRunNumber:(long long)arg2;
- (id)allCoresDataForRunNumber:(long long)arg1;
- (void)addAllCoresData:(id)arg1 forRunNumber:(long long)arg2;
- (int)numberOfCpusDataForRunNumber:(long long)arg1;
- (void)addNumberOfCpusData:(int)arg1 forRunNumber:(long long)arg2;
- (id)targetDataForRunNumber:(long long)arg1;
- (void)addTargetData:(id)arg1 forRunNumber:(long long)arg2;
- (id)commentForRunNumber:(long long)arg1;
- (void)addComment:(id)arg1 forRunNumber:(long long)arg2;
- (id)iconNamed:(id)arg1 fullSize:(BOOL)arg2;
- (void)addIcon:(id)arg1 name:(id)arg2 fullSize:(BOOL)arg3;
- (id)dataForRunNumber:(long long)arg1;
- (id)dataForAllRuns;
- (id)runData;
- (id)runNumbers;
- (long long)runNumberForIndex:(unsigned long long)arg1;
- (unsigned long long)indexOfRunNumber:(long long)arg1;
- (void)removeRunNumber:(long long)arg1;
- (void)addRunNumber:(long long)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;

@end

