//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSArchiver.h"

@class XRSharingCoordinator;

@interface XRSharingArchiver : NSArchiver
{
    XRSharingCoordinator *_sharingCoordinator;
}

- (void).cxx_destruct;
- (id)sharingCoordinator;
- (id)initForWritingWithMutableData:(id)arg1 sharingCoordinator:(id)arg2;

@end

