//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface XRStrategyContextObject : NSObject
{
    NSMutableDictionary *_filters;
    long long _runNumber;
    NSString *_strategyIdentifier;
}

@property(copy, nonatomic) NSString *strategyIdentifier; // @synthesize strategyIdentifier=_strategyIdentifier;
@property(nonatomic) long long runNumber; // @synthesize runNumber=_runNumber;
- (void).cxx_destruct;
- (id)filterObjectForKey:(id)arg1;
- (void)addFilters:(id)arg1;
- (id)init;

@end

