//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface XRStrategyInspectionCursor : NSObject
{
    id _primitiveRepresentedObject;
    struct XRTimeRange _primitiveTimeRange;
}

@property(nonatomic) struct XRTimeRange primitiveTimeRange; // @synthesize primitiveTimeRange=_primitiveTimeRange;
@property(retain, nonatomic) id primitiveRepresentedObject; // @synthesize primitiveRepresentedObject=_primitiveRepresentedObject;
- (void).cxx_destruct;
@property(readonly, nonatomic) id representedObject;
@property(readonly, nonatomic) struct XRTimeRange timeRange;
@property(readonly, nonatomic, getter=isValid) BOOL valid;
@property(readonly, nonatomic) NSArray *inspectionDataElements;
@property(readonly, nonatomic) BOOL canMoveForward;
@property(readonly, nonatomic) BOOL canMoveBackward;
- (void)moveBackward;
- (void)moveForward;
- (id)init;

@end

