//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPlugIn/PFTInstrumentType.h>

@class NSString;

@interface XRStubInstrumentType : PFTInstrumentType
{
    NSString *_packageName;
}

+ (BOOL)instrumentTypeCanProduceStub:(id)arg1;
- (void).cxx_destruct;
- (id)reasonForNotSupportingTarget:(id)arg1 device:(id)arg2 recordingOptions:(id)arg3;
- (id)reasonForNotSupportingDevice:(id)arg1;
- (id)initWithPlugIn:(id)arg1 data:(id)arg2;
- (id)initWithInfo:(id)arg1;

@end

