//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSArray, NSSet, PFTInstrumentList, XRAnalysisCore, XRStrategyController;

@protocol XRStrategyControllerDelegate
- (XRAnalysisCore *)coreForRunNumber:(long long)arg1;
- (PFTInstrumentList *)instrumentsForAllRuns;
- (NSSet *)presentStrategyIdentifiersInRunNumber:(long long)arg1;
- (NSArray *)allCoresForRunNumber:(long long)arg1;
- (id <XRThreadSetImmutable>)threadsByTIDInRunNumber:(long long)arg1;
- (NSArray *)strategy:(XRStrategyController *)arg1 runsForRunNumber:(long long)arg2;
@end

