//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPlugIn/XRStrategyContextObject.h>

@class NSString, XRStrategyInspectionCursor;

@interface XRStrategyInspectionNavigator : XRStrategyContextObject
{
    BOOL _readyForNavigation;
    NSString *_route;
    unsigned long long _startTime;
    XRStrategyInspectionCursor *_cursor;
}

@property(readonly, nonatomic) XRStrategyInspectionCursor *cursor; // @synthesize cursor=_cursor;
@property(nonatomic, getter=isReadyForNavigation) BOOL readyForNavigation; // @synthesize readyForNavigation=_readyForNavigation;
@property(nonatomic) unsigned long long startTime; // @synthesize startTime=_startTime;
@property(copy, nonatomic) NSString *route; // @synthesize route=_route;
- (void).cxx_destruct;
- (void)assignReadiedCursorSafely:(id)arg1;

@end

