//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface XRSymbolicationManager : NSObject
{
}

+ (void)startAutomaticDownloadsForDocument:(id)arg1;
+ (void)downloadDSYMForSymbol:(id)arg1;
+ (void)locateDSYMAndSymbolicateForSymbol:(id)arg1;
+ (id)symbolicateMenuItemsForSymbol:(id)arg1 withTarget:(id)arg2 locateSelector:(SEL)arg3 symbolicateSelector:(SEL)arg4 downloadSelector:(SEL)arg5;
+ (void)symbolicateDocuments:(id)arg1;
+ (BOOL)addDSYM:(id)arg1 forUUID:(id)arg2 andResymbolicate:(BOOL)arg3;
+ (id)refreshModel:(id)arg1 forDocument:(id)arg2;
+ (id)findBinaryForUUID:(struct __CFUUID *)arg1 withDSYM:(id)arg2 binaryPathGuess:(id)arg3;
+ (void)_enumerateSymbolsForCurrentRunOfDocument:(id)arg1 block:(CDUnknownBlockType)arg2;
+ (void)initialize;

@end

