//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSSecureCoding.h"

@class NSObject<OS_dispatch_queue>, NSUUID, XRDevice, XRIntKeyedDictionary;

@interface XRSymbolAwareOracle : NSObject <NSSecureCoding>
{
    XRDevice *_device;
    XRIntKeyedDictionary *_providersByPID;
    NSUUID *_stablilityUUID;
    NSObject<OS_dispatch_queue> *_workQ;
}

+ (BOOL)supportsSecureCoding;
- (void).cxx_destruct;
- (id)stabilityID;
- (void)encodeWithCoder:(id)arg1;
- (id)providerForPID:(unsigned int)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithDevice:(id)arg1;
- (id)initWithDevice:(id)arg1 stabilityUUID:(id)arg2;
- (id)init;
- (id)initWithDevice:(id)arg1 stabilityUUID:(id)arg2 providers:(id)arg3;

@end

