//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class XRSynchronizedDictionary;

@protocol XRSynchronizedDictionaryDelegate
- (void)synchronizedDictionary:(XRSynchronizedDictionary *)arg1 didSetObject:(id)arg2 forKey:(id)arg3;
@end

