//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPlugIn/XRDevice.h>

@class NSMutableDictionary, XRImportPlugIn;

@interface XRSynthesizedDevice : XRDevice
{
    XRImportPlugIn *_importPlugIn;
    _Bool _isDisabled;
    NSMutableDictionary *_processNameCache;
}

- (void).cxx_destruct;
- (id)_supportedKDebugEvents:(id *)arg1;
- (BOOL)allowsChoosingExecutable;
- (id)deviceArchitecture;
- (id)cpuDescription;
- (int)numberOfPhysicalCpus;
- (int)numberOfCpus;
- (void)fixupSymbolicator:(struct _CSTypeRef)arg1;
- (BOOL)supportsKernelBacktracing;
- (struct _CSTypeRef)createKernelSymbolicator;
- (struct _CSTypeRef)createSymbolicatorForPid:(int)arg1;
- (BOOL)executableIsRestricted:(id)arg1 launchOptions:(id)arg2;
- (BOOL)isRunningPid:(int)arg1;
- (id)execnameForPid:(int)arg1;
- (int)versionForCapability:(id)arg1;
@property(readonly) double runStopTime;
@property(readonly) double runStartTime;
- (BOOL)currentDeviceTime:(struct _XRDeviceTimeInfo *)arg1;
- (void)disableDeviceNow;
- (id)platformName;
- (BOOL)isReadyToUse;
- (id)templateData;
- (id)importPlugIn;
- (id)initWithImportPlugIn:(id)arg1;

@end

