//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMutableDictionary.h"

@interface XRSynchronizedDictionary : NSMutableDictionary
{
    id <XRSynchronizedDictionaryDelegate> _delegate;
    NSMutableDictionary *_contents;
}

@property(retain, nonatomic) NSMutableDictionary *contents; // @synthesize contents=_contents;
@property(nonatomic) __weak id <XRSynchronizedDictionaryDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)keyEnumerator;
- (id)objectForKey:(id)arg1;
- (void)removeObjectForKey:(id)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (unsigned long long)count;
- (id)initWithObjects:(const id *)arg1 forKeys:(const id *)arg2 count:(unsigned long long)arg3;

@end

