//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSAttributedString, NSImage, NSMutableArray, NSString;

@interface XRTemplateItem : NSObject
{
    NSString *_templatePath;
    NSImage *_image;
    NSAttributedString *_templateDescription;
    NSString *_title;
    NSString *_imageUID;
    BOOL _custom;
    BOOL _deletable;
    NSMutableArray *_items;
    XRTemplateItem *_defaultItem;
    BOOL _isDocumentRef;
}

+ (id)remapTemplateImageResource:(id)arg1;
- (void).cxx_destruct;
- (id)defaultItem;
- (id)items;
- (BOOL)isDeletable;
- (BOOL)isCustom;
- (id)documentUUID;
- (id)templatePath;
- (id)templateURL;
- (id)helpURL;
- (id)imageDescription;
- (BOOL)isSelectable;
- (id)imageSubtitle;
- (id)imageTitle;
- (id)imageRepresentation;
- (id)imageUID;
- (id)description;
- (id)initWithPath:(id)arg1;

@end

