//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPlugIn/XRStrategyController.h>

@interface XRThreadStrategyController : XRStrategyController
{
}

+ (struct NSString *)strategyIdentifier;
- (id)_assignCursorToNavigator:(id)arg1;
- (void)_enumerateEngineeringTypeIDsOfInterest:(CDUnknownBlockType)arg1;
- (void)recordDeviceInformation;
- (void)_prepareBaseFilter:(id)arg1 tableID:(unsigned int)arg2;
- (id)_makeStrategyFilter;
- (void)_refreshObjectsFilter;
- (void)_refreshAllObjects;
- (void)_recomputeFilteredList;
- (BOOL)getDataSource:(struct NSObject **)arg1 forInstrument:(id)arg2;

@end

