//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "XRThreadSetImmutable.h"

@class NSString, XRIntKeyedDictionary;

@interface XRThreadSet : NSObject <XRThreadSetImmutable>
{
    struct _opaque_pthread_rwlock_t _lock;
    XRIntKeyedDictionary *_threadsByTid;
}

- (void).cxx_destruct;
- (void)dealloc;
- (id)allThreads;
- (id)threadForTid:(unsigned long long)arg1;
- (void)addThreads:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

