//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class XRTimeFlag;

@interface XRTraceWindowedFlag : NSObject
{
    BOOL _display;
    XRTimeFlag *_flag;
    long long _runNumber;
}

@property(nonatomic) BOOL display; // @synthesize display=_display;
@property(nonatomic) long long runNumber; // @synthesize runNumber=_runNumber;
@property(retain, nonatomic) XRTimeFlag *flag; // @synthesize flag=_flag;
- (void).cxx_destruct;
- (id)initWithFlag:(id)arg1 runNumber:(long long)arg2 display:(BOOL)arg3;

@end

