//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "XRIssueResponder.h"

@class NSMutableArray, NSMutableOrderedSet, NSObject<OS_dispatch_semaphore>, NSString;

@interface XRUniqueIssueAccumulator : NSObject <XRIssueResponder>
{
    NSMutableOrderedSet *_uniqueIssues;
    NSMutableArray *_prototypeIssues;
    id <XRIssueResponder> _nextResponder;
    long long _signature;
    NSObject<OS_dispatch_semaphore> *_lock;
    char _issuesSeen[4];
    BOOL _forwardAllIssues;
    BOOL _forwardAllUniqueIssues;
    NSString *_defaultRecoveryMessage;
}

- (void).cxx_destruct;
- (BOOL)getIssueType:(unsigned long long)arg1 asXML:(id *)arg2 afterSignature:(long long *)arg3;
- (BOOL)getIssuesAsXML:(id *)arg1 afterSignature:(long long *)arg2;
- (void)handleIssue:(id)arg1 type:(unsigned long long)arg2 from:(id)arg3;
- (void)resetForwardingState;
- (void)setIssuePrototype:(id)arg1 forType:(unsigned long long)arg2;
- (id)init;
- (id)initWithNextResponder:(id)arg1 forwardAllIssues:(BOOL)arg2 forwardAllUniqueIssues:(BOOL)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

