//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class XRIntKeyedDictionary;

@interface XRUsernameSet : NSObject
{
    struct _opaque_pthread_rwlock_t _lock;
    XRIntKeyedDictionary *_usernamesByUID;
}

- (void).cxx_destruct;
- (void)dealloc;
- (id)usernameForUID:(unsigned int)arg1;
- (void)addUsername:(id)arg1 forUID:(unsigned int)arg2;
- (id)init;

@end

