//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPlugIn/XRExtensionInstrumentTypeData.h>

#import "XRInstrumentTypeData.h"

@class NSArray, NSDictionary, NSSet, NSString, NSURL;

@interface XRXMLInstrumentTypeData : XRExtensionInstrumentTypeData <XRInstrumentTypeData>
{
}

- (id)initWithXMLElement:(id)arg1 plugin:(id)arg2;

// Remaining properties
@property(readonly) NSSet *activatesAugmentations;
@property(readonly) BOOL beta;
@property(readonly) NSArray *brushNames;
@property(readonly) BOOL canAttach;
@property(readonly) BOOL canAttachToAll;
@property(readonly) BOOL canLaunch;
@property(readonly) BOOL canReplay;
@property(readonly) NSArray *capabilityAssertions;
@property(readonly) NSString *category;
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int deckUnits;
@property(readonly) NSString *defaultBrushName;
@property(readonly) BOOL deprecated;
@property(readonly, copy) NSString *description;
@property(readonly) BOOL hasRecordingControls;
@property(readonly) unsigned long long hash;
@property(readonly) NSString *helpURL;
@property(readonly) NSURL *iconURL;
@property(readonly) NSString *identifier;
@property(readonly) NSString *instrumentClassName;
@property(readonly) NSArray *keywords;
@property(readonly) NSString *name;
@property(readonly) NSDictionary *platformAssertions;
@property(readonly) int preferredTargetType;
@property(readonly) NSDictionary *recordingAssertions;
@property(readonly) NSDictionary *recordingOptionAssertions;
@property(readonly) NSArray *recordingParameters;
@property(readonly) NSArray *serviceAssertions;
@property(readonly) BOOL simulatorRequiresService;
@property(readonly) Class superclass;
@property(readonly) BOOL useLegacyRecordingOptions;
@property(readonly) NSString *uuid;
@property(readonly) NSString *version;

@end

