//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSError.h"

@interface NSError (InstrumentsPackaging)
+ (id)packageConflicts:(id)arg1 otherPackage:(id)arg2 conflict:(id)arg3;
+ (id)malformedDistributionErrorWithURL:(id)arg1;
@end

