//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSFileHandle, NSMutableArray, NSString, NSURL;

@interface XRInstrumentsPackageBuilder : NSObject
{
    BOOL _disableSystemSearch;
    NSMutableArray *_validators;
    NSMutableArray *_linkedDistributionURLs;
    NSMutableArray *_linkPaths;
    NSMutableArray *_linkDistributionNames;
    NSString *_versionOverride;
    NSURL *_dependencyFileOutURL;
    BOOL _force;
    NSURL *_packageSpecURL;
    NSURL *_outputURL;
    NSFileHandle *_errorFile;
    NSFileHandle *_diagnosticFile;
}

@property(retain) NSFileHandle *diagnosticFile; // @synthesize diagnosticFile=_diagnosticFile;
@property(retain) NSFileHandle *errorFile; // @synthesize errorFile=_errorFile;
@property BOOL force; // @synthesize force=_force;
@property(copy) NSURL *outputURL; // @synthesize outputURL=_outputURL;
@property(copy) NSURL *packageSpecURL; // @synthesize packageSpecURL=_packageSpecURL;
- (void).cxx_destruct;
- (BOOL)build;
- (void)addValidator:(id)arg1;
- (id)init;
- (BOOL)_validatePackage;
- (BOOL)_buildPackage;
- (BOOL)_runTransform:(id)arg1 context:(id)arg2 output:(id)arg3;
- (BOOL)_validate;
- (BOOL)_loadLinkedDistributionsIntoContext:(id)arg1;
- (void)emitDependencyInfoToURL:(id)arg1;
- (void)setVersionOverride:(id)arg1;
- (void)addLinkedDistributionName:(id)arg1;
- (void)addLinkSearchPathURL:(id)arg1;
- (void)addLinkedDistributionURL:(id)arg1;
- (void)disableSystemSearchPath;

@end

