//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

#import "XRPackagedModeler.h"

@class NSOrderedSet, NSSet, NSString, XRPackage;

@interface XRPackagedModeler : NSManagedObject <XRPackagedModeler>
{
}

+ (id)fetchRequest;
- (id)newAdditionalRuleURL;
- (id)newOutput;
- (id)newInstanceParameter;

// Remaining properties
@property(retain, nonatomic) NSOrderedSet *additionalRulesURLs; // @dynamic additionalRulesURLs;
@property(copy, nonatomic) NSString *identifier; // @dynamic identifier;
@property(retain, nonatomic) NSOrderedSet *outputs; // @dynamic outputs;
@property(copy, nonatomic) NSString *owner; // @dynamic owner;
@property(retain, nonatomic) XRPackage *package; // @dynamic package;
@property(retain, nonatomic) NSSet *parameters; // @dynamic parameters;
@property(copy, nonatomic) NSString *purpose; // @dynamic purpose;
@property(copy, nonatomic) NSString *rulesPath; // @dynamic rulesPath;
@property(copy, nonatomic) NSString *title; // @dynamic title;

@end

