//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPackaging/XRPackagedBindingConstraint.h>

@class NSArray, NSString;

@interface XRPackagedAttributeBindingConstraint : XRPackagedBindingConstraint
{
}

- (id)newBindToParameterInstruction;
- (id)newMatchesInstruction;
- (id)referencedAttribute;
- (id)unboundTableConstraintsForOutputID:(int)arg1;

// Remaining properties
@property(readonly) NSArray *instructions; // @dynamic instructions;
@property(retain) NSString *name; // @dynamic name;

@end

