//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPackaging/XRPackagedUserInterfaceDetailSpec.h>

@class NSArray, NSString;

@interface XRPackagedUserInterfaceCallTreeSpec : XRPackagedUserInterfaceDetailSpec
{
}

- (id)newWeight;
- (unsigned long long)family;

// Remaining properties
@property(retain) NSString *backtraceFrom; // @dynamic backtraceFrom;
@property(retain) NSString *categoryFrom; // @dynamic categoryFrom;
@property(retain) NSString *threadFrom; // @dynamic threadFrom;
@property(readonly) NSArray *weights; // @dynamic weights;

@end

