//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSOrderedSet, NSSet, NSString;

@protocol XRPackagedUserInterfaceProvider
- (NSOrderedSet *)details;
- (NSOrderedSet *)graphs;
- (NSSet *)definedParameters;
- (NSSet *)definedTables;
- (NSString *)title;
- (NSString *)identifier;
- (int)version;
@end

