//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPackaging/XRPackagedPreflightCheck.h>

#import "XRPackagedCapabilityCheck.h"

@class NSString;

@interface XRPackagedCapabilityCheck : XRPackagedPreflightCheck <XRPackagedCapabilityCheck>
{
}

+ (id)fetchRequest;

// Remaining properties
@property(copy, nonatomic) NSString *capability; // @dynamic capability;
@property(nonatomic) int min; // @dynamic min;

@end

