//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPackaging/XRPackagedAttributeValue.h>

@class NSString;

@interface XRPackagedAttributeStringConstant : XRPackagedAttributeValue
{
}

- (id)objectValue;
- (id)clipsValue;

// Remaining properties
@property(retain) NSString *string; // @dynamic string;

@end

