//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

@class NSSet, XRPackagedUserInterfaceGraphLane;

@interface XRPackagedUserInterfaceGraphLaneTreatment : NSManagedObject
{
}

- (id)newSelectionPredicate;
- (BOOL)bestTreatmentUnspecified;

// Remaining properties
@property BOOL bestTreatmentAboveMinutes; // @dynamic bestTreatmentAboveMinutes;
@property BOOL bestTreatmentBelowMilliseconds; // @dynamic bestTreatmentBelowMilliseconds;
@property BOOL bestTreatmentForNormalRange; // @dynamic bestTreatmentForNormalRange;
@property BOOL highlightable; // @dynamic highlightable;
@property(retain) XRPackagedUserInterfaceGraphLane *lane; // @dynamic lane;
@property(readonly) NSSet *selectionPredicates; // @dynamic selectionPredicates;
@property BOOL walkable; // @dynamic walkable;

@end

