//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPackaging/XRPackagedSelectionPredicate.h>

@class XRPackagedUserInterfaceDetailSpec;

@interface XRPackagedDetailSelectionPredicate : XRPackagedSelectionPredicate
{
}

+ (id)fetchRequest;
- (BOOL)_proveColumnReferenceIsValid:(id)arg1;

// Remaining properties
@property(retain, nonatomic) XRPackagedUserInterfaceDetailSpec *detail; // @dynamic detail;

@end

