//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPackaging/XRPackagedTableSpec.h>

@class NSString, XRPackagedUserInterfaceProvider;

@interface XRPackagedUserInterfaceTableDef : XRPackagedTableSpec
{
}

- (id)resolvedProvider;

// Remaining properties
@property(retain) NSString *identifier; // @dynamic identifier;
@property(retain) XRPackagedUserInterfaceProvider *provider; // @dynamic provider;

@end

