//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPackaging/XRPackagedRecordModeCheck.h>

@class NSString;

@interface XRPackagedRecordModeCapabilityCheck : XRPackagedRecordModeCheck
{
}


// Remaining properties
@property(retain) NSString *capability; // @dynamic capability;
@property int min; // @dynamic min;
@end

