//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

@class XRPackagedModelerOutput;

@interface XRPackagedBindingConstraint : NSManagedObject
{
}

- (id)referencedAttribute;
- (id)unboundTableConstraintsForOutputID:(int)arg1;

// Remaining properties
@property(retain) XRPackagedModelerOutput *output; // @dynamic output;

@end

