//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XRXMLElementParser.h"

@class NSMutableString;

@interface XRPackageSlotElementParser : XRXMLElementParser
{
    unsigned char _implClass;
    NSMutableString *_slotDef;
}

+ (id)_elementNameToKVCMap;
+ (id)_elementNameToClassMap;
- (void).cxx_destruct;
- (id)slotDefinitionCLIPS;
- (void)_handleCompletion;
- (void)setEngineeringTypeElement:(id)arg1;
- (void)setClipsDefinitionElement:(id)arg1;
- (void)setName:(id)arg1;
- (void)_handleStart;

@end

