//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XRXMLElementParser.h"

@class NSString, XRXMLTextElementParser;

@interface XRPackageImportElementParser : XRXMLElementParser
{
    XRXMLTextElementParser *_nameElement;
    NSString *_scope;
}

+ (id)_elementNameToKVCMap;
+ (id)_elementNameToClassMap;
@property(retain, nonatomic) NSString *scope; // @synthesize scope=_scope;
@property(retain, nonatomic) XRXMLTextElementParser *nameElement; // @synthesize nameElement=_nameElement;
- (void).cxx_destruct;

@end

