//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPackaging/XRPackageElementParserBase.h>

@class NSString;

@interface XRPackagePlotElementParser : XRPackageElementParserBase
{
    NSString *_labelFormat;
}

+ (id)_elementNameToKVCMap;
+ (id)_elementNameToClassMap;
@property(retain, nonatomic) NSString *labelFormat; // @synthesize labelFormat=_labelFormat;
- (void).cxx_destruct;
- (void)setInstanceBy:(id)arg1;
- (void)setQualifiedBy:(id)arg1;
- (void)setLabelFrom:(id)arg1;
- (void)setColorFrom:(id)arg1;
- (void)setValueFrom:(id)arg1;
- (void)_validatedSetKey:(id)arg1 element:(id)arg2;
- (void)_handleCompletion;
- (void)_handleStart;

@end

