//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XRXMLElementParser.h"

@class NSMutableString;

@interface XRPackageKnowledgeTemplateElementParser : XRXMLElementParser
{
    NSMutableString *_template;
}

+ (id)_elementNameToClassMap;
- (void).cxx_destruct;
- (void)_handleCompletion;
- (void)setMultislot:(id)arg1;
- (void)setSlot:(id)arg1;
- (void)setName:(id)arg1;
- (void)_handleStart;

@end

