//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPackaging/XRPackageElementParserBase.h>

@class XRPackageProductionSystemElementParser;

@interface XRPackageModelerElementParser : XRPackageElementParserBase
{
    XRPackageProductionSystemElementParser *_productionSystem;
}

+ (id)_elementNameToKVCMap;
+ (id)_elementNameToClassMap;
@property(retain, nonatomic) XRPackageProductionSystemElementParser *productionSystem; // @synthesize productionSystem=_productionSystem;
- (void).cxx_destruct;
- (void)_handleStart;

@end

