//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

#import "XRPackagedAugmentationReference.h"

@class NSString, XRPackagedInstrument;

@interface XRPackagedAugmentationReference : NSManagedObject <XRPackagedAugmentationReference>
{
}

+ (id)fetchRequest;

// Remaining properties
@property(retain, nonatomic) XRPackagedInstrument *activatedBy; // @dynamic activatedBy;
@property(copy, nonatomic) NSString *identifier; // @dynamic identifier;

@end

