//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPackaging/XRPackageColumnElementParser.h>

@class XRKtraceIntStringMapElement, XRXMLTextElementParser;

@interface XRPackageKtraceColumnElementParser : XRPackageColumnElementParser
{
    BOOL _expressionIsKdebugStringLookup;
    XRXMLTextElementParser *_expressionElement;
    XRKtraceIntStringMapElement *_enumElement;
}

+ (id)_elementNameToKVCMap;
+ (id)_elementNameToClassMap;
@property(nonatomic) BOOL expressionIsKdebugStringLookup; // @synthesize expressionIsKdebugStringLookup=_expressionIsKdebugStringLookup;
@property(retain, nonatomic) XRKtraceIntStringMapElement *enumElement; // @synthesize enumElement=_enumElement;
@property(readonly, nonatomic) XRXMLTextElementParser *expressionElement; // @synthesize expressionElement=_expressionElement;
- (void).cxx_destruct;
- (void)_handleCompletion;
- (void)setExpressionElement:(id)arg1;

@end

