//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XRXMLElementParser.h"

@class XRPackageProductionSystemElementParser;

@interface XRPackageKnowledgeSourceElementParser : XRXMLElementParser
{
    XRPackageProductionSystemElementParser *_productionSystemElement;
}

+ (id)_elementNameToKVCMap;
+ (id)_elementNameToClassMap;
@property(retain, nonatomic) XRPackageProductionSystemElementParser *productionSystemElement; // @synthesize productionSystemElement=_productionSystemElement;
- (void).cxx_destruct;
- (void)_handleCompletion;

@end

