//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

#import "XRPackagedSchemaAttribute.h"

@class NSString, XRPackagedSchema;

@interface XRPackagedSchemaAttribute : NSManagedObject <XRPackagedSchemaAttribute>
{
}

+ (id)fetchRequest;
- (BOOL)validateValueAgainstPattern:(id)arg1;

// Remaining properties
@property(copy, nonatomic) NSString *name; // @dynamic name;
@property(copy, nonatomic) NSString *note; // @dynamic note;
@property(copy, nonatomic) NSString *pattern; // @dynamic pattern;
@property(nonatomic) BOOL required; // @dynamic required;
@property(retain, nonatomic) XRPackagedSchema *schema; // @dynamic schema;

@end

