//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSSet;

@interface XRPackageDistributionRegistryURLLockSet : NSObject
{
    NSMutableDictionary *_locksByURL;
    NSSet *_immutableInstalledURLs;
    int _myNumber;
}

- (void).cxx_destruct;
- (void)_setImmutableInstalledURLsFromInternals:(id)arg1;
- (void)_abandonWithInternals:(id)arg1;
- (BOOL)_trackURLAndLock:(id)arg1 internals:(id)arg2 error:(id *)arg3;
- (void)_releaseLockForURL:(id)arg1 internals:(id)arg2;
- (id)_lockURLForURL:(id)arg1 internals:(id)arg2;
- (BOOL)isUserInstalledURL:(id)arg1;
- (id)allInstalledURLs;
- (id)userInstalledURLs;
- (void)dealloc;
- (id)init;

@end

