//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPackaging/XRPackageElementParserBase.h>

@class NSMutableArray;

@interface XRPackageElementParser : XRPackageElementParserBase
{
    NSMutableArray *_ktraceRuleSystems;
}

+ (id)_elementNameToKVCMap;
+ (id)_elementNameToClassMap;
- (void).cxx_destruct;
- (id)addKtraceModelingRuleSystem;
- (void)_handleCompletion;
- (void)_handleStart;

@end

