//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPackaging/XRPackagedFeatureDataSpec.h>

#import "XRPackagedUserInterfaceGraphLane.h"

@class NSSet, NSString, XRPackagedUserInterfaceGraphSpec;

@interface XRPackagedUserInterfaceGraphLane : XRPackagedFeatureDataSpec <XRPackagedUserInterfaceGraphLane>
{
}

+ (id)fetchRequest;
- (id)addHistogramTreatment;
- (id)addPlotTreatment;

// Remaining properties
@property(copy, nonatomic) NSString *color; // @dynamic color;
@property(nonatomic) BOOL inverted; // @dynamic inverted;
@property(retain, nonatomic) XRPackagedUserInterfaceGraphSpec *spec; // @dynamic spec;
@property(retain, nonatomic) NSSet *treatments; // @dynamic treatments;

@end

