//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

#import "XRPackagedPreflightCheck.h"

@class NSString, XRPackagedInstrument;

@interface XRPackagedPreflightCheck : NSManagedObject <XRPackagedPreflightCheck>
{
}

+ (id)fetchRequest;

// Remaining properties
@property(retain, nonatomic) XRPackagedInstrument *instrument; // @dynamic instrument;
@property(copy, nonatomic) NSString *onFailureMessage; // @dynamic onFailureMessage;

@end

