//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XRXMLSimpleStringElementParser.h"

@class NSString;

@interface XRPackageDisableWhenMissingElementParser : XRXMLSimpleStringElementParser
{
    NSString *_suite;
    long long _minVersion;
}

+ (id)_elementNameToKVCMap;
+ (id)_elementNameToClassMap;
@property long long minVersion; // @synthesize minVersion=_minVersion;
@property(copy) NSString *suite; // @synthesize suite=_suite;
- (void).cxx_destruct;
- (void)_handleCompletion;

@end

