//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPackaging/XRPackagedSchema.h>

#import "XRPackagedSchemaDefinition.h"

@interface XRPackagedSchemaDefinition : XRPackagedSchema <XRPackagedSchemaDefinition>
{
}

+ (id)fetchRequest;
- (id)documentationURL;
- (id)attributeWithName:(id)arg1;
- (id)columnForMnemonic:(id)arg1;
- (id)referenceColumnForMnemonic:(id)arg1;
- (id)newAttribute;
- (id)newSchemaColumn;

@end

