//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPackaging/XRPackagedFeatureDataSpec.h>

#import "XRPackagedUserInterfaceDetailSpec.h"

@class NSOrderedSet, NSString, XRPackagedUserInterfaceProvider;

@interface XRPackagedUserInterfaceDetailSpec : XRPackagedFeatureDataSpec <XRPackagedUserInterfaceDetailSpec>
{
}

+ (id)fetchRequest;
- (id)newSelectionPredicate;
- (unsigned long long)family;

// Remaining properties
@property(copy, nonatomic) NSString *emptyContentSuggestion; // @dynamic emptyContentSuggestion;
@property(retain, nonatomic) XRPackagedUserInterfaceProvider *provider; // @dynamic provider;
@property(retain, nonatomic) NSOrderedSet *selectionPredicates; // @dynamic selectionPredicates;
@property(copy, nonatomic) NSString *visitOnFocus; // @dynamic visitOnFocus;

@end

