//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "XRIssueResponder.h"

@class NSSet, NSString, NSURL;

@interface XRPackageDistributionRegistryInternals : NSObject <XRIssueResponder>
{
    NSURL *_repoURL;
    id <XRIssueResponder> _responder;
    NSSet *_immutableInstalledURLs;
    NSSet *_obsoleteUserInstalledURLs;
}

@property(retain, nonatomic) NSSet *obsoleteUserInstalledURLs; // @synthesize obsoleteUserInstalledURLs=_obsoleteUserInstalledURLs;
@property(retain, nonatomic) NSSet *immutableInstalledURLs; // @synthesize immutableInstalledURLs=_immutableInstalledURLs;
@property(retain, nonatomic) id <XRIssueResponder> responder; // @synthesize responder=_responder;
@property(copy, nonatomic) NSURL *repoURL; // @synthesize repoURL=_repoURL;
- (void).cxx_destruct;
- (void)handleIssue:(id)arg1 type:(unsigned long long)arg2 from:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

