//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPackaging/XRPackagedDefinedParameterConstraint.h>

#import "XRPackagedDefinedParameterMetaConstraint.h"

@class NSString;

@interface XRPackagedDefinedParameterMetaConstraint : XRPackagedDefinedParameterConstraint <XRPackagedDefinedParameterMetaConstraint>
{
}

+ (id)fetchRequest;

// Remaining properties
@property(copy, nonatomic) NSString *config; // @dynamic config;
@property(copy, nonatomic) NSString *title; // @dynamic title;
@property(copy, nonatomic) NSString *type; // @dynamic type;

@end

