//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

#import "XRPackagedUserInterfaceProvider.h"

@class NSOrderedSet, NSSet, NSString;

@interface XRPackagedUserInterfaceProvider : NSManagedObject <XRPackagedUserInterfaceProvider>
{
}

+ (id)fetchRequest;
- (id)parameterWithBindingSyntax:(id)arg1;
- (id)newDefinedParameter;
- (id)newAggregationSpec;
- (id)newNarrativeSpec;
- (id)newCallTreeSpec;
- (id)newGraphSpec;
- (id)newTableDef;
- (id)newListSpec;

// Remaining properties
@property(retain, nonatomic) NSSet *definedParameters; // @dynamic definedParameters;
@property(retain, nonatomic) NSSet *definedTables; // @dynamic definedTables;
@property(retain, nonatomic) NSOrderedSet *details; // @dynamic details;
@property(retain, nonatomic) NSOrderedSet *graphs; // @dynamic graphs;
@property(copy, nonatomic) NSString *identifier; // @dynamic identifier;
@property(copy, nonatomic) NSString *title; // @dynamic title;
@property(nonatomic) int version; // @dynamic version;

@end

