//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPackaging/XRPackagedAttributeValue.h>

@class NSString;

@interface XRPackagedAttributeParameterBinding : XRPackagedAttributeValue
{
}

- (id)objectValue;
- (id)parameterNameOnly;
- (id)clipsValue;

// Remaining properties
@property(retain) NSString *parameter; // @dynamic parameter;

@end

