//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPackaging/XRPackageDetailElementParser.h>

@class XRXMLTextElementParser;

@interface XRPackageCallTreeElementParser : XRPackageDetailElementParser
{
    XRXMLTextElementParser *_backtraceFrom;
    XRXMLTextElementParser *_threadFrom;
    XRXMLTextElementParser *_categoryFrom;
    XRXMLTextElementParser *_weightFrom;
}

+ (id)_elementNameToKVCMap;
+ (id)_elementNameToClassMap;
@property(retain, nonatomic) XRXMLTextElementParser *weightFrom; // @synthesize weightFrom=_weightFrom;
@property(retain, nonatomic) XRXMLTextElementParser *categoryFrom; // @synthesize categoryFrom=_categoryFrom;
@property(retain, nonatomic) XRXMLTextElementParser *threadFrom; // @synthesize threadFrom=_threadFrom;
@property(retain, nonatomic) XRXMLTextElementParser *backtraceFrom; // @synthesize backtraceFrom=_backtraceFrom;
- (void).cxx_destruct;
- (void)_handleCompletion;
- (void)_handleStart;

@end

