//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsPackaging/XRPackagedTableSpec.h>

@class XRPackagedModelerOutput;

@interface XRPackagedInputTableSpec : XRPackagedTableSpec
{
}

- (void)appendBindToInputActionToString:(id)arg1;

// Remaining properties
@property(retain) XRPackagedModelerOutput *output; // @dynamic output;

@end

