//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSManagedObjectContext, NSPersistentStoreCoordinator;

@interface XRPackageManager : NSObject
{
    NSPersistentStoreCoordinator *_packageCoordinator;
    NSManagedObjectContext *_mainThreadObjectContext;
}

+ (BOOL)migrateDistributionAtURL:(id)arg1 error:(id *)arg2;
+ (BOOL)migrationIsNeededForDistributionAtURL:(id)arg1 info:(id)arg2;
+ (id)_asBuiltModelForPackageAtURL:(id)arg1;
+ (id)_infoDataBaseFileNameForMigration;
+ (void)initialize;
+ (id)_packagingBundle;
+ (void)announceCapabilitiesForDistributionLoading:(id)arg1;
+ (void)registerCapabilities:(id)arg1;
- (void).cxx_destruct;
- (void)accessFromSecondaryThread:(CDUnknownBlockType)arg1;
- (id)traceParameterWithName:(id)arg1;
- (id)findAllDefinedTraceParameters;
- (BOOL)isExportedParameter:(id)arg1 scope:(id)arg2;
- (id)augmentationsMatchingIDs:(id)arg1;
- (id)schemaWithID:(id)arg1;
- (id)schemaDefinitionWithID:(id)arg1;
@property(readonly, nonatomic) NSArray *packages;
- (void)dropPackage:(id)arg1;
- (id)loadPackageAtURL:(id)arg1 error:(id *)arg2;
- (void)dealloc;
- (id)init;

@end

