//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSImage.h"

@interface NSImage (XR_CSKAssets)
+ (id)XR_cskiconForFilePath:(id)arg1;
+ (id)XR_cskiconForFileURL:(id)arg1;
+ (id)XR_cskfindIconWithColor:(id)arg1;
+ (id)XR_cskpullDownIconWithColor:(id)arg1;
+ (id)XR_cskinfoMessageTypeDotIcon;
+ (id)XR_cskdebugMessageTypeDotIcon;
+ (id)XR_cskfaultMessageTypeDotIcon;
+ (id)XR_cskerrorMessageTypeDotIcon;
+ (id)XR_csksidebarUnknownDeviceIcon;
+ (id)XR_csksidebarMacProIcon;
+ (id)XR_csksidebarMacProCylinderIcon;
+ (id)XR_csksidebarMacMiniIcon;
+ (id)XR_csksidebarMacBookIcon;
+ (id)XR_csksidebarIMacIcon;
+ (id)XR_csksidebarTVThirdIcon;
+ (id)XR_csksidebarTVIcon;
+ (id)XR_csksidebarWatchIcon;
+ (id)XR_csksidebarIPadIcon;
+ (id)XR_csksidebarIPodTouchIcon;
+ (id)XR_csksidebarIPhoneIcon;
+ (id)XR_csksidebarGenericFolderIcon;
+ (id)XR_csksidebarGenericFileIcon;
- (id)XR_cskimageTintedWithColor:(id)arg1;
@end

