//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSStackView.h"

#import "NSPopoverDelegate.h"

@class NSButton, NSMutableArray, NSPopover, NSString, PFTDataElementList;

@interface PFTDataView : NSStackView <NSPopoverDelegate>
{
    PFTDataElementList *_model;
    NSMutableArray *_boundButtons;
    NSMutableArray *_popoverControllers;
    NSPopover *_currentPopover;
    NSButton *_currentPopoverButton;
    BOOL _dataViewCanResize;
    unsigned long long _style;
    id <PFTDataViewDelegate> _dataViewDelegate;
}

@property(nonatomic) __weak id <PFTDataViewDelegate> dataViewDelegate; // @synthesize dataViewDelegate=_dataViewDelegate;
- (void).cxx_destruct;
- (void)popoverDidClose:(id)arg1;
- (unsigned long long)selectedRow;
@property(nonatomic) unsigned long long style;
- (void)viewDidMoveToWindow;
- (void)viewDidMoveToSuperview;
- (BOOL)isFlipped;
- (BOOL)isOpaque;
- (void)_popupButtonClicked:(id)arg1;
- (void)reloadData;
- (void)_elementsUpdated:(id)arg1;
@property(retain, nonatomic) PFTDataElementList *model;
- (void)dealloc;
- (void)_unbindButtons;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

