//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

#import "DVTChooserViewDelegate.h"
#import "PFTDataViewDelegate.h"

@class DVTChooserView, NSMapTable, NSString, NSTabView, NSTextField, PFTDataElementList, PFTDataView;

@interface PFTDataViewer : NSView <DVTChooserViewDelegate, PFTDataViewDelegate>
{
    NSMapTable *_placeholderMessageForDataViewMapTable;
    DVTChooserView *_chooserView;
    PFTDataElementList *_extendedDetailInspectorModel;
    PFTDataElementList *_runInfoInspectorModel;
    PFTDataView *_extendedDetailInspectorDataView;
    PFTDataView *_runInfoInspectorDataView;
    NSTextField *_placeholderLabel;
    NSTabView *_tabView;
}

@property __weak NSTabView *tabView; // @synthesize tabView=_tabView;
@property(retain, nonatomic) NSTextField *placeholderLabel; // @synthesize placeholderLabel=_placeholderLabel;
@property __weak PFTDataView *runInfoInspectorDataView; // @synthesize runInfoInspectorDataView=_runInfoInspectorDataView;
@property __weak PFTDataView *extendedDetailInspectorDataView; // @synthesize extendedDetailInspectorDataView=_extendedDetailInspectorDataView;
- (void).cxx_destruct;
- (void)displayPlaceholderMessage:(id)arg1 forDataView:(id)arg2;
- (void)chooserView:(id)arg1 userDidSelectChoices:(id)arg2;
- (void)viewWillMoveToSuperview:(id)arg1;
- (void)showRunInfoInspectorDataView;
- (void)showExtendedDetailInspectorDataView;
- (void)_showDataViewAtIndex:(unsigned long long)arg1;
@property(retain) PFTDataElementList *runInfoInspectorModel; // @synthesize runInfoInspectorModel=_runInfoInspectorModel;
@property(retain) PFTDataElementList *extendedDetailInspectorModel; // @synthesize extendedDetailInspectorModel=_extendedDetailInspectorModel;
- (void)drawRect:(struct CGRect)arg1;
- (void)dealloc;
- (void)awakeFromNib;
- (BOOL)isOpaque;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

