//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTokenField.h"

#import "NSTokenFieldDelegate.h"

@class NSButton, NSCharacterSet, NSMenuItem, NSString;

@interface PFTLegacySearchTokenTextField : NSTokenField <NSTokenFieldDelegate>
{
    NSMenuItem *_selectedMenuItem;
    NSButton *_buttonWithMenu;
    NSButton *_clearSearchControl;
    BOOL _matchesAny;
    NSCharacterSet *_invalidCharacters;
    id <XRFilteredDataSource> _filterTarget;
}

+ (void)initialize;
@property(nonatomic) __weak id <XRFilteredDataSource> filterTarget; // @synthesize filterTarget=_filterTarget;
- (void).cxx_destruct;
- (id)tokenField:(id)arg1 shouldUseDrawingAttributes:(id)arg2 forRepresentedObject:(id)arg3;
- (void)setObjectValue:(id)arg1;
- (id)tokenField:(id)arg1 displayStringForRepresentedObject:(id)arg2;
- (void)_clearSearchField:(id)arg1;
- (void)_searchFieldChanged:(id)arg1;
- (void)_handleSearchFieldChanged;
- (void)_updateInstrumentForSearchFieldChanges;
- (void)viewDidMoveToWindow;
- (void)passFilterToTarget;
- (BOOL)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)searchMenuSelect:(id)arg1;
- (void)updateMenuAndFilterTarget;
- (void)resetCursorRects;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)awakeFromNib;
- (void)_setup;
- (void)_buttonWithMenuClicked:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

