//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PFTDataElementList.h"

@class NSString, PFTTraceDocument;

@interface PFTSelectedRunDataElementList : PFTDataElementList
{
    PFTTraceDocument *_traceDocument;
    long long _selectedRunNumber;
    NSString *_context;
}

- (void).cxx_destruct;
- (id)context;
- (void)setContext:(id)arg1;
- (void)_updateElements;
- (void)_runEnded:(id)arg1;
- (void)_runChanged:(id)arg1;
- (id)traceDocument;
- (void)setTraceDocument:(id)arg1;
- (void)dealloc;

@end

