//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PFTDataElementList.h"

@class NSString, PFTSelectedInstrumentList, PFTTraceDocument;

@interface PFTSelectedInstrumentDataElementList : PFTDataElementList
{
    NSString *_context;
    PFTSelectedInstrumentList *_selectedInstrumentList;
    PFTTraceDocument *_traceDocument;
    BOOL _onlyProvideElementsForInstrumentDetailView;
}

- (void).cxx_destruct;
- (id)context;
- (void)setContext:(id)arg1;
- (id)traceDocument;
- (void)setTraceDocument:(id)arg1;
- (void)_detailViewChanged:(id)arg1;
- (void)_instrumentUnselected:(id)arg1;
- (void)_instrumentUpdated:(id)arg1;
- (void)_instrumentSelected:(id)arg1;
- (id)selectedInstrumentList;
- (void)setSelectedInstrumentList:(id)arg1;
- (void)dealloc;
- (id)initAndOnlyProvideElementsForInstrumentDetailView:(BOOL)arg1;

@end

