//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTokenFieldCell.h"

@interface XR_CSKTokenFieldCell : NSTokenFieldCell
{
    unsigned long long _leftMargin;
    unsigned long long _rightMargin;
}

@property unsigned long long rightMargin; // @synthesize rightMargin=_rightMargin;
@property unsigned long long leftMargin; // @synthesize leftMargin=_leftMargin;
- (struct CGRect)drawingRectForBounds:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (void)commonInit;

@end

