//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTokenFieldDelegate.h"

@class NSArray, XR_CSKTokenField;

@protocol XR_CSKTokenFieldDelegate <NSTokenFieldDelegate>

@optional
- (NSArray *)tokenFieldIconMenuItemsFor:(XR_CSKTokenField *)arg1;
- (void)tokenField:(XR_CSKTokenField *)arg1 globalOperatorDidChange:(int)arg2;
@end

