//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSArray;

@interface XR_CSKFilterGroup : NSObject <NSCopying>
{
    int _globalOperator;
    NSArray *_filters;
}

@property(retain, nonatomic) NSArray *filters; // @synthesize filters=_filters;
@property(nonatomic) int globalOperator; // @synthesize globalOperator=_globalOperator;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (BOOL)isEqual:(id)arg1;
- (BOOL)checkAgainstTargetFilterables:(id)arg1;
- (id)serializationString;
- (id)initWithSerializationString:(id)arg1;
- (id)initWithFilters:(id)arg1 globalOperator:(int)arg2;
- (void)_sanitizeGlobalOperator;
- (id)init;

@end

