//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsKit/XR_CSKFilter.h>

@interface XR_CSKToken : XR_CSKFilter
{
}

+ (void)parseString:(id)arg1 forType:(long long *)arg2 comparisonType:(long long *)arg3 value:(id *)arg4 invert:(char *)arg5;
+ (id)tokensFromFilters:(id)arg1;
+ (id)tokenFromFilter:(id)arg1;
- (id)comparisonValueString;
- (id)filterCopyRepresentation;

@end

