//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTokenField.h"

@class DVTFilterTokenIconView;

@interface XR_CSKTokenField : NSTokenField
{
    BOOL _hasText;
    BOOL _popUpPullsUp;
    int _globalOperatorType;
    DVTFilterTokenIconView *_iconView;
}

+ (Class)cellClass;
@property(retain) DVTFilterTokenIconView *iconView; // @synthesize iconView=_iconView;
@property(nonatomic) int globalOperatorType; // @synthesize globalOperatorType=_globalOperatorType;
@property(nonatomic) BOOL popUpPullsUp; // @synthesize popUpPullsUp=_popUpPullsUp;
- (void).cxx_destruct;
- (void)closeCompletionWindow;
- (void)_handleWindowNotifications:(id)arg1;
- (void)_updateButtonPositions;
- (void)_updateSearchButton;
@property BOOL hasText;
- (void)invalidateSelectionAndDisplayTokens;
- (id)_cell;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)_initCommon;

// Remaining properties
@property id <XR_CSKTokenFieldDelegate> delegate; // @dynamic delegate;

@end

