//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DVTLayerHostingView.h"

@class CALayer, DVTClickableLayer, NSDictionary, NSImage, NSString, NSView, XRActivityStatusCategory, XRActivityStatusContainerLayer, XRActivityTextLayer;

@interface XRActivityView : DVTLayerHostingView
{
    BOOL _isSetup;
    BOOL _isKeyWindow;
    NSView *_layerView;
    CALayer *_backgroundLayer;
    CALayer *_backgroundColorLayer;
    DVTClickableLayer *_leftArrow;
    DVTClickableLayer *_rightArrow;
    CDUnknownBlockType _leftArrowBlock;
    CDUnknownBlockType _rightArrowBlock;
    BOOL _enableLeft;
    BOOL _enableRight;
    XRActivityTextLayer *_runAndTimeLayer;
    XRActivityStatusContainerLayer *_issuesContainerLayer;
    XRActivityStatusCategory *_warningsIssueCategory;
    XRActivityStatusCategory *_errorsIssueCategory;
    NSImage *_leftArrowKey;
    NSImage *_leftArrowBackground;
    NSImage *_rightArrowKey;
    NSImage *_rightArrowBackground;
    NSDictionary *_textAttributes;
    BOOL _observingKeyWindowNotifications;
    BOOL _traceIsRecording;
    unsigned long long _runCount;
    unsigned long long _selectedRunIndex;
    NSString *_runInfoString;
    NSString *_timeString;
    unsigned long long _recordingErrorCount;
    unsigned long long _recordingWarningCount;
}

+ (struct CGSize)defaultSizeForToolbarDisplayMode:(unsigned long long)arg1 sizeMode:(unsigned long long)arg2;
@property(nonatomic) unsigned long long recordingWarningCount; // @synthesize recordingWarningCount=_recordingWarningCount;
@property(nonatomic) unsigned long long recordingErrorCount; // @synthesize recordingErrorCount=_recordingErrorCount;
@property(readonly, copy) NSString *runInfoString; // @synthesize runInfoString=_runInfoString;
- (void).cxx_destruct;
- (void)makeSureIssuesLayerIsVisible;
- (id)clickableLayerAtPoint:(struct CGPoint)arg1;
- (void)_activationStateChangedForWindow:(id)arg1;
- (void)_updateCurrentActivityReportForWindowActivationState;
- (void)_updateBackgroundColorForWindowActivationState;
- (void)setUpOrTearDown;
@property(nonatomic) BOOL traceIsRecording; // @synthesize traceIsRecording=_traceIsRecording;
- (void)tearDown;
- (void)_handleResignKeyWindowNotification:(id)arg1;
- (void)_handleBecameKeyWindowNotification:(id)arg1;
- (void)setup;
- (id)_buildAllStatusLayer;
- (void)setNextRunBlock:(CDUnknownBlockType)arg1;
- (void)setPrevRunBlock:(CDUnknownBlockType)arg1;
- (void)setupLayers;
- (id)_runAndTimeLayer;
- (id)_textLayerWithFrame:(struct CGRect)arg1 stringValue:(id)arg2;
- (id)_backgroundLayer;
- (id)_highlightColor;
- (id)_backgroundColor;
- (void)_updateHighlightColorForWindowActivationState;
- (struct CGRect)insetReportLayerBounds;
- (struct CGRect)insetRootLayerBounds;
@property(copy) NSString *timeString; // @synthesize timeString=_timeString;
- (void)setRunCount:(unsigned long long)arg1 andSelectedRunIndex:(unsigned long long)arg2;
- (void)_updateRunInfoAndTimeText;
@property(readonly) unsigned long long selectedRunIndex; // @synthesize selectedRunIndex=_selectedRunIndex;
@property(readonly) unsigned long long runCount; // @synthesize runCount=_runCount;
@property struct CGSize contentSize;
- (void)sizeToFitToolbarDisplayMode:(unsigned long long)arg1 sizeMode:(unsigned long long)arg2;
- (void)viewDidMoveToSuperview;
- (void)viewDidMoveToWindow;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

