//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "NSMutableCopying.h"

@class NSString, PFTTraceDocument;

@interface XRActionContext : NSObject <NSMutableCopying, NSCopying>
{
    PFTTraceDocument *_document;
    long long _runNumber;
    NSString *_instrumentUUID;
    struct XRTimeRange _timeRange;
}

@property(nonatomic) struct XRTimeRange timeRange; // @synthesize timeRange=_timeRange;
@property(copy, nonatomic) NSString *instrumentUUID; // @synthesize instrumentUUID=_instrumentUUID;
@property(nonatomic) long long runNumber; // @synthesize runNumber=_runNumber;
@property(nonatomic) __weak PFTTraceDocument *document; // @synthesize document=_document;
- (void).cxx_destruct;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

