//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface XRAction : NSObject
{
    NSString *_identifier;
    id _handler;
    NSString *_targetClassType;
    NSString *_targetProtocolType;
    NSString *_displayName;
    NSString *_actionSelector;
    BOOL _appleInternal;
    unsigned short _etype;
    unsigned long long _positioningIndex;
}

+ (id)createActionWithActionElement:(id)arg1 handler:(id)arg2;
@property(nonatomic) unsigned long long positioningIndex; // @synthesize positioningIndex=_positioningIndex;
@property(nonatomic) unsigned short etype; // @synthesize etype=_etype;
@property(nonatomic) BOOL appleInternal; // @synthesize appleInternal=_appleInternal;
@property(copy, nonatomic) NSString *actionSelector; // @synthesize actionSelector=_actionSelector;
@property(copy, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
@property(copy, nonatomic) NSString *targetProtocolType; // @synthesize targetProtocolType=_targetProtocolType;
@property(copy, nonatomic) NSString *targetClassType; // @synthesize targetClassType=_targetClassType;
@property(retain, nonatomic) id handler; // @synthesize handler=_handler;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (id)displayNameForInContext:(id)arg1 targets:(id)arg2;
- (BOOL)validateWithTargets:(id)arg1 context:(id)arg2;
- (void)dispatchActionForTargets:(id)arg1 context:(id)arg2;
- (SEL)action;
- (long long)displayNameCompare:(id)arg1;
- (id)description;
- (id)initWithIdentifier:(id)arg1 handler:(id)arg2 targetClassType:(id)arg3 targetProtocolType:(id)arg4 displayName:(id)arg5 actionSelector:(id)arg6 appleInternal:(BOOL)arg7;

@end

