//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsKit/XRAnalysisCoreTableViewPersonality.h>

@interface XRAnalysisCoreTableViewIntervalPersonality : XRAnalysisCoreTableViewPersonality
{
}

- (void)personalizeColumnItem:(id)arg1;
- (BOOL)shouldAddFocusActionToColumn:(id)arg1 abstractContent:(id)arg2;

@end

