//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsKit/XRAnalysisCoreTableViewPersonality.h>

@interface XRAnalysisCoreTableViewTimeslicePersonality : XRAnalysisCoreTableViewPersonality
{
}

- (BOOL)contentChangesWithTimeInspection;
- (BOOL)rowSelectionDoesNotAffectTimeSelection;
- (void)personalizeContentFilter:(id)arg1 timeInspection:(unsigned long long)arg2;

@end

