//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSTableColumn, XRAnalysisCoreColumnSpec;

@interface XRAnalysisCoreTableViewColumnListItem : NSObject
{
    unsigned char _tableColID;
    unsigned char _implClassID;
    unsigned char _topologyFieldID;
    unsigned short _engineeringTypeID;
    NSTableColumn *_column;
    XRAnalysisCoreColumnSpec *_colSpec;
}

@property(nonatomic) unsigned char topologyFieldID; // @synthesize topologyFieldID=_topologyFieldID;
@property(nonatomic) unsigned char implClassID; // @synthesize implClassID=_implClassID;
@property(nonatomic) unsigned short engineeringTypeID; // @synthesize engineeringTypeID=_engineeringTypeID;
@property(nonatomic) unsigned char tableColID; // @synthesize tableColID=_tableColID;
@property(retain, nonatomic) XRAnalysisCoreColumnSpec *colSpec; // @synthesize colSpec=_colSpec;
@property(retain, nonatomic) NSTableColumn *column; // @synthesize column=_column;
- (void).cxx_destruct;

@end

