//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsKit/XRAnalysisCoreDetailViewContent.h>

@class NSMutableSet, XRAnalysisCoreTableQuery, XRAnalysisCoreTableViewPersonality, XRAnalysisCoreUIListDetailSpec;

@interface XRAnalysisCoreTableViewContent : XRAnalysisCoreDetailViewContent
{
    NSMutableSet *__cachedColIDs;
    XRAnalysisCoreUIListDetailSpec *_spec;
    XRAnalysisCoreTableQuery *_contentFilter;
    XRAnalysisCoreTableQuery *_documentBaseFilter;
    XRAnalysisCoreTableViewPersonality *_personality;
}

@property(retain, nonatomic) XRAnalysisCoreTableViewPersonality *personality; // @synthesize personality=_personality;
@property(retain, nonatomic) XRAnalysisCoreTableQuery *documentBaseFilter; // @synthesize documentBaseFilter=_documentBaseFilter;
@property(retain, nonatomic) XRAnalysisCoreTableQuery *contentFilter; // @synthesize contentFilter=_contentFilter;
@property(retain, nonatomic) XRAnalysisCoreUIListDetailSpec *spec; // @synthesize spec=_spec;
- (void).cxx_destruct;
- (BOOL)isValidColumnIdentifier:(id)arg1;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)init;

@end

