//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableDictionary, NSMutableIndexSet;

@interface XRAnalysisCoreRollUpItem : NSObject
{
    unsigned long long _bookmark;
    struct NSMutableArray *_sortedSubItems;
    NSMutableIndexSet *_insertedIndexes;
    XRAnalysisCoreRollUpItem *_parent;
    unsigned char _level;
    NSMutableDictionary *_subItemsByValue;
}

@property(readonly, nonatomic) NSMutableDictionary *subItemsByValue; // @synthesize subItemsByValue=_subItemsByValue;
@property(readonly, nonatomic) XRAnalysisCoreRollUpItem *parent; // @synthesize parent=_parent;
@property(readonly, nonatomic) unsigned long long bookmark; // @synthesize bookmark=_bookmark;
@property(readonly, nonatomic) unsigned char level; // @synthesize level=_level;
- (void).cxx_destruct;
- (void)dealloc;
@property(readonly, nonatomic) NSArray *subitems;
- (void)_updateChangesAndReset:(id)arg1;
- (void)addSubItem:(id)arg1 value:(id)arg2;
- (id)initWithBookmark:(unsigned long long)arg1 level:(unsigned char)arg2;

@end

