//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, XRAnalysisCore, XRAnalysisCorePivotArray, XRAnalysisCoreRowArray, XRAnalysisCoreTableQuery, XRAnalysisCoreTableViewContent, XREngineeringTypeFormatter, XRIntKeyedDictionary;

@interface XRAnalysisCoreTableViewControllerResponse : NSObject
{
    BOOL _updatedDocumentFilter;
    unsigned int _tableID;
    XRAnalysisCoreTableViewContent *_abstractContent;
    XRAnalysisCore *_core;
    XREngineeringTypeFormatter *_formatter;
    XRAnalysisCoreTableQuery *_contentFilter;
    XRAnalysisCoreTableQuery *_documentFilter;
    NSArray *_sortDescriptors;
    XRAnalysisCorePivotArray *_rows;
    XRAnalysisCoreRowArray *_rowsPassingDocumentFilter;
    XRIntKeyedDictionary *_bookmarksPassingFilter;
    unsigned long long _kind;
    NSArray *_selectedSignatures;
}

@property(retain, nonatomic) NSArray *selectedSignatures; // @synthesize selectedSignatures=_selectedSignatures;
@property(nonatomic) unsigned long long kind; // @synthesize kind=_kind;
@property(retain, nonatomic) XRIntKeyedDictionary *bookmarksPassingFilter; // @synthesize bookmarksPassingFilter=_bookmarksPassingFilter;
@property(retain, nonatomic) XRAnalysisCoreRowArray *rowsPassingDocumentFilter; // @synthesize rowsPassingDocumentFilter=_rowsPassingDocumentFilter;
@property(nonatomic) BOOL updatedDocumentFilter; // @synthesize updatedDocumentFilter=_updatedDocumentFilter;
@property(retain, nonatomic) XRAnalysisCorePivotArray *rows; // @synthesize rows=_rows;
@property(retain, nonatomic) NSArray *sortDescriptors; // @synthesize sortDescriptors=_sortDescriptors;
@property(nonatomic) unsigned int tableID; // @synthesize tableID=_tableID;
@property(retain, nonatomic) XRAnalysisCoreTableQuery *documentFilter; // @synthesize documentFilter=_documentFilter;
@property(retain, nonatomic) XRAnalysisCoreTableQuery *contentFilter; // @synthesize contentFilter=_contentFilter;
@property(retain, nonatomic) XREngineeringTypeFormatter *formatter; // @synthesize formatter=_formatter;
@property(nonatomic) __weak XRAnalysisCore *core; // @synthesize core=_core;
@property(retain, nonatomic) XRAnalysisCoreTableViewContent *abstractContent; // @synthesize abstractContent=_abstractContent;
- (void).cxx_destruct;
- (id)init;

@end

