//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DTTimelineDecoratedPlane, NSObject<OS_dispatch_semaphore>, NSOperation, XRAnalysisCore, XRAnalysisCoreRowArray, XRAnalysisCoreTableQuery;

__attribute__((visibility("hidden")))
@interface XRAnalysisCoreConnectionIntervalMonitor : NSObject
{
    NSObject<OS_dispatch_semaphore> *_lock;
    struct unordered_map<unsigned long long, XRBookmark, std::__1::hash<unsigned long long>, std::__1::equal_to<unsigned long long>, std::__1::allocator<std::__1::pair<const unsigned long long, XRBookmark>>> *_uuids;
    unsigned char _uuidColumnID;
    unsigned int _tableID;
    DTTimelineDecoratedPlane *_plane;
    XRAnalysisCore *_core;
    XRAnalysisCoreTableQuery *_query;
    XRAnalysisCoreRowArray *_rowArray;
    NSOperation *_op;
}

@property(retain, nonatomic) NSOperation *op; // @synthesize op=_op;
@property(retain, nonatomic) XRAnalysisCoreRowArray *rowArray; // @synthesize rowArray=_rowArray;
@property(nonatomic) unsigned char uuidColumnID; // @synthesize uuidColumnID=_uuidColumnID;
@property(nonatomic) unsigned int tableID; // @synthesize tableID=_tableID;
@property(retain, nonatomic) XRAnalysisCoreTableQuery *query; // @synthesize query=_query;
@property(nonatomic) __weak XRAnalysisCore *core; // @synthesize core=_core;
@property(nonatomic) __weak DTTimelineDecoratedPlane *plane; // @synthesize plane=_plane;
- (void).cxx_destruct;
- (void)dealloc;
- (id)init;

@end

