//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsKit/XRAnalysisCoreViewFindContext.h>

@class NSIndexSet, XRAnalysisCoreTableViewControllerResponse, XRIntKeyedDictionary;

@interface XRAnalysisCoreTableViewFindContext : XRAnalysisCoreViewFindContext
{
    long long _nextRow;
    long long _resumeAtRow;
    NSIndexSet *_currentColIndicesToSearch;
    XRIntKeyedDictionary *_columnIdentifiersByIndex;
    XRAnalysisCoreTableViewControllerResponse *_response;
    long long _row;
}

@property(readonly, nonatomic) long long row; // @synthesize row=_row;
- (void).cxx_destruct;
- (void)resumeAtRow:(long long)arg1;
- (BOOL)_hasRowAbstractionsToSearch;
- (id)_columnIdentifierForIndex:(long long)arg1;
- (id)_columnIndicesToSearch;
- (void)_searchAbstractionsForMatch;
- (BOOL)performFindNext:(id)arg1;
- (BOOL)_checkAndHandleResumeAtRowAbstraction;
- (void)_restartRowAbstraction;
- (void)_advanceRowAbstraction;
- (id)init;

@end

