//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XRAnalysisCoreValueTreatment.h"

@interface XRAnalysisCoreValueTreatment (Decorators)
- (void)setupPlane:(id)arg1;
- (id)decoratorFromCore:(id)arg1 tableID:(unsigned int)arg2 trace:(id)arg3 runNumber:(long long)arg4 context:(id)arg5;
@end

