//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class XRAnalysisCoreValue;

@interface XRAnalysisCoreValueCellTextComponent : NSObject
{
    XRAnalysisCoreValue *_subvalue;
    struct _NSRange _characterRange;
}

@property(copy, nonatomic) XRAnalysisCoreValue *subvalue; // @synthesize subvalue=_subvalue;
@property(nonatomic) struct _NSRange characterRange; // @synthesize characterRange=_characterRange;
- (void).cxx_destruct;

@end

