//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DTTimelineDecorator.h"

@class XRAnalysisCoreGraphSpec, XRAnalysisCoreTableQuery, XREngineeringTypeFormatter, XRTrace;

@interface XRAnalysisCoreStandardDecorator : DTTimelineDecorator
{
    XRTrace *_trace;
    XREngineeringTypeFormatter *_formatter;
    long long _runNumber;
    XRAnalysisCoreGraphSpec *_graphSpec;
    XRAnalysisCoreTableQuery *_filter;
}

@property(retain, nonatomic) XRAnalysisCoreTableQuery *filter; // @synthesize filter=_filter;
@property(retain, nonatomic) XRAnalysisCoreGraphSpec *graphSpec; // @synthesize graphSpec=_graphSpec;
- (void).cxx_destruct;
- (id)core;
- (unsigned long long)decoratorKind;
- (void)setDefaultsForPlane:(id)arg1;
- (id)init;
- (id)initWithTrace:(id)arg1 runNumber:(long long)arg2 formatter:(id)arg3;

@end

