//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsKit/XRAnalysisCoreQueryBasedDecorator.h>

@class XRTheme;

__attribute__((visibility("hidden")))
@interface XRAnalysisCoreQueryPointDecorator : XRAnalysisCoreQueryBasedDecorator
{
    BOOL _isHighlightable;
    BOOL _isEventType;
    struct _opaque_pthread_rwlock_t _imageRdWrLock;
    struct unordered_map<IconLookup_t, NSImage *, std::__1::hash<IconLookup_t>, std::__1::equal_to<IconLookup_t>, std::__1::allocator<std::__1::pair<const IconLookup_t, NSImage *>>> _iconHash;
    int _iconSize;
    XRTheme *_theme;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)decorateInspectionRanges:(id)arg1 fromCore:(id)arg2 qualityOfService:(unsigned int)arg3 priority:(int)arg4 group:(id)arg5;
- (void)fillContainer:(struct DTTimelineDecorationContainer *)arg1 fromCore:(id)arg2 qualityOfService:(unsigned int)arg3 priority:(int)arg4 group:(id)arg5;
- (id)representativeQueryFromCore:(id)arg1;
- (BOOL)heightChangedForPlane:(id)arg1;
- (BOOL)_setHeightDependantDefaultsForPlane:(id)arg1;
- (void)setDefaultsForPlane:(id)arg1;
- (void)dealloc;
- (id)initWithTrace:(id)arg1 runNumber:(long long)arg2 formatter:(id)arg3;
- (id)initWithTrace:(id)arg1 runNumber:(long long)arg2 formatter:(id)arg3 treatment:(id)arg4 tableID:(unsigned int)arg5 timeColumnID:(unsigned char)arg6 valueColumnID:(unsigned char)arg7 valueLabelColumnID:(unsigned char)arg8 colorColumnID:(unsigned char)arg9 visualConnectionUUIDLabelColumnID:(unsigned char)arg10 selectionCriteria:(id)arg11 selectionColumnIDs:(id)arg12;
- (id)initWithTrace:(id)arg1 runNumber:(long long)arg2 formatter:(id)arg3 treatment:(id)arg4 tableID:(unsigned int)arg5 timeColumnID:(unsigned char)arg6 durationColumnID:(unsigned char)arg7 valueColumnID:(unsigned char)arg8 valueLabelColumnID:(unsigned char)arg9 colorColumnID:(unsigned char)arg10 visualConnectionUUIDLabelColumnID:(unsigned char)arg11 selectionCriteria:(id)arg12 selectionColumnIDs:(id)arg13;

@end

