//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsKit/XRNavButtonsTextCellView.h>

#import "NSAnimationDelegate.h"
#import "XRAnalysisCoreValueCellView.h"

@class NSAttributedString, NSString, XRAnalysisCoreValue, XRAnalysisCoreValueCellTextView, XREngineeringTypeFormatter;

@interface XRAnalysisCoreValueCellView : XRNavButtonsTextCellView <NSAnimationDelegate, XRAnalysisCoreValueCellView>
{
    XREngineeringTypeFormatter *_formatter;
    XRAnalysisCoreValueCellTextView *_customTextView;
    XRAnalysisCoreValue *_value;
    BOOL _customTextViewStale;
    BOOL _rightAligned;
    BOOL _emphasized;
    BOOL _selected;
    BOOL _filteredOut;
    BOOL _diminutivePresentation;
}

+ (BOOL)_mainContentViewIsPrimaryTextField;
+ (id)_createMainContentView;
@property(retain, nonatomic) XREngineeringTypeFormatter *formatter; // @synthesize formatter=_formatter;
@property(nonatomic) BOOL diminutivePresentation; // @synthesize diminutivePresentation=_diminutivePresentation;
@property(nonatomic) BOOL filteredOut; // @synthesize filteredOut=_filteredOut;
@property(nonatomic) BOOL selected; // @synthesize selected=_selected;
@property(nonatomic) BOOL emphasized; // @synthesize emphasized=_emphasized;
- (void).cxx_destruct;
- (BOOL)_actionButtonHugsLeftEdge;
- (id)attributedStringValue;
- (id)stringValue;
- (void)viewDidMoveToWindow;
- (void)showFindIndicatorForRange:(struct _NSRange)arg1;
- (void)_refreshTextView;
- (void)_mapStringForValue:(id)arg1 fromNarrative:(BOOL)arg2 recursionDepth:(int)arg3 intoRangeMap:(id)arg4 intoString:(id)arg5 defaultAttributes:(id)arg6;
@property(copy, nonatomic) NSAttributedString *placeholderString;
- (void)setActionContext:(id)arg1;
- (void)setAnalysisCoreValue:(id)arg1;
- (void)prepareForReuse;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

