//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface XRAnalysisCoreTableViewPersonality : NSObject
{
}

- (BOOL)shouldAddFocusActionToColumn:(id)arg1 abstractContent:(id)arg2;
- (BOOL)rowSelectionDoesNotAffectTimeSelection;
- (BOOL)contentChangesWithTimeInspection;
- (BOOL)adjustRowHeightToFitNarratives;
- (void)personalizeView:(id)arg1 forColumn:(id)arg2;
- (void)personalizeColumnItem:(id)arg1;
- (void)personalizeTableView:(id)arg1;
- (void)personalizeContentFilter:(id)arg1 timeInspection:(unsigned long long)arg2;
- (void)personalizeValueFormatter:(id)arg1;

@end

