//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "XRCallTreeDataSource.h"
#import "XRFilteredDataSource.h"

@class NSMutableDictionary, NSString, NSTimer, XRAnalysisCoreProjector, XRCallTreeDetailView, XREngineeringTypeFormatter, XRInstrumentControlState, XRIntKeyedDictionary, XRMultiProcessBacktraceRepository, XRSlidingCapableScrollView;

@interface XRAnalysisCoreCallTreeViewController : NSViewController <XRCallTreeDataSource, XRFilteredDataSource>
{
    XRSlidingCapableScrollView *_callTreeScrollView;
    XRCallTreeDetailView *_callTreeView;
    XRMultiProcessBacktraceRepository *_backtraceRepository;
    XRIntKeyedDictionary *_wrappers;
    NSMutableDictionary *_aggregatorByCategory;
    unsigned int _backtraceAggIdx;
    unsigned char _backtraceDim;
    unsigned char _threadDim;
    unsigned char _categoryDim;
    NSString *_categoryDimName;
    XREngineeringTypeFormatter *_myEngFormatter;
    XRAnalysisCoreProjector *_projector;
    NSTimer *_deferredSelectionUpdateTimer;
    id <XRAnalysisCoreCallTreeViewControllerDelegate> _delegate;
    XRInstrumentControlState *_interfaceControlSettings;
}

@property(retain, nonatomic) XRInstrumentControlState *interfaceControlSettings; // @synthesize interfaceControlSettings=_interfaceControlSettings;
@property(nonatomic) __weak id <XRAnalysisCoreCallTreeViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)filterDetailWithTokens:(id)arg1 context:(id)arg2 matchesAny:(BOOL)arg3;
- (id)searchContexts;
- (id)selectedSearchContext;
- (void)refineQueryBasedOnUIState:(id)arg1;
- (id)contextRepresentation;
- (id)currentCallTreeFilter;
- (void)_stackFrameSelected:(id)arg1;
- (void)_focusOnCallTreeNode:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)dataElementForHeaviestStack;
- (id)dataMiningElementsWithState;
- (id)processCategoriesForPid:(int)arg1;
- (id)provideCategories;
- (id)backtracesForCategory:(id)arg1 timeRange:(struct XRTimeRange)arg2 savedIndex:(unsigned long long *)arg3;
- (void)resetAggregatesForRepository:(id)arg1;
- (void)_deferredSelectionTimeout:(id)arg1;
- (void)restoreUIState:(id)arg1 subcontext:(id)arg2;
- (void)saveUIState:(id)arg1;
- (void)refresh;
- (void)instrumentWillBecomeInvalid;
- (void)_mainThreadAdaptCallTree;
- (void)_mainThreadFillAggregator;
- (void)_mainThreadRepoDidReset;
- (void)viewWillLayout;
- (void)viewWillAppear;
- (void)loadView;
- (void)setRepresentedObject:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

