//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableRowView.h"

#import "XRAnalysisCoreTableViewRow.h"

@class NSString;

@interface XRAnalysisCoreTableViewRow : NSTableRowView <XRAnalysisCoreTableViewRow>
{
    long long _signature;
    unsigned long long _edgeDecoration;
}

+ (void)copySelectionToPasteboardFromAnalysisCoreTableView:(id)arg1;
@property(nonatomic) unsigned long long edgeDecoration; // @synthesize edgeDecoration=_edgeDecoration;
@property(nonatomic) long long signature; // @synthesize signature=_signature;
- (id)attributedStringValue;
- (void)setSelected:(BOOL)arg1;
- (void)setEmphasized:(BOOL)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)didAddSubview:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

