//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class XRAnalysisCoreTableViewController;

@protocol XRAnalysisCoreTableViewControllerDelegate <NSObject>

@optional
- (void)tableViewController:(XRAnalysisCoreTableViewController *)arg1 selectedAndEventAtTime:(unsigned long long)arg2;
@end

