//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray, NSMutableDictionary, XRTrace;

__attribute__((visibility("hidden")))
@interface XRAnalysisCoreConnectionIntervalModel : NSObject
{
    XRTrace *_trace;
    long long _runNumber;
    unsigned long long _filterValue;
    NSMutableDictionary *_visualConnectionTableToColumnMaps;
    NSMutableArray *_monitoringInfo;
    struct _opaque_pthread_mutex_t _lock;
    NSArray *_visualConnectionTableIDs;
}

@property(copy, nonatomic) NSArray *visualConnectionTableIDs; // @synthesize visualConnectionTableIDs=_visualConnectionTableIDs;
- (void).cxx_destruct;
- (void)accessLocked:(CDUnknownBlockType)arg1;
- (id)columnMapForTable:(unsigned int)arg1;
- (void)applyHighlightsToPlanesForUUIDs:(const unsigned long long *)arg1 count:(unsigned int)arg2;
- (id)planeForUUID:(unsigned int)arg1;
- (BOOL)tick;
- (void)setGroupPlanesToMonitor:(id)arg1;
- (void)_monitorPlaneOrGroupPlane:(id)arg1 core:(id)arg2;
- (void)_monitorPlane:(id)arg1 core:(id)arg2;
- (void)_processMonitor:(id)arg1 startingRow:(unsigned int)arg2;
- (void)setFilterValue:(unsigned long long)arg1;
- (void)dealloc;
- (id)initWithTrace:(id)arg1 runNumber:(long long)arg2;

@end

