//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsKit/XRAnalysisCoreQueryBasedDecorator.h>

@class NSColor, NSImage;

__attribute__((visibility("hidden")))
@interface XRAnalysisCoreQueryIntervalDecorator : XRAnalysisCoreQueryBasedDecorator
{
    NSColor *_defaultHighlightColor;
    NSColor *_defaultTextHighlightColor;
    NSImage *_defaultHighlightDrawableIcon;
    double _planeHeight;
    double _textHeight;
    int _iconSize;
    BOOL _isHighlightable;
    BOOL _isEventType;
}

- (void).cxx_destruct;
- (void)decorateInspectionRanges:(id)arg1 fromCore:(id)arg2 qualityOfService:(unsigned int)arg3 priority:(int)arg4 group:(id)arg5;
- (void)fillContainer:(struct DTTimelineDecorationContainer *)arg1 fromCore:(id)arg2 qualityOfService:(unsigned int)arg3 priority:(int)arg4 group:(id)arg5;
- (id)representativeQueryFromCore:(id)arg1;
- (BOOL)heightChangedForPlane:(id)arg1;
- (BOOL)_setHeightDependantDefaultsForPlane:(id)arg1;
- (void)setDefaultsForPlane:(id)arg1;
- (id)initWithTrace:(id)arg1 runNumber:(long long)arg2 formatter:(id)arg3 treatment:(id)arg4 tableID:(unsigned int)arg5 timeColumnID:(unsigned char)arg6 durationColumnID:(unsigned char)arg7 valueColumnID:(unsigned char)arg8 valueLabelColumnID:(unsigned char)arg9 colorColumnID:(unsigned char)arg10 visualConnectionUUIDLabelColumnID:(unsigned char)arg11 selectionCriteria:(id)arg12 selectionColumnIDs:(id)arg13;

@end

