//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsKit/XRAnalysisCoreDetailViewContent.h>

@class NSArray, NSMutableSet, NSString, XRAnalysisCoreUIProjectionDetailSpec;

@interface XRAnalysisCoreProjectionViewContent : XRAnalysisCoreDetailViewContent
{
    NSMutableSet *__cachedColIDs;
    unsigned char _backtraceDim;
    unsigned char _threadDim;
    unsigned char _categoryDim;
    BOOL _hasOnFocusDetail;
    XRAnalysisCoreUIProjectionDetailSpec *_spec;
    NSArray *_projectorHierarchy;
    NSString *_categoryDimName;
}

@property(nonatomic) BOOL hasOnFocusDetail; // @synthesize hasOnFocusDetail=_hasOnFocusDetail;
@property(copy, nonatomic) NSString *categoryDimName; // @synthesize categoryDimName=_categoryDimName;
@property(nonatomic) unsigned char categoryDim; // @synthesize categoryDim=_categoryDim;
@property(nonatomic) unsigned char threadDim; // @synthesize threadDim=_threadDim;
@property(nonatomic) unsigned char backtraceDim; // @synthesize backtraceDim=_backtraceDim;
@property(copy, nonatomic) NSArray *projectorHierarchy; // @synthesize projectorHierarchy=_projectorHierarchy;
@property(retain, nonatomic) XRAnalysisCoreUIProjectionDetailSpec *spec; // @synthesize spec=_spec;
- (void).cxx_destruct;
- (BOOL)isValidColumnIdentifier:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (id)init;

@end

