//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XRAnalysisCoreGraphSpec.h"

@class NSColor;

@interface XRAnalysisCoreGraphSpec (AppKitAdditions)
- (void)encodeAppKitParts:(id)arg1;
- (void)decodeAppKitParts:(id)arg1;
@property(readonly, nonatomic) NSColor *overrideTextColor;
@property(readonly, nonatomic) NSColor *overrideColor;
@end

