//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "XRAnalysisCoreQueryHandler.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface XRAnalysisCoreQueryIntervalDecoratorHandler : NSObject <XRAnalysisCoreQueryHandler>
{
    struct _opaque_pthread_mutex_t _lock;
    struct DTTimelineDecorationContainer *_container;
    unsigned char _timeColumnID;
    unsigned char _durationColumnID;
    unsigned char _valueColumnID;
    unsigned short _valueEngineeringType;
    unsigned char _valueColumnImpType;
    int _nextAvailableLabel;
    unsigned long long _highlightType;
    union XRBookmark _highlightBookmark;
    const vector_59b01178 *_highlightBookmarks;
}

- (void)reduceFromLocalResults:(id)arg1;
- (void)runWorkgroup:(unsigned short)arg1 of:(unsigned int)arg2 withLocalResults:(id)arg3 context:(id)arg4 rowIterator:(struct XRAnalysisCoreReadCursor *)arg5;
- (void)dealloc;
- (id)initWithContainer:(struct DTTimelineDecorationContainer *)arg1 timeColumnID:(unsigned char)arg2 durationColumnID:(unsigned char)arg3 valueColumnID:(unsigned char)arg4 valueEngineeringType:(unsigned short)arg5 valueColumnImpType:(unsigned char)arg6 highlightBookmarks:(const vector_59b01178 *)arg7;
- (id)initWithContainer:(struct DTTimelineDecorationContainer *)arg1 timeColumnID:(unsigned char)arg2 durationColumnID:(unsigned char)arg3 valueColumnID:(unsigned char)arg4 valueEngineeringType:(unsigned short)arg5 valueColumnImpType:(unsigned char)arg6 highlightBookmark:(union XRBookmark)arg7;
- (id)initWithContainer:(struct DTTimelineDecorationContainer *)arg1 timeColumnID:(unsigned char)arg2 durationColumnID:(unsigned char)arg3 valueColumnID:(unsigned char)arg4 valueEngineeringType:(unsigned short)arg5 valueColumnImpType:(unsigned char)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

