//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsKit/XRAnalysisCoreStandardDecorator.h>

@class NSArray, NSDictionary, NSString, XRAnalysisCoreValue, XRAnalysisCoreValueTreatment;

__attribute__((visibility("hidden")))
@interface XRAnalysisCoreQueryBasedDecorator : XRAnalysisCoreStandardDecorator
{
    XRAnalysisCoreValueTreatment *_treatment;
    unsigned int _tableID;
    unsigned char _timeColumnID;
    unsigned char _durationColumnID;
    unsigned char _valueColumnID;
    unsigned char _valueLabelColumnID;
    unsigned char _colorColumnID;
    unsigned char _visualConnectionUUIDLabelColumnID;
    unsigned char _valueColumnImpType;
    unsigned short _valueEngineeringType;
    unsigned short _valueLabelEngineeringType;
    unsigned char _colorColumnImpType;
    unsigned short _colorEngineeringType;
    NSArray *_selectionCriteria;
    NSDictionary *_selectionColumnIDs;
    unsigned long long _highlightType;
    union XRBookmark _highlightBookmark;
    vector_59b01178 _highlightBookmarks;
    XRAnalysisCoreValue *_groupByValue;
    NSString *_groupByColumnName;
    NSString *_valueQualifierValue;
    NSString *_valueQualifierColumnName;
}

@property(readonly) unsigned char visualConnectionUUIDLabelColumnID; // @synthesize visualConnectionUUIDLabelColumnID=_visualConnectionUUIDLabelColumnID;
@property(readonly) unsigned char valueColumnID; // @synthesize valueColumnID=_valueColumnID;
@property(readonly) unsigned char durationColumnID; // @synthesize durationColumnID=_durationColumnID;
@property(readonly) unsigned char timeColumnID; // @synthesize timeColumnID=_timeColumnID;
@property(copy, nonatomic) NSString *valueQualifierColumnName; // @synthesize valueQualifierColumnName=_valueQualifierColumnName;
@property(copy, nonatomic) NSString *valueQualifierValue; // @synthesize valueQualifierValue=_valueQualifierValue;
@property(copy, nonatomic) NSString *groupByColumnName; // @synthesize groupByColumnName=_groupByColumnName;
@property(copy, nonatomic) XRAnalysisCoreValue *groupByValue; // @synthesize groupByValue=_groupByValue;
- (id).cxx_construct;
- (void).cxx_destruct;
- (const vector_59b01178 *)highlightBookmarks;
- (void)setHighlightBookmarks:(const vector_59b01178 *)arg1;
- (union XRBookmark)highlightBookmark;
- (void)setHighlightBookmark:(union XRBookmark)arg1;
- (unsigned long long)highlightType;
- (void)clearAllHighlights;
- (unsigned long long)decoratorKind;
- (void)decorateInspectionRanges:(id)arg1 qualityOfService:(unsigned int)arg2 priority:(int)arg3 group:(id)arg4;
- (void)decorateContainer:(struct DTTimelineDecorationContainer *)arg1 qualityOfService:(unsigned int)arg2 priority:(int)arg3 group:(id)arg4;
- (unsigned int)tableID;
- (id)representativeQueryFromCore:(id)arg1;
- (void)decorateInspectionRanges:(id)arg1 fromCore:(id)arg2 qualityOfService:(unsigned int)arg3 priority:(int)arg4 group:(id)arg5;
- (void)fillContainer:(struct DTTimelineDecorationContainer *)arg1 fromCore:(id)arg2 qualityOfService:(unsigned int)arg3 priority:(int)arg4 group:(id)arg5;
- (id)_createColumnSelectionValueSets:(id)arg1 schema:(id)arg2;
- (void)setDefaultColorsForPlane:(id)arg1 withEngineeringType:(unsigned short)arg2;
- (id)initWithTrace:(id)arg1 runNumber:(long long)arg2 formatter:(id)arg3;
- (id)initWithTrace:(id)arg1 runNumber:(long long)arg2 formatter:(id)arg3 treatment:(id)arg4 tableID:(unsigned int)arg5 timeColumnID:(unsigned char)arg6 durationColumnID:(unsigned char)arg7 valueColumnID:(unsigned char)arg8 valueLabelColumnID:(unsigned char)arg9 colorColumnID:(unsigned char)arg10 visualConnectionUUIDLabelColumnID:(unsigned char)arg11 selectionCriteria:(id)arg12 selectionColumnIDs:(id)arg13;

@end

