//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "XRAnalysisCoreQueryHandler.h"

@class NSString, XRAnalysisCoreConnectionIntervalModel;

__attribute__((visibility("hidden")))
@interface XRAnalysisCoreConnectionIntervalDecoratorHandler : NSObject <XRAnalysisCoreQueryHandler>
{
    struct _opaque_pthread_mutex_t _lock;
    struct DTTimelineDecorationContainer *_container;
    XRAnalysisCoreConnectionIntervalModel *_model;
    unsigned char _timeColumnID;
    unsigned char _durationColumnID;
    unsigned char _uuidColumnID;
    unsigned char _filterColumnID;
    set_4cedab1c *_highlightUUIDs;
}

- (void).cxx_destruct;
- (void)reduceFromLocalResults:(id)arg1;
- (void)runWorkgroup:(unsigned short)arg1 of:(unsigned int)arg2 withLocalResults:(id)arg3 context:(id)arg4 rowIterator:(struct XRAnalysisCoreReadCursor *)arg5;
- (void)dealloc;
- (id)initWithContainer:(struct DTTimelineDecorationContainer *)arg1 columnMap:(id)arg2 model:(id)arg3 highlightUUIDs:(set_4cedab1c *)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

