//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "XRAnalysisCoreQueryHandler.h"

@class NSObject<OS_dispatch_semaphore>, NSString;

__attribute__((visibility("hidden")))
@interface XRAnalysisCoreQueryPeakDecoratorHandler : NSObject <XRAnalysisCoreQueryHandler>
{
    NSObject<OS_dispatch_semaphore> *_lock;
    struct DTTimelineDecorationContainer *_container;
    unsigned char _timeColumnID;
    unsigned char _valueColumnID;
    unsigned char _labelColumnID;
    unsigned char _valueColumnImpType;
    int _nextAvailableLabel;
    unsigned long long _highlightType;
    union XRBookmark _highlightBookmark;
    const vector_59b01178 *_highlightBookmarks;
}

- (void).cxx_destruct;
- (void)reduceFromLocalResults:(id)arg1;
- (void)runWorkgroup:(unsigned short)arg1 of:(unsigned int)arg2 withLocalResults:(id)arg3 context:(id)arg4 rowIterator:(struct XRAnalysisCoreReadCursor *)arg5;
- (id)initWithContainer:(struct DTTimelineDecorationContainer *)arg1 timeColumnID:(unsigned char)arg2 valueColumnID:(unsigned char)arg3 lableColumnID:(unsigned char)arg4 valueColumnImpType:(unsigned char)arg5 highlightBookmarks:(const vector_59b01178 *)arg6;
- (id)initWithContainer:(struct DTTimelineDecorationContainer *)arg1 timeColumnID:(unsigned char)arg2 valueColumnID:(unsigned char)arg3 lableColumnID:(unsigned char)arg4 valueColumnImpType:(unsigned char)arg5 highlightBookmark:(union XRBookmark)arg6;
- (id)initWithContainer:(struct DTTimelineDecorationContainer *)arg1 timeColumnID:(unsigned char)arg2 valueColumnID:(unsigned char)arg3 lableColumnID:(unsigned char)arg4 valueColumnImpType:(unsigned char)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

