//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsKit/XRAction.h>

@interface XRAnalysisCoreValueAction : XRAction
{
}

+ (id)createActionWithEtypeActionElement:(id)arg1 handler:(id)arg2;
- (id)initWithIdentifier:(id)arg1 handler:(id)arg2 engineeringType:(unsigned short)arg3 displayName:(id)arg4 actionSelector:(id)arg5 appleInternal:(BOOL)arg6;

@end

