//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsKit/XRAnalysisCoreStandardDecorator.h>

@class XRAnalysisCoreProjector;

@interface XRAnalysisCoreProjectionBasedDecorator : XRAnalysisCoreStandardDecorator
{
    XRAnalysisCoreProjector *_projector;
}

- (void).cxx_destruct;
- (id)decorateContainer:(struct DTTimelineDecorationContainer *)arg1;
- (void)setDefaultsForPlane:(id)arg1;
- (id)fillContainer:(struct DTTimelineDecorationContainer *)arg1 fromProjector:(id)arg2;
- (id)initWithTrace:(id)arg1 runNumber:(long long)arg2 formatter:(id)arg3;
- (id)initWithTrace:(id)arg1 runNumber:(long long)arg2 formatter:(id)arg3 projector:(id)arg4;

@end

