//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsKit/XRScopedTextControl.h>

#import "DVTSourceTextViewDelegate.h"
#import "XRFilteredDataSource.h"
#import "XRLazyKVOResponder.h"

@class NSArray, NSArrayController, NSMutableArray, NSPredicate, NSRulerMarker, NSString, PFTTraceDocument, XRLazyKVOAdapter;

@interface XRConsoleControl : XRScopedTextControl <XRLazyKVOResponder, DVTSourceTextViewDelegate, XRFilteredDataSource>
{
    PFTTraceDocument *_traceDocument;
    NSArrayController *_logController;
    long long _runBeingObserved;
    unsigned long long _logCount;
    NSPredicate *_textFilterPredicate;
    long long _lastFilteredEntryDisplayed;
    int _previousType;
    NSMutableArray *_logEventPositionLineRanges;
    NSMutableArray *_logEventPositionEvents;
    BOOL _selectingEvent;
    NSRulerMarker *_timeSelectedMarker;
    struct _NSRange _outputRange;
    struct _NSRange _promptRange;
    XRLazyKVOAdapter *_kvoAdapter;
    NSArray *_consoleTableMonitors;
}

+ (void)initialize;
- (void).cxx_destruct;
- (void)_eventHorizonFromCore:(id)arg1 withTimeRange:(struct XRTimeRange)arg2 startTime:(unsigned long long)arg3 trace:(id)arg4 runNumber:(long long)arg5 logStorage:(id)arg6;
- (void)setSelectedEvent:(id)arg1;
- (void)_moveMarkerToLine:(unsigned long long)arg1;
- (id)samplesInRange:(struct XRTimeRange)arg1;
- (void)inspectionHeadUpdated:(id)arg1;
- (void)filterDetailWithTokens:(id)arg1 context:(id)arg2 matchesAny:(BOOL)arg3;
- (void)_runDidEnd:(id)arg1;
- (void)_logUpdated:(id)arg1;
- (BOOL)textView:(id)arg1 doCommandBySelector:(SEL)arg2;
- (struct _NSRange)textView:(id)arg1 willChangeSelectionFromCharacterRange:(struct _NSRange)arg2 toCharacterRange:(struct _NSRange)arg3;
- (BOOL)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)updateLogWithEventRange:(struct _NSRange)arg1 clearBeforeUpdate:(BOOL)arg2;
- (id)promptString;
- (void)viewWillMoveToSuperview:(id)arg1;
- (void)observeRunNumber:(long long)arg1;
- (void)_setUpConsoleTableMonitorsForCore:(id)arg1;
- (void)handleLazyKVOUpdate:(id)arg1;
- (void)setFilterPredicate:(id)arg1;
- (void)applyCurrentFilter;
- (void)_clearTextView;
- (void)_setWatermark;
- (id)customWatermark;
- (id)detailViewLabel;
- (id)classForNibName;
- (void)dealloc;
- (void)invalidate;
- (id)initWithDocument:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

