//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class NSObject<XRBrushProvider>, NSStackView, NSTextField;

@interface XRControlBandViewController : NSViewController
{
    BOOL _useRadio;
    NSTextField *_styleChooserLabel;
    NSStackView *_stackView;
    NSObject<XRBrushProvider> *_brushable;
}

+ (void)initialize;
@property(nonatomic) BOOL useRadio; // @synthesize useRadio=_useRadio;
@property(retain, nonatomic) NSObject<XRBrushProvider> *brushable; // @synthesize brushable=_brushable;
@property(nonatomic) __weak NSStackView *stackView; // @synthesize stackView=_stackView;
@property(nonatomic) __weak NSTextField *styleChooserLabel; // @synthesize styleChooserLabel=_styleChooserLabel;
- (void).cxx_destruct;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)awakeFromNib;
- (void)radioChanged:(id)arg1;
- (id)createMenuForBrushable:(id)arg1;
- (void)dealloc;
- (id)initWithBrushable:(id)arg1 useRadio:(BOOL)arg2;
- (id)initWithBrushable:(id)arg1;

@end

