//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsKit/XRPreferencesModule.h>

#import "XRCPUmanagerDelegateProtocol.h"

@class NSButton, NSSlider, NSString, NSTextField, XRCPUmanager;

@interface XRCPUsPreferencesModule : XRPreferencesModule <XRCPUmanagerDelegateProtocol>
{
    XRCPUmanager *_processorMgr;
    NSSlider *_activeProcessorsSlider;
    NSTextField *_activeProcessorsText;
    NSTextField *_maxProcessorsText;
    NSButton *_activeProcessorsHTCheck;
}

@property __weak NSButton *activeProcessorsHTCheck; // @synthesize activeProcessorsHTCheck=_activeProcessorsHTCheck;
@property __weak NSTextField *maxProcessorsText; // @synthesize maxProcessorsText=_maxProcessorsText;
@property __weak NSTextField *activeProcessorsText; // @synthesize activeProcessorsText=_activeProcessorsText;
@property __weak NSSlider *activeProcessorsSlider; // @synthesize activeProcessorsSlider=_activeProcessorsSlider;
- (void).cxx_destruct;
- (void)updateActiveProcessorCoreCount;
- (void)_updateActiveProcessorCoreCount;
- (void)toggleHyperThreading:(id)arg1;
- (void)changeActiveProcessorCores:(id)arg1;
- (BOOL)isResizable;
- (id)imageForPreferenceNamed:(id)arg1;
- (void)initializeFromDefaults;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

