//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class NSArray, NSView;

@interface XRDataElementPopoverViewController : NSViewController
{
    unsigned long long _style;
    BOOL _allowTitles;
    NSArray *_elements;
    NSView *_dataView;
}

@property __weak NSView *dataView; // @synthesize dataView=_dataView;
@property(readonly, nonatomic) BOOL allowTitles; // @synthesize allowTitles=_allowTitles;
@property(readonly, nonatomic) NSArray *elements; // @synthesize elements=_elements;
- (void).cxx_destruct;
- (void)viewWillAppear;
- (void)viewDidAppear;
- (void)reloadData;
- (void)awakeFromNib;
- (id)initWithDataElements:(id)arg1 style:(unsigned long long)arg2 allowTitles:(BOOL)arg3;

@end

