//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsKit/XRNonInteractiveModeViewController.h>

@class NSProgressIndicator, NSTextField;

@interface XRDetailViewBusyModeController : XRNonInteractiveModeViewController
{
    NSProgressIndicator *_progressView;
    NSTextField *_progressText;
}

@property(nonatomic) __weak NSTextField *progressText; // @synthesize progressText=_progressText;
@property(nonatomic) __weak NSProgressIndicator *progressView; // @synthesize progressView=_progressView;
- (void).cxx_destruct;
- (void)_setProgressMessage:(id)arg1 additionalMessage:(id)arg2;
- (void)_setProgressCompletion:(double)arg1;
- (void)viewDidLoad;
- (id)init;

@end

