//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class NSTextField;

@interface XRDetailViewSplashViewController : NSViewController
{
    NSTextField *_descriptionView;
    NSTextField *_recoveryView;
}

@property __weak NSTextField *recoveryView; // @synthesize recoveryView=_recoveryView;
@property __weak NSTextField *descriptionView; // @synthesize descriptionView=_descriptionView;
- (void).cxx_destruct;
- (void)setDescription:(id)arg1 recovery:(id)arg2;
- (void)viewDidLoad;
- (id)nibBundle;
- (id)nibName;

@end

