//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSSortDescriptor.h"

#import "XRAnalysisCoreSortDescriptor.h"

@class NSString, XREngineeringTypeFormatter;

@interface XREngineeringTypeSortDescriptor : NSSortDescriptor <XRAnalysisCoreSortDescriptor>
{
    struct XRIntKeyedDictionary *_sigMapsByEtype;
    NSString *_identifier;
    long long _runNumber;
    XREngineeringTypeFormatter *_formatter;
}

- (void).cxx_destruct;
- (long long)compareObject:(id)arg1 toObject:(id)arg2;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)reversedSortDescriptor;
- (void)sortDidFinish;
- (void)sortWillBegin;
- (id)initWithTrace:(id)arg1 runNumber:(long long)arg2 columnIdentifier:(id)arg3 ascending:(BOOL)arg4;
- (BOOL)isEqual:(id)arg1;
- (id)initWithFormatter:(id)arg1 runNumber:(long long)arg2 columnIdentifier:(id)arg3 ascending:(BOOL)arg4;

@end

