//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSFormatter.h"

@class NSNumberFormatter, XRProcessSet, XRThreadSet, XRUsernameSet;

@interface XREngineeringTypeFormatter : NSFormatter
{
    NSNumberFormatter *_countFormatter;
    NSNumberFormatter *_intIDFormatter;
    NSNumberFormatter *_fpsFormatter;
    NSNumberFormatter *_fixedDecimalFormatter;
    XRThreadSet *_threadSet;
    XRProcessSet *_procSet;
    XRUsernameSet *_usernameSet;
    long long _runNumber;
    BOOL _includeProcessNameWithThread;
    BOOL _multiline;
}

+ (id)stringForValue:(id)arg1 threadSet:(id)arg2 processSet:(id)arg3 usernameSet:(id)arg4 runNumber:(long long)arg5;
@property(nonatomic, getter=isMultiline) BOOL multiline; // @synthesize multiline=_multiline;
@property(nonatomic) BOOL includeProcessNameWithThread; // @synthesize includeProcessNameWithThread=_includeProcessNameWithThread;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (BOOL)getObjectValue:(out id *)arg1 forString:(id)arg2 errorDescription:(out id *)arg3;
- (id)attributedStringForNarrativeSubvalue:(id)arg1 withDefaultAttributes:(id)arg2;
- (id)attributedStringForObjectValue:(id)arg1 withDefaultAttributes:(id)arg2;
- (id)stringForObjectValue:(id)arg1;
- (id)init;
- (id)initWithTrace:(id)arg1 runNumber:(long long)arg2;

@end

