//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class XRIntKeyedDictionary;

@interface XRExistenceProjectorsForRun : NSObject
{
    XRIntKeyedDictionary *_tableProjectors;
}

@property(retain, nonatomic) XRIntKeyedDictionary *tableProjectors; // @synthesize tableProjectors=_tableProjectors;
- (void).cxx_destruct;
- (id)init;

@end

