//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, XRAnalysisCoreProjector;

@interface XRExistanceProjectorForTableColumn : NSObject
{
    unsigned char _columnID;
    unsigned char _subColumnID;
    unsigned int _tableID;
    XRAnalysisCoreProjector *_projector;
    unsigned long long _lastCount;
    NSMutableDictionary *_subProjections;
}

@property(readonly, retain, nonatomic) NSMutableDictionary *subProjections; // @synthesize subProjections=_subProjections;
@property(readonly, nonatomic) unsigned char subColumnID; // @synthesize subColumnID=_subColumnID;
@property(nonatomic) unsigned long long lastCount; // @synthesize lastCount=_lastCount;
@property(readonly, retain, nonatomic) XRAnalysisCoreProjector *projector; // @synthesize projector=_projector;
@property(nonatomic) unsigned char columnID; // @synthesize columnID=_columnID;
@property(nonatomic) unsigned int tableID; // @synthesize tableID=_tableID;
- (void).cxx_destruct;
- (BOOL)hasSubColumn;
- (id)initWithProjector:(id)arg1 tableID:(unsigned int)arg2 columnID:(unsigned char)arg3 subColumnID:(unsigned char)arg4;
- (id)initWithProjector:(id)arg1 tableID:(unsigned int)arg2 columnID:(unsigned char)arg3;

@end

