//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "XRTopicInterfaceComponent.h"

@class NSBrowser, NSDictionary, NSString, XRDeviceTopic, XRTopic;

@interface XRFileExplorerViewController : NSViewController <XRTopicInterfaceComponent>
{
    XRTopic *_subTopic;
    NSBrowser *_browser;
    XRDeviceTopic *_topic;
    id <XRFileSystem> _fileSystem;
}

@property(readonly, nonatomic) id <XRFileSystem> fileSystem; // @synthesize fileSystem=_fileSystem;
@property(readonly, nonatomic) XRDeviceTopic *topic; // @synthesize topic=_topic;
@property(nonatomic) __weak NSBrowser *browser; // @synthesize browser=_browser;
@property(retain, nonatomic) XRTopic *subTopic; // @synthesize subTopic=_subTopic;
- (void).cxx_destruct;
- (void)_selectItemAtPath:(id)arg1 reparentIfNeeded:(BOOL)arg2;
- (void)_selectItemAtPath:(id)arg1;
- (int)topicViewer:(id)arg1 handleKeyDown:(id)arg2;
- (void)refresh;
- (void)reloadData;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)viewDidDisappear;
- (void)viewWillAppear;
- (void)applyResult:(id)arg1;
- (void)select:(id)arg1;
@property(readonly, nonatomic) NSString *filename;
@property(readonly, nonatomic) NSDictionary *selectedItem;
- (id)validateSelection;
- (id)launchOptionsUserInterfaceComponentIdentifier;
- (void)awakeFromNib;
- (id)initWithTopic:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

