//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

#import "NSOutlineViewDelegate.h"
#import "NSWindowDelegate.h"

@class DVTSearchField, NSArray, NSMenu, NSMutableArray, NSOutlineView, NSString, PFTTraceDocument, XRFlagController;

@interface XRFlagViewer : NSWindowController <NSWindowDelegate, NSOutlineViewDelegate>
{
    XRFlagController *_flagController;
    NSArray *_searchMenuItemsArray;
    NSArray *_flagColumnArray;
    NSArray *_flagColumnMenuItemsArray;
    BOOL _flagTableDeferReload;
    BOOL _ignoreColumnMoves;
    NSMutableArray *_flagColumnsToSearch;
    NSMutableArray *_searchedFlags;
    NSOutlineView *_flagOutline;
    NSMenu *_tableColumnMenu;
    NSMenu *_displayStateMenu;
    DVTSearchField *_flagTableSearchField;
    NSMenu *_searchColumnMenu;
}

+ (id)sharedInstance;
+ (union _flagTableFilter_u)defaultFlagFilter;
+ (union _flagTableFilter_u)flagFilterForDocument:(id)arg1 runNumber:(long long)arg2;
+ (void)setFlagFilter:(union _flagTableFilter_u)arg1 forDocument:(id)arg2 runNumber:(long long)arg3;
@property(retain, nonatomic) NSMenu *searchColumnMenu; // @synthesize searchColumnMenu=_searchColumnMenu;
@property(nonatomic) __weak DVTSearchField *flagTableSearchField; // @synthesize flagTableSearchField=_flagTableSearchField;
@property(retain, nonatomic) NSMenu *displayStateMenu; // @synthesize displayStateMenu=_displayStateMenu;
@property(retain, nonatomic) NSMenu *tableColumnMenu; // @synthesize tableColumnMenu=_tableColumnMenu;
@property(nonatomic) __weak NSOutlineView *flagOutline; // @synthesize flagOutline=_flagOutline;
- (void).cxx_destruct;
- (void)flagModifiedResponse:(id)arg1;
- (void)setSearchCategoryFrom:(id)arg1;
- (void)searchFlagTableAction:(id)arg1;
- (void)inspectFlagAction:(id)arg1;
- (void)columnVisibleAction:(id)arg1;
- (void)displayFilterAction:(id)arg1;
- (void)flagMenuAction:(id)arg1;
- (void)flagRangeAction:(id)arg1;
- (void)reloadFlagTable;
- (void)dealloc;
- (id)windowTitleForDocumentDisplayName:(id)arg1;
- (void)updateRunNumber:(id)arg1;
@property(readonly, nonatomic) PFTTraceDocument *traceDocument;
- (BOOL)outlineView:(id)arg1 shouldEditTableColumn:(id)arg2 item:(id)arg3;
- (void)outlineView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 item:(id)arg4;
- (void)outlineViewSelectionDidChange:(id)arg1;
- (void)setDocument:(id)arg1;
- (void)close;
- (BOOL)shouldCloseDocument;
- (void)refreshDisplayStateFilterMenuWith:(union _flagTableFilter_u)arg1;
- (void)tableViewColumnDidMove:(id)arg1;
- (void)_processNewSignalFlags:(id)arg1;
- (void)windowDidLoad;
- (void)updateSearchCategoryMenu;
- (void)updateColumnHidingMenu;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

