//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsKit/XRActionHandler.h>

@interface XRGeneralActionPlugIn : XRActionHandler
{
}

- (void)copyValueAsText:(id)arg1 withContext:(id)arg2;
- (void)addFilterToken:(id)arg1 withContext:(id)arg2;
- (void)removeProcessFromFilter:(id)arg1 withContext:(id)arg2;
- (void)addProcessToFilter:(id)arg1 withContext:(id)arg2;
- (void)setInspectionRange:(id)arg1 withContext:(id)arg2;
- (void)moveInspectionHead:(id)arg1 withContext:(id)arg2;
- (void)addInstrumentOfType:(id)arg1 withContext:(id)arg2;
- (void)showSchedulingLoad:(id)arg1 withContext:(id)arg2;
- (void)lookupSystemCallDocs:(id)arg1 withContext:(id)arg2;
- (void)revealFilePathInFinder:(id)arg1 withContext:(id)arg2;
- (void)revealCPUInCPUStrategy:(id)arg1 withContext:(id)arg2;
- (void)pinCore:(id)arg1 withContext:(id)arg2;
- (void)revealThreadInThreadStrategy:(id)arg1 withContext:(id)arg2;
- (void)pinThread:(id)arg1 withContext:(id)arg2;
- (void)pinProcess:(id)arg1 withContext:(id)arg2;
- (void)_pardonOurDust;
- (void)lookupAPIWithTargets:(id)arg1 withContext:(id)arg2;
- (id)displayNameForAction:(id)arg1 targets:(id)arg2 context:(id)arg3;
- (BOOL)validateAction:(id)arg1 targets:(id)arg2 context:(id)arg3;
- (void)_progressSheetEnded:(id)arg1 returnCode:(int)arg2 contextInfo:(void *)arg3;
- (void)symbolInspector:(id)arg1 withContext:(id)arg2;

@end

