//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsKit/XRPreferencesModule.h>

#import "NSOpenSavePanelDelegate.h"
#import "NSTextFieldDelegate.h"

@class NSString;

@interface XRGeneralPreferencesModule : XRPreferencesModule <NSOpenSavePanelDelegate, NSTextFieldDelegate>
{
}

- (void)resetDontAskMeWarnings:(id)arg1;
- (BOOL)isResizable;
- (id)imageForPreferenceNamed:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

