//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSArray, NSURL, XRImagePickerView;

@protocol XRImagePickerDelegate
- (void)imagePicker:(XRImagePickerView *)arg1 imageSelectedFromURL:(NSURL *)arg2;
- (void)imagePicker:(XRImagePickerView *)arg1 selectedImageAtIndex:(long long)arg2;
- (NSArray *)imagesForImagePicker:(XRImagePickerView *)arg1;
@end

