//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DTTimelineDecorator.h"

@interface XRInspectionHeadDecorator : DTTimelineDecorator
{
    unsigned long long _inspectionTime;
}

@property(nonatomic) unsigned long long inspectionTime; // @synthesize inspectionTime=_inspectionTime;
- (id)decorateContainer:(struct DTTimelineDecorationContainer *)arg1;
- (void)setDefaultsForPlane:(id)arg1;
- (id)init;

@end

