//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObjectController.h"

#import "NSTokenFieldDelegate.h"
#import "XRLazyKVOResponder.h"

@class NSString, NSTokenField, NSView, XRAnalysisCoreTableViewController, XRInstrumentDebuggerTokenFilterState, XRInstrumentDebuggerWindowController, XRLazyKVOAdapter;

@interface XRInstrumentDebuggerStoreDetailController : NSObjectController <XRLazyKVOResponder, NSTokenFieldDelegate>
{
    XRLazyKVOAdapter *_adapter;
    id _target;
    NSString *_keyPath;
    NSView *_tableViewHost;
    XRInstrumentDebuggerWindowController *_windowController;
    NSTokenField *_filterField;
    XRInstrumentDebuggerTokenFilterState *_filterState;
    XRAnalysisCoreTableViewController *_tableContentsViewController;
}

+ (void)initialize;
@property(retain, nonatomic) XRAnalysisCoreTableViewController *tableContentsViewController; // @synthesize tableContentsViewController=_tableContentsViewController;
@property __weak XRInstrumentDebuggerTokenFilterState *filterState; // @synthesize filterState=_filterState;
@property __weak NSTokenField *filterField; // @synthesize filterField=_filterField;
@property(nonatomic) __weak XRInstrumentDebuggerWindowController *windowController; // @synthesize windowController=_windowController;
@property __weak NSView *tableViewHost; // @synthesize tableViewHost=_tableViewHost;
- (void).cxx_destruct;
- (void)_setContentObject:(id)arg1;
- (void)handleLazyKVOUpdate:(id)arg1;
- (void)unbind:(id)arg1;
- (void)bind:(id)arg1 toObject:(id)arg2 withKeyPath:(id)arg3 options:(id)arg4;
- (void)_configureHost;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

