//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XRInstrumentControlState.h"

@interface XRInstrumentControlState (InstrumentsKit)
- (void)setHiddenColumnIdentifiers:(id)arg1;
- (id)hiddenColumnIdentifiers;
- (void)setColumnWidthsByColumnIdentifier:(id)arg1;
- (id)columnWidthsByColumnIdentifier;
- (BOOL)hasEngineeringTypeSortDescriptors;
- (void)setEngineeringTypeSortDescriptors:(id)arg1;
- (id)engineeringTypeSortDescriptors:(id)arg1;
@end

