//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

@class NSSet, XRInstrumentDebuggerOutputBoundary, XRInstrumentDebuggerRun, XRInstrumentDebuggerStore;

@interface XRInstrumentDebuggerTable : NSManagedObject
{
}

+ (id)fetchRequest;

// Remaining properties
@property(nonatomic) short access; // @dynamic access;
@property(retain, nonatomic) NSSet *references; // @dynamic references;
@property(retain, nonatomic) XRInstrumentDebuggerOutputBoundary *requiredBy; // @dynamic requiredBy;
@property(retain, nonatomic) XRInstrumentDebuggerRun *run; // @dynamic run;
@property(retain, nonatomic) XRInstrumentDebuggerStore *store; // @dynamic store;
@property(nonatomic) int tableID; // @dynamic tableID;

@end

