//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSManagedObjectContext, NSManagedObjectModel, NSPersistentStoreCoordinator, NSString, XRTrace;

@interface XRInstrumentDebuggerState : NSObject
{
    NSManagedObjectModel *_mom;
    NSPersistentStoreCoordinator *_psc;
    NSManagedObjectContext *_backgroundCtx;
    // Error parsing type: Ai, name: _nextGraphID
    XRTrace *_trace;
    NSString *_loggingType;
    NSManagedObjectContext *_managedObjectContext;
}

@property(readonly, nonatomic) NSManagedObjectContext *managedObjectContext; // @synthesize managedObjectContext=_managedObjectContext;
@property(retain, nonatomic) NSString *loggingType; // @synthesize loggingType=_loggingType;
- (void).cxx_destruct;
- (void)refreshInGroup:(id)arg1;
- (void)attachToTrace:(id)arg1 group:(id)arg2;
- (id)init;

@end

