//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsKit/XRInstrumentDebuggerGraphNode.h>

@class NSSet, NSString, XRAnalysisCoreTableSpec, XRInstrumentDebuggerRun;

@interface XRInstrumentDebuggerStore : XRInstrumentDebuggerGraphNode
{
}

+ (id)fetchRequest;

// Remaining properties
@property(nonatomic) long long rows; // @dynamic rows;
@property(retain, nonatomic) XRInstrumentDebuggerRun *run; // @dynamic run;
@property(copy, nonatomic) NSString *spec; // @dynamic spec;
@property(retain, nonatomic) XRAnalysisCoreTableSpec *specObject; // @dynamic specObject;
@property(copy, nonatomic) NSString *subpath; // @dynamic subpath;
@property(retain, nonatomic) NSSet *tables; // @dynamic tables;

@end

