//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsKit/XRInstrumentDebuggerGraphNode.h>

@class NSSet, NSString, XRInstrumentDebuggerRun;

@interface XRInstrumentDebuggerOutputBoundary : XRInstrumentDebuggerGraphNode
{
}

+ (id)fetchRequest;

// Remaining properties
@property(retain, nonatomic) XRInstrumentDebuggerRun *run; // @dynamic run;
@property(retain, nonatomic) NSSet *tables; // @dynamic tables;
@property(copy, nonatomic) NSString *uuid; // @dynamic uuid;

@end

