//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

@class NSSet, NSString, XRInstrumentDebuggerSchemataNode;

@interface XRInstrumentDebuggerSchema : NSManagedObject
{
}

+ (id)fetchRequest;

// Remaining properties
@property(retain, nonatomic) NSSet *columns; // @dynamic columns;
@property(copy, nonatomic) NSString *documentationURL; // @dynamic documentationURL;
@property(copy, nonatomic) NSString *name; // @dynamic name;
@property(copy, nonatomic) NSString *package; // @dynamic package;
@property(retain, nonatomic) XRInstrumentDebuggerSchemataNode *schemataNode; // @dynamic schemataNode;
@property(copy, nonatomic) NSString *topology; // @dynamic topology;

@end

