//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XRInstrument.h"

#import "XRTimelineRepresentedObject.h"

@class NSString;

@interface XRInstrument (XRTimelineRepresentedObject) <XRTimelineRepresentedObject>
- (id)_filterablesForRunListData:(id)arg1 runNumber:(long long)arg2;
- (BOOL)_planeShouldBeResizableForUIStrategy;
- (void)_createTrackForTopLevelItem:(id)arg1 uiStrategyController:(id)arg2 graph:(id)arg3 multipleBrushes:(BOOL)arg4 forEmbedding:(BOOL)arg5 inToolbar:(BOOL)arg6;
- (id)_topLevelItemForUIStrategy:(id)arg1 forEmbedding:(BOOL)arg2;
- (id)_topLevelItemForUIStrategy:(id)arg1 forEmbedding:(BOOL)arg2 instance:(unsigned int)arg3;
- (id)_keyForUIStrategy;
- (id)_UISerializationString;
- (int)_strategyUIType;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

