//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsKit/XRInstrumentDebuggerGraphNode.h>

@class NSOrderedSet, NSSet, NSString, XRInstrumentDebuggerEngineContext, XRInstrumentDebuggerRun;

@interface XRInstrumentDebuggerEngine : XRInstrumentDebuggerGraphNode
{
}

+ (id)fetchRequest;

// Remaining properties
@property(retain, nonatomic) NSOrderedSet *console; // @dynamic console;
@property(copy, nonatomic) NSString *contentMode; // @dynamic contentMode;
@property(retain, nonatomic) NSSet *contexts; // @dynamic contexts;
@property(retain, nonatomic) XRInstrumentDebuggerEngineContext *currentContext; // @dynamic currentContext;
@property(retain, nonatomic) NSOrderedSet *factDump; // @dynamic factDump;
@property(copy, nonatomic) NSString *loggingType; // @dynamic loggingType;
@property(retain, nonatomic) XRInstrumentDebuggerRun *run; // @dynamic run;

@end

