//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDocument.h"

@class NSString, NSURL, WebView, XRPackage;

@interface XRInstrumentDistributionDocument : NSDocument
{
    NSURL *_privateUnpackedInstrDst;
    BOOL _canInstall;
    NSString *_reasonWhyInstallIsDisabled;
    XRPackage *_package;
    WebView *_packageDescriptionView;
}

@property __weak WebView *packageDescriptionView; // @synthesize packageDescriptionView=_packageDescriptionView;
@property(readonly, nonatomic) XRPackage *package; // @synthesize package=_package;
@property(retain) NSString *reasonWhyInstallIsDisabled; // @synthesize reasonWhyInstallIsDisabled=_reasonWhyInstallIsDisabled;
@property BOOL canInstall; // @synthesize canInstall=_canInstall;
- (void).cxx_destruct;
- (void)windowControllerDidLoadNib:(id)arg1;
- (BOOL)readFromFileWrapper:(id)arg1 ofType:(id)arg2 error:(id *)arg3;
- (void)installButtonPressed:(id)arg1;
- (void)cancelButtonPressed:(id)arg1;
- (void)close;
- (id)fileWrapperOfType:(id)arg1 error:(id *)arg2;
- (id)windowNibName;

@end

