//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSButton, NSPopoverTouchBarItem, NSString, PFTWindowController;

@interface XRInstrumentListPopoverController : NSObject
{
    NSPopoverTouchBarItem *_popoverItem;
    NSString *_identifier;
    PFTWindowController *_windowController;
    id <NSTouchBarDelegate> _touchBarDelegate;
    NSButton *_popoverButton;
}

@property(readonly, nonatomic) NSButton *popoverButton; // @synthesize popoverButton=_popoverButton;
@property(readonly, nonatomic) __weak id <NSTouchBarDelegate> touchBarDelegate; // @synthesize touchBarDelegate=_touchBarDelegate;
@property(readonly, nonatomic) __weak PFTWindowController *windowController; // @synthesize windowController=_windowController;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(readonly, nonatomic) NSPopoverTouchBarItem *popoverItem; // @synthesize popoverItem=_popoverItem;
- (void).cxx_destruct;
- (void)_updatePopoverButton;
- (id)initWithWindowController:(id)arg1 identifier:(id)arg2 touchBarDelegate:(id)arg3;

@end

