//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObjectController.h"

#import "DTObjectGridGraphDataSource.h"
#import "DTObjectGridGraphDelegate.h"
#import "XRLazyKVOResponder.h"

@class DTObjectGridGraph, NSString, XRInstrumentDebuggerGraphNode, XRLazyKVOAdapter;

@interface XRInstrumentDebuggerGraphController : NSObjectController <XRLazyKVOResponder, DTObjectGridGraphDataSource, DTObjectGridGraphDelegate>
{
    XRLazyKVOAdapter *_adapter;
    id _target;
    NSString *_keyPath;
    id _displayedContent;
    DTObjectGridGraph *_graph;
    XRInstrumentDebuggerGraphNode *_selectedNode;
}

+ (void)initialize;
@property(retain, nonatomic) XRInstrumentDebuggerGraphNode *selectedNode; // @synthesize selectedNode=_selectedNode;
@property(retain, nonatomic) DTObjectGridGraph *graph; // @synthesize graph=_graph;
- (void).cxx_destruct;
- (id)_edgeForIdentifier:(unsigned int)arg1;
- (id)_nodeForIdentifier:(unsigned int)arg1;
- (void)objectGridGraph:(id)arg1 didClickNode:(id)arg2;
- (void)objectGridGraph:(id)arg1 willDisplayReference:(id)arg2;
- (void)objectGridGraph:(id)arg1 willDisplayNode:(id)arg2;
- (void)enumerateIncomingReferencesForNode:(unsigned int)arg1 withBlock:(CDUnknownBlockType)arg2;
- (void)enumerateOutgoingReferencesForNode:(unsigned int)arg1 withBlock:(CDUnknownBlockType)arg2;
- (void)_setContentObject:(id)arg1;
- (void)handleLazyKVOUpdate:(id)arg1;
- (void)unbind:(id)arg1;
- (void)bind:(id)arg1 toObject:(id)arg2 withKeyPath:(id)arg3 options:(id)arg4;
- (void)_graphWasAssigned;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)initWithContent:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

