//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsKit/XRInstrumentDebuggerEngine.h>

@class NSString;

@interface XRInstrumentDebuggerModeler : XRInstrumentDebuggerEngine
{
}

+ (id)fetchRequest;

// Remaining properties
@property(copy, nonatomic) NSString *debugString; // @dynamic debugString;
@property(copy, nonatomic) NSString *modelerClassName; // @dynamic modelerClassName;
@property(nonatomic) short stage; // @dynamic stage;
@property(copy, nonatomic) NSString *uuid; // @dynamic uuid;

@end

