//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

@class NSAttributedString, XRInstrumentDebuggerEngine;

@interface XRInstrumentDebuggerTextBlock : NSManagedObject
{
}

+ (id)fetchRequest;

// Remaining properties
@property(retain, nonatomic) XRInstrumentDebuggerEngine *consoleOwner; // @dynamic consoleOwner;
@property(retain, nonatomic) NSAttributedString *content; // @dynamic content;
@property(retain, nonatomic) XRInstrumentDebuggerEngine *factOwner; // @dynamic factOwner;

@end

