//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

@class NSSet, NSString, XRInstrumentDebuggerCore;

@interface XRInstrumentDebuggerRun : NSManagedObject
{
}

+ (id)fetchRequest;

// Remaining properties
@property(retain, nonatomic) XRInstrumentDebuggerCore *core; // @dynamic core;
@property(retain, nonatomic) NSSet *modelers; // @dynamic modelers;
@property(copy, nonatomic) NSString *name; // @dynamic name;
@property(nonatomic) long long number; // @dynamic number;
@property(retain, nonatomic) NSSet *outputBoundaries; // @dynamic outputBoundaries;
@property(retain, nonatomic) NSSet *stores; // @dynamic stores;
@property(retain, nonatomic) NSSet *tables; // @dynamic tables;

@end

