//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsKit/XRInstrumentDebuggerGraphNode.h>

@class XRInstrumentDebuggerBindingEngine, XRInstrumentDebuggerRun, XRInstrumentDebuggerSchemataNode;

@interface XRInstrumentDebuggerCore : XRInstrumentDebuggerGraphNode
{
}

+ (id)fetchRequest;

// Remaining properties
@property(retain, nonatomic) XRInstrumentDebuggerBindingEngine *bindingEngine; // @dynamic bindingEngine;
@property(retain, nonatomic) XRInstrumentDebuggerRun *run; // @dynamic run;
@property(retain, nonatomic) XRInstrumentDebuggerSchemataNode *schemataNode; // @dynamic schemataNode;

@end

