//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

#import "NSOutlineViewDelegate.h"
#import "NSTableViewDataSource.h"
#import "NSTableViewDelegate.h"
#import "NSTextViewDelegate.h"
#import "NSWindowDelegate.h"
#import "XRLazyKVOResponder.h"

@class NSArray, NSArrayController, NSIndexSet, NSObject<OS_dispatch_group>, NSString, NSTabView, NSTableView, NSTreeController, NSView, NSWindow, PFTTraceDocument, WKWebView, XRAnalysisCore, XRInstrumentDebuggerEngineDetailController, XRInstrumentDebuggerGraphController, XRInstrumentDebuggerState, XRInstrumentDebuggerStoreDetailController, XRIssueDiagnosticViewController, XRLazyKVOAdapter;

@interface XRInstrumentDebuggerWindowController : NSWindowController <XRLazyKVOResponder, NSOutlineViewDelegate, NSTextViewDelegate, NSTableViewDataSource, NSTableViewDelegate, NSWindowDelegate>
{
    XRLazyKVOAdapter *_kvoAdapter;
    NSObject<OS_dispatch_group> *_currentUpdateGroup;
    BOOL _fetching;
    XRIssueDiagnosticViewController *_errorViewController;
    XRInstrumentDebuggerStoreDetailController *_storeDetailController;
    NSView *_graphPane;
    NSArrayController *_storesArrayController;
    XRInstrumentDebuggerGraphController *_graphController;
    NSArrayController *_modelersArrayController;
    XRInstrumentDebuggerState *_state;
    long long _selectedNavigatorTabIdx;
    NSTabView *_detailTabView;
    XRInstrumentDebuggerEngineDetailController *_engineDetailController;
    NSArrayController *_availableRunsController;
    NSTreeController *_othersTreeController;
    NSWindow *_breachStatusSheet;
    WKWebView *_schemaWebView;
    NSArrayController *_schemataController;
    NSTableView *_storesTableView;
    XRAnalysisCore *_coreBeingRecovered;
    NSIndexSet *_schemaSelectionIndexes;
    NSArray *_storesArraySortDescriptors;
    NSArray *_modelersArraySortDescriptors;
}

@property(copy) NSArray *modelersArraySortDescriptors; // @synthesize modelersArraySortDescriptors=_modelersArraySortDescriptors;
@property(copy) NSArray *storesArraySortDescriptors; // @synthesize storesArraySortDescriptors=_storesArraySortDescriptors;
@property(copy, nonatomic) NSIndexSet *schemaSelectionIndexes; // @synthesize schemaSelectionIndexes=_schemaSelectionIndexes;
@property __weak XRAnalysisCore *coreBeingRecovered; // @synthesize coreBeingRecovered=_coreBeingRecovered;
@property __weak NSTableView *storesTableView; // @synthesize storesTableView=_storesTableView;
@property(retain) NSArrayController *schemataController; // @synthesize schemataController=_schemataController;
@property __weak WKWebView *schemaWebView; // @synthesize schemaWebView=_schemaWebView;
@property(retain) NSWindow *breachStatusSheet; // @synthesize breachStatusSheet=_breachStatusSheet;
@property(retain) NSTreeController *othersTreeController; // @synthesize othersTreeController=_othersTreeController;
@property(retain) NSArrayController *availableRunsController; // @synthesize availableRunsController=_availableRunsController;
@property(retain) XRInstrumentDebuggerEngineDetailController *engineDetailController; // @synthesize engineDetailController=_engineDetailController;
@property __weak NSTabView *detailTabView; // @synthesize detailTabView=_detailTabView;
@property long long selectedNavigatorTabIdx; // @synthesize selectedNavigatorTabIdx=_selectedNavigatorTabIdx;
@property(retain) XRInstrumentDebuggerState *state; // @synthesize state=_state;
@property(retain) NSArrayController *modelersArrayController; // @synthesize modelersArrayController=_modelersArrayController;
@property(retain) XRInstrumentDebuggerGraphController *graphController; // @synthesize graphController=_graphController;
@property(retain) NSArrayController *storesArrayController; // @synthesize storesArrayController=_storesArrayController;
@property __weak NSView *graphPane; // @synthesize graphPane=_graphPane;
@property(retain) XRInstrumentDebuggerStoreDetailController *storeDetailController; // @synthesize storeDetailController=_storeDetailController;
@property(retain) XRIssueDiagnosticViewController *errorViewController; // @synthesize errorViewController=_errorViewController;
@property(nonatomic, getter=isFetching) BOOL fetching; // @synthesize fetching=_fetching;
- (void).cxx_destruct;
- (void)validateAnalysisCore:(id)arg1;
- (void)instanceModelers:(id)arg1;
- (void)runBindingSolver:(id)arg1;
- (BOOL)respondsToSelector:(SEL)arg1;
- (void)breachCancelled:(id)arg1;
- (void)breachAuthorized:(id)arg1;
- (void)refresh:(id)arg1;
@property(readonly) PFTTraceDocument *traceDocument;
- (BOOL)shouldCloseDocument;
- (id)windowFrameAutosaveName;
- (id)windowTitleForDocumentDisplayName:(id)arg1;
- (void)setDocument:(id)arg1;
- (void)handleLazyKVOUpdate:(id)arg1;
- (void)showHelp:(id)arg1;
- (void)copyAsRequiredInputElement:(id)arg1;
- (void)copyAsCreateTableElement:(id)arg1;
- (void)_eventHorizonMoved:(id)arg1;
- (void)dealloc;
- (void)windowWillClose:(id)arg1;
- (void)_stateObjectDidInitialize:(id)arg1;
- (void)windowDidLoad;
- (void)coreBreachRequested:(id)arg1;
- (void)panicStopIssued:(id)arg1;
- (void)_forceFullFetch;
- (id)initWithWindow:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

