//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsKit/XRTouchBarItemViewController.h>

#import "XRLazyKVOResponder.h"

@class NSScrollView, NSStackView, NSString, XRLazyKVOAdapter;

@interface XRInstrumentListItemViewController : XRTouchBarItemViewController <XRLazyKVOResponder>
{
    NSScrollView *_scrollView;
    NSStackView *_stackView;
    XRLazyKVOAdapter *_observationAdapter;
}

@property(readonly, nonatomic) XRLazyKVOAdapter *observationAdapter; // @synthesize observationAdapter=_observationAdapter;
@property(retain, nonatomic) NSStackView *stackView; // @synthesize stackView=_stackView;
@property(retain, nonatomic) NSScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void).cxx_destruct;
- (void)_selectInstrument:(id)arg1;
- (void)_updateInstrumentList;
- (id)_buildView;
- (void)handleLazyKVOUpdate:(id)arg1;
- (void)viewDidDisappear;
- (void)viewDidAppear;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

