//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

@class NSString, XRInstrumentDebuggerSchema;

@interface XRInstrumentDebuggerSchemaColumn : NSManagedObject
{
}

+ (id)fetchRequest;

// Remaining properties
@property(copy, nonatomic) NSString *etype; // @dynamic etype;
@property(copy, nonatomic) NSString *impl; // @dynamic impl;
@property(copy, nonatomic) NSString *mnemonic; // @dynamic mnemonic;
@property(copy, nonatomic) NSString *name; // @dynamic name;
@property(retain, nonatomic) XRInstrumentDebuggerSchema *schema; // @dynamic schema;
@property(copy, nonatomic) NSString *topologyField; // @dynamic topologyField;

@end

