//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface XRIssueMOck : NSObject
{
    unsigned long long _relativeTimestamp;
}

- (void)setRelativeTimestamp:(unsigned long long)arg1;
- (unsigned long long)relativeTimestamp;

@end

