//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@interface XRIssueDiagnosticViewController : NSViewController
{
}

- (void)_reloadView;
- (void)viewWillAppear;
- (void)setRepresentedObject:(id)arg1;
- (id)nibBundle;
- (id)webView;
- (void)viewDidLoad;

@end

