//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DVTLibraryController.h"

@interface XRLibraryViewController : DVTLibraryController
{
}

- (void)_syncAsset:(id)arg1 withInstrumentType:(id)arg2;
- (id)_createLibraryAssetForInstrumentType:(id)arg1;
- (void)_addInstrumentType:(id)arg1;
- (void)_removeInstrumentType:(id)arg1;
- (void)_populateLibrary;
- (BOOL)removeAssets:(id)arg1 error:(id *)arg2;
- (BOOL)canRemoveAsset:(id)arg1;
- (void)instrumentRemoved:(id)arg1;
- (void)instrumentAdded:(id)arg1;
- (id)searchStringsForAsset:(id)arg1;
- (BOOL)delegateFirstResponder;
- (void)libraryTileView:(id)arg1 wasDoubleClicked:(id)arg2;
- (BOOL)canOpenDetailPopUp;
- (BOOL)depositAssets:(id)arg1;
- (void)populatePasteboard:(id)arg1 withAssets:(id)arg2;
- (void)libraryDidLoad;
- (void)dealloc;

@end

