//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XRInstrumentControlState.h"

@class NSString;

@interface XRMainWindowUserInterfaceControlMode : XRInstrumentControlState
{
}

@property(readonly, nonatomic, getter=isLowerDisplayHidden) BOOL lowerDisplayHidden;
@property(readonly, nonatomic, getter=isExtendedDetailInspectorHidden) BOOL extendedDetailInspectorHidden;
@property(nonatomic) int currentLayout;
@property(retain, nonatomic) NSString *selectedStrategyIdentifier;
- (void)initializeDefaultState;

@end

