//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "XRTabViewControllerAnimationControlDelegate.h"

@class NSMutableDictionary, NSProgress, NSString, XRTabViewControllerWithDelegate;

@interface XRModalViewController : NSViewController <XRTabViewControllerAnimationControlDelegate>
{
    XRTabViewControllerWithDelegate *_subviewController;
    NSString *_currentMode;
    NSProgress *_displayedProgress;
    NSMutableDictionary *_itemsByMode;
    BOOL _animating;
}

+ (BOOL)_animateTransitions;
- (void).cxx_destruct;
- (void)_subviewBecameInteractive:(id)arg1;
- (void)_subviewBecameBusy:(id)arg1;
- (void)setViewController:(id)arg1 mode:(id)arg2;
- (void)setMode:(id)arg1 progress:(id)arg2;
- (void)_throttledSwitchToMode:(id)arg1;
- (BOOL)_hasController:(id)arg1;
- (void)tabViewControllerFinishedAnimating:(id)arg1;
- (void)tabViewControllerStartedAnimating:(id)arg1;
- (void)updateViewConstraints;
- (void)loadView;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

