//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSPreferences.h"

@interface XRPreferences : NSPreferences
{
}

+ (void)restoreWindowWithIdentifier:(id)arg1 state:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
+ (void)initialize;
- (BOOL)windowShouldClose:(id)arg1;
- (void)applicationWillTerminate:(id)arg1;
- (BOOL)usesButtons;
- (void)dealloc;
- (id)init;

@end

