//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsKit/XRToolbarItem.h>

#import "DVTDelayedMenuButtonDelegate.h"

@class NSString, XRRecordStopToolbarButton;

@interface XRRecordStopToolbarItem : XRToolbarItem <DVTDelayedMenuButtonDelegate>
{
    XRRecordStopToolbarButton *_button;
    int _state;
}

- (void).cxx_destruct;
- (id)delayedMenuButton:(id)arg1 willSetCurrentMenuItem:(id)arg2;
- (void)disconnectFromContext;
- (void)connectToContext:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)_updateWithNewState:(int)arg1;
- (void)refresh;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

