//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsKit/XRTouchBarItemViewController.h>

#import "XRLazyKVOResponder.h"

@class NSString, XRLazyKVOAdapter;

@interface XRRecordPauseItemViewController : XRTouchBarItemViewController <XRLazyKVOResponder>
{
    XRLazyKVOAdapter *_observationAdapter;
}

+ (id)_redFunctionRowAppearance;
+ (id)_functionRowAppearance;
+ (id)_stopButtonImage;
@property(readonly, nonatomic) XRLazyKVOAdapter *observationAdapter; // @synthesize observationAdapter=_observationAdapter;
- (void).cxx_destruct;
- (void)_toggleRecording:(id)arg1;
- (id)_recordButton;
- (id)_buildRecordButton;
- (id)_recordButtonImage;
- (void)handleLazyKVOUpdate:(id)arg1;
- (void)viewDidDisappear;
- (void)viewDidAppear;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

