//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DVTDelayedMenuButton.h"

@class NSImage, NSMenu, NSMenuItem, XRRecordingButtonImages, XRToolbarItem;

@interface XRRecordStopToolbarButton : DVTDelayedMenuButton
{
    NSMenu *_recordMenu;
    XRToolbarItem *_toolbarItem;
    XRRecordingButtonImages *_recordImmediateMode;
    XRRecordingButtonImages *_recordDeferredMode;
    XRRecordingButtonImages *_recordWindowedMode;
    NSImage *_stopImage;
    NSImage *_stopImageNonMain;
    BOOL _showMenu;
    BOOL _useStopImage;
    BOOL _enableRecord;
    BOOL _enableConfigure;
    BOOL _disableMainImage;
    NSMenuItem *_recordMenuItem;
    NSMenuItem *_recordingOptionsMenuItem;
}

@property(readonly, nonatomic) NSMenuItem *recordingOptionsMenuItem; // @synthesize recordingOptionsMenuItem=_recordingOptionsMenuItem;
@property(readonly, nonatomic) NSMenuItem *recordMenuItem; // @synthesize recordMenuItem=_recordMenuItem;
@property(readonly, nonatomic) NSMenu *recordMenu; // @synthesize recordMenu=_recordMenu;
@property(nonatomic) BOOL disableMainImage; // @synthesize disableMainImage=_disableMainImage;
@property(nonatomic) BOOL enableConfigure; // @synthesize enableConfigure=_enableConfigure;
@property(nonatomic) BOOL enableRecord; // @synthesize enableRecord=_enableRecord;
@property(nonatomic) BOOL useStopImage; // @synthesize useStopImage=_useStopImage;
@property(nonatomic) BOOL showMenu; // @synthesize showMenu=_showMenu;
- (void).cxx_destruct;
- (void)performRecordAction:(id)arg1;
- (void)performRecordingOptionsAction:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (void)setToolbarItem:(id)arg1;
- (id)_toolbarItem;
- (void)_setButtonStyle;
- (id)_recordingButtonImagesForMode:(unsigned long long)arg1;
- (unsigned long long)_currentRecordingMode;
- (void)_createImages;
- (id)addRecordButtonToMenu:(id)arg1;
- (id)addRecordingOptionsButtonToMenu:(id)arg1;
- (id)_newToolbarViewHitTest:(struct CGPoint)arg1;
- (void)_swizzleToolbarViewHitTest;
- (id)init;

@end

