//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSImage;

@interface XRRecordingButtonImages : NSObject
{
    NSImage *_baseImage;
    NSImage *_nonMainImage;
    NSImage *_disabledImage;
    NSImage *_disabledNonMainImage;
}

@property(readonly, nonatomic) NSImage *disabledNonMainImage; // @synthesize disabledNonMainImage=_disabledNonMainImage;
@property(readonly, nonatomic) NSImage *disabledImage; // @synthesize disabledImage=_disabledImage;
@property(readonly, nonatomic) NSImage *nonMainImage; // @synthesize nonMainImage=_nonMainImage;
@property(readonly, nonatomic) NSImage *baseImage; // @synthesize baseImage=_baseImage;
- (void).cxx_destruct;
- (id)initWithImage:(id)arg1;

@end

