//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "NSPathControlDelegate.h"
#import "XRDeviceObserver.h"

@class NSButton, NSImageView, NSMenu, NSMutableArray, NSPopUpButton, NSScrollView, NSString, NSTextField, NSView, PFTDataElementList, PFTDataView, PFTTraceDocument, SemiFakePopUpButton, XRRecordingOptions, XRTargetChooserPathControl, XRTrace;

@interface XRRecordingOptionsViewController : NSViewController <XRDeviceObserver, NSPathControlDelegate>
{
    XRTrace *_trace;
    int _state;
    BOOL _calculateTimeUnits;
    unsigned long long _maxHoursToRecord;
    PFTTraceDocument *_itemContext;
    BOOL _currentlyShowingNoInstrumentText;
    BOOL _observing;
    NSMutableArray *_configurableInstruments;
    NSMenu *_configurableInstrumentsMenu;
    PFTDataElementList *_instrumentDataElements;
    XRTargetChooserPathControl *_targetChooser;
    NSView *_globalRecordingOptionsView;
    NSButton *_discloseGlobalRecordingOptions;
    NSTextField *_globalRecordingOptionsSummary;
    NSTextField *_globalRecordingOptionsLabel;
    NSTextField *_timeLimitTextField;
    NSPopUpButton *_timeLimitPopup;
    NSButton *_recordingModeImmediate;
    NSButton *_recordingModeDeferred;
    NSButton *_recordingModeWindowed;
    NSTextField *_windowLimitTextField;
    NSTextField *_windowLimitLabel;
    NSButton *_doneButton;
    NSButton *_recordButton;
    XRRecordingOptions *_recordingOptions;
    NSView *_instrumentOptionContainer;
    NSTextField *_warningTextView;
    NSImageView *_warningImage;
    NSTextField *_noInstrumentsText;
    NSView *_instrumentRecordingOptions;
    SemiFakePopUpButton *_instrumentListButton;
    NSScrollView *_instrumentsSettingsScrollView;
    PFTDataView *_instrumentSettingsView;
}

@property __weak PFTDataView *instrumentSettingsView; // @synthesize instrumentSettingsView=_instrumentSettingsView;
@property __weak NSScrollView *instrumentsSettingsScrollView; // @synthesize instrumentsSettingsScrollView=_instrumentsSettingsScrollView;
@property __weak SemiFakePopUpButton *instrumentListButton; // @synthesize instrumentListButton=_instrumentListButton;
@property(retain) NSView *instrumentRecordingOptions; // @synthesize instrumentRecordingOptions=_instrumentRecordingOptions;
@property(retain) NSTextField *noInstrumentsText; // @synthesize noInstrumentsText=_noInstrumentsText;
@property __weak NSImageView *warningImage; // @synthesize warningImage=_warningImage;
@property __weak NSTextField *warningTextView; // @synthesize warningTextView=_warningTextView;
@property __weak NSView *instrumentOptionContainer; // @synthesize instrumentOptionContainer=_instrumentOptionContainer;
@property(retain, nonatomic) XRRecordingOptions *recordingOptions; // @synthesize recordingOptions=_recordingOptions;
@property __weak NSButton *recordButton; // @synthesize recordButton=_recordButton;
@property __weak NSButton *doneButton; // @synthesize doneButton=_doneButton;
@property __weak NSTextField *windowLimitLabel; // @synthesize windowLimitLabel=_windowLimitLabel;
@property __weak NSTextField *windowLimitTextField; // @synthesize windowLimitTextField=_windowLimitTextField;
@property __weak NSButton *recordingModeWindowed; // @synthesize recordingModeWindowed=_recordingModeWindowed;
@property __weak NSButton *recordingModeDeferred; // @synthesize recordingModeDeferred=_recordingModeDeferred;
@property __weak NSButton *recordingModeImmediate; // @synthesize recordingModeImmediate=_recordingModeImmediate;
@property __weak NSPopUpButton *timeLimitPopup; // @synthesize timeLimitPopup=_timeLimitPopup;
@property __weak NSTextField *timeLimitTextField; // @synthesize timeLimitTextField=_timeLimitTextField;
@property __weak NSTextField *globalRecordingOptionsLabel; // @synthesize globalRecordingOptionsLabel=_globalRecordingOptionsLabel;
@property __weak NSTextField *globalRecordingOptionsSummary; // @synthesize globalRecordingOptionsSummary=_globalRecordingOptionsSummary;
@property __weak NSButton *discloseGlobalRecordingOptions; // @synthesize discloseGlobalRecordingOptions=_discloseGlobalRecordingOptions;
@property(retain) NSView *globalRecordingOptionsView; // @synthesize globalRecordingOptionsView=_globalRecordingOptionsView;
@property __weak XRTargetChooserPathControl *targetChooser; // @synthesize targetChooser=_targetChooser;
- (void).cxx_destruct;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)_updateRecordButtonState;
- (void)handleDeviceNotification:(id)arg1;
- (void)_dismissWithReturnCode:(long long)arg1;
- (void)disconnectObservers;
- (void)ok:(id)arg1;
- (void)record:(id)arg1;
- (void)_prepareToExit;
- (void)globalRecordingOptionsClicked:(id)arg1;
- (void)_resizeWindowToRect:(struct CGRect)arg1;
- (void)recordingModeChanged:(id)arg1;
- (void)windowLimitChanged:(id)arg1;
- (void)timeLimitUnitsChanged:(id)arg1;
- (void)timeLimitChanged:(id)arg1;
- (void)_computeGlobalRecordOptionsSummaryString;
- (void)_updateUIControls;
- (void)instrumentSelected:(id)arg1;
- (void)_reconfigurePathControl;
- (void)_setupPathControl;
- (void)_selectInstrumentConfigurationView;
- (void)_makeInstrumentConfigurationViewVisible;
- (void)_makeNoInstrumentsViewVisible;
- (void)_updateConfigurableInstrumentsList;
- (void)viewWillAppear;
- (id)initWithTrace:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

