//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

#import "XRFilteredDataSource.h"

@class NSString, XRRunIssuesViewController;

@interface XRRunIssuesMainView : NSView <XRFilteredDataSource>
{
    XRRunIssuesViewController *_viewController;
}

@property(nonatomic) __weak XRRunIssuesViewController *viewController; // @synthesize viewController=_viewController;
- (void).cxx_destruct;
- (id)selectedSearchContext;
- (id)searchContexts;
- (void)filterDetailWithTokens:(id)arg1 context:(id)arg2 matchesAny:(BOOL)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

