//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "NSOutlineViewDataSource.h"
#import "NSOutlineViewDelegate.h"
#import "XRFilteredDataSource.h"

@class DTNanoTimestampFormatter, NSArray, NSOutlineView, NSPredicate, NSString, NSTableColumn, XRTrace;

@interface XRRunIssuesViewController : NSViewController <NSOutlineViewDelegate, NSOutlineViewDataSource, XRFilteredDataSource>
{
    unsigned long long _lastSeenInspectionTime;
    struct XRTimeRange _lastSeenFilterRange;
    NSPredicate *_timeFilterPredicate;
    NSPredicate *_userFilterPredicate;
    NSPredicate *_nilParentPredicate;
    NSArray *_recordingIssueSortDescriptors;
    DTNanoTimestampFormatter *_timestampFormatter;
    NSString *_selectedSearchContext;
    XRTrace *_trace;
    NSOutlineView *_issuesOutline;
    NSTableColumn *_imageColumn;
    NSTableColumn *_timestampColumn;
    NSTableColumn *_messageColumn;
}

@property(retain, nonatomic) NSTableColumn *messageColumn; // @synthesize messageColumn=_messageColumn;
@property(retain, nonatomic) NSTableColumn *timestampColumn; // @synthesize timestampColumn=_timestampColumn;
@property(retain, nonatomic) NSTableColumn *imageColumn; // @synthesize imageColumn=_imageColumn;
@property(retain, nonatomic) DTNanoTimestampFormatter *timestampFormatter; // @synthesize timestampFormatter=_timestampFormatter;
@property(retain, nonatomic) NSOutlineView *issuesOutline; // @synthesize issuesOutline=_issuesOutline;
@property(nonatomic) __weak XRTrace *trace; // @synthesize trace=_trace;
- (void).cxx_destruct;
- (id)selectedSearchContext;
- (id)searchContexts;
- (void)filterDetailWithTokens:(id)arg1 context:(id)arg2 matchesAny:(BOOL)arg3;
- (id)outlineView:(id)arg1 viewForTableColumn:(id)arg2 item:(id)arg3;
- (BOOL)outlineView:(id)arg1 shouldEditTableColumn:(id)arg2 item:(id)arg3;
- (void)outlineViewSelectionDidChange:(id)arg1;
- (BOOL)outlineView:(id)arg1 shouldExpandItem:(id)arg2;
- (void)outlineView:(id)arg1 sortDescriptorsDidChange:(id)arg2;
- (id)outlineView:(id)arg1 objectValueForTableColumn:(id)arg2 byItem:(id)arg3;
- (long long)outlineView:(id)arg1 numberOfChildrenOfItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 isItemExpandable:(id)arg2;
- (id)outlineView:(id)arg1 child:(long long)arg2 ofItem:(id)arg3;
- (void)copy:(id)arg1;
- (unsigned long long)_getRootObjectsCount;
- (id)_getRootObjectsSort:(BOOL)arg1;
- (id)_getSearchPredicate;
- (id)_getObjectsForPredicate:(id)arg1 sort:(BOOL)arg2;
- (id)_fetchRequestForPredicate:(id)arg1 sort:(BOOL)arg2;
- (void)_selectRowNearestToTime:(unsigned long long)arg1;
- (void)didSetInspectionTime:(unsigned long long)arg1;
- (void)didChangeUpdateFilter;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)_mocChanged:(id)arg1;
- (void)invalidate;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

