//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsKit/XRTouchBarItemViewController.h>

#import "XRLazyKVOResponder.h"

@class NSString, XRLazyKVOAdapter;

@interface XRSnapToFitItemViewController : XRTouchBarItemViewController <XRLazyKVOResponder>
{
    XRLazyKVOAdapter *_observationAdapter;
    struct XRSnapToFitUndoInfo _undoInfo;
}

@property(nonatomic) struct XRSnapToFitUndoInfo undoInfo; // @synthesize undoInfo=_undoInfo;
@property(readonly, nonatomic) XRLazyKVOAdapter *observationAdapter; // @synthesize observationAdapter=_observationAdapter;
- (void).cxx_destruct;
- (void)_resetUndoInfo;
- (void)_snapToFit:(id)arg1;
- (id)_snapToFitButton;
- (id)_buildSnapToFitButton;
- (void)_updateButtonAndUndoState;
- (void)handleLazyKVOUpdate:(id)arg1;
- (void)viewDidDisappear;
- (void)viewDidAppear;
- (void)loadView;
- (id)initWithWindowController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

