//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DVTMessageBubbleAnnotation.h"

@class NSArray;

@interface XRSourceCommentAnnotation : DVTMessageBubbleAnnotation
{
    NSArray *_dataElements;
}

@property(retain) NSArray *dataElements; // @synthesize dataElements=_dataElements;
- (void).cxx_destruct;
- (double)preferredWidthForAvailableWidth:(double)arg1;

@end

