//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DVTAnnotationProvider.h"

#import "DVTMessageBubbleAnnotationDelegate.h"
#import "XRCommentObserver.h"
#import "XRInspectorSource.h"

@class NSString, XRSourceCommentAnnotation, XRTextView;

@interface XRSourceCommentAnnotationProvider : DVTAnnotationProvider <DVTMessageBubbleAnnotationDelegate, XRCommentObserver, XRInspectorSource>
{
    XRSourceCommentAnnotation *_selectedAnnotation;
    XRTextView *_textView;
}

+ (id)annotationProviderForContext:(id)arg1 error:(id *)arg2;
- (void).cxx_destruct;
- (id)documentUUID;
- (id)dataElementsForInspector:(id)arg1;
- (void)inspectorDismissed:(id)arg1;
- (void)didClickMessageBubbleForAnnotation:(id)arg1 onIcon:(BOOL)arg2 inTextView:(id)arg3 event:(id)arg4;
- (struct CGRect)_locationOfAnnotation:(id)arg1 inTextView:(id)arg2;
- (void)_createAnnotationAtLine:(unsigned long long)arg1 withCommentList:(id)arg2 displayType:(int)arg3;
- (id)_themeForComments:(id)arg1;
- (id)_descriptionForComments:(id)arg1 displayType:(int)arg2;
- (BOOL)_isOnlyMarker:(id)arg1;
- (void)commentsWereUpdated:(id)arg1 displayType:(int)arg2;
- (id)initWithContext:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

