//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DVTAnnotationContext.h"

@class XRTextView;

@interface XRSourceCommentAnnotationContext : DVTAnnotationContext
{
    XRTextView *_textView;
}

@property(retain, nonatomic) XRTextView *textView; // @synthesize textView=_textView;
- (void).cxx_destruct;
- (id)initWithTextView:(id)arg1;

@end

