//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XRInstrumentControlState.h"

@class XR_CSKFilterGroup;

@interface XRStrategyUIControllerMode : XRInstrumentControlState
{
    XR_CSKFilterGroup *_cachedTrackFilterGroup;
}

- (void).cxx_destruct;
@property(retain, nonatomic) XR_CSKFilterGroup *trackFilterGroup;

@end

