//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "XR_CSKTokenFieldControllerDelegate.h"

@class NSArray, NSMutableArray, NSStackView, NSString, NSView, PFTTraceDocument, XRStrategyUIController, XR_CSKTokenField, XR_CSKTokenFieldController;

@interface XRStrategiesToolbarViewController : NSViewController <XR_CSKTokenFieldControllerDelegate>
{
    XRStrategyUIController *_currentUIController;
    NSMutableArray *_scopeButtons;
    PFTTraceDocument *_currentDocument;
    XR_CSKTokenFieldController *_tokenFieldController;
    NSArray *_availableStrategyUIControllers;
    NSStackView *_stackView;
    XR_CSKTokenField *_tokenField;
    NSView *_separatorView;
}

@property(retain, nonatomic) NSView *separatorView; // @synthesize separatorView=_separatorView;
@property(nonatomic) __weak XR_CSKTokenField *tokenField; // @synthesize tokenField=_tokenField;
@property(nonatomic) __weak NSStackView *stackView; // @synthesize stackView=_stackView;
@property(retain, nonatomic) NSArray *availableStrategyUIControllers; // @synthesize availableStrategyUIControllers=_availableStrategyUIControllers;
@property(retain, nonatomic) XRStrategyUIController *currentUIController; // @synthesize currentUIController=_currentUIController;
- (void).cxx_destruct;
- (void)tokenFieldController:(id)arg1 globalOperatorDidChange:(int)arg2;
- (void)tokenFieldController:(id)arg1 filtersDidUpdate:(id)arg2;
- (void)tokenFieldController:(id)arg1 filter:(id)arg2 configureMenu:(id)arg3;
- (id)tokenFieldController:(id)arg1 menuItemsForFilter:(id)arg2;
- (id)_itemForComparisonType:(long long)arg1;
- (id)_itemForFilterType:(long long)arg1;
- (void)runNumberChanged;
@property(retain, nonatomic) PFTTraceDocument *currentDocument;
@property(readonly, nonatomic) BOOL hasFilter;
- (void)_rebuildUI;
- (id)_scopeButtonForUIStrategyController:(id)arg1;
- (void)_strategyScopeButtonClicked:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

