//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DTTimelineDecoratedPlane, DTTimelineGraph, DTTimelinePlane, NSString, PFTTraceDocument, XRAnalysisCoreConnectionIntervalDecorator, XRAnalysisCoreConnectionIntervalModel;

__attribute__((visibility("hidden")))
@interface XRStrategyUIHighlightingController : NSObject
{
    PFTTraceDocument *_traceDocument;
    long long _currentRunNumber;
    NSString *_identifier;
    unsigned long long _highlightType;
    union XRBookmark _highlightBookmark;
    unsigned int _highlightTableID;
    unsigned long long *_highlightUUIDArray;
    unsigned int _highlightUUIDArrayCount;
    DTTimelinePlane *_highlightedPlane;
    struct XRTimeRange _highlightedPlaneTimeRange;
    DTTimelineGraph *_timelineGraph;
    DTTimelineDecoratedPlane *_overlayPlane;
    XRAnalysisCoreConnectionIntervalDecorator *_connectionsDecorator;
    XRAnalysisCoreConnectionIntervalModel *_connectionsModel;
}

@property(retain, nonatomic) XRAnalysisCoreConnectionIntervalModel *connectionsModel; // @synthesize connectionsModel=_connectionsModel;
@property(retain, nonatomic) XRAnalysisCoreConnectionIntervalDecorator *connectionsDecorator; // @synthesize connectionsDecorator=_connectionsDecorator;
@property(retain, nonatomic) DTTimelineDecoratedPlane *overlayPlane; // @synthesize overlayPlane=_overlayPlane;
@property(nonatomic) __weak DTTimelineGraph *timelineGraph; // @synthesize timelineGraph=_timelineGraph;
- (void).cxx_destruct;
- (void)restoreHighlightState;
- (void)shutdown;
- (void)clearHighlightWalk;
- (void)highlightSelectedUUID:(unsigned long long)arg1 bookmark:(union XRBookmark)arg2 timeRange:(struct XRTimeRange)arg3 onPlane:(id)arg4 withRoute:(id)arg5;
- (void)highlightSelectedObjectAtTime:(unsigned long long)arg1 onPlane:(id)arg2 withRoute:(id)arg3;
- (void)_updatePlaneHighlightsForCore:(id)arg1 connectionChainTableID:(unsigned int)arg2 uuid:(unsigned long long)arg3 route:(id)arg4;
- (BOOL)_getUUID:(unsigned long long *)arg1 bookmark:(union XRBookmark *)arg2 changes:(id)arg3 forQuery:(id)arg4 tableID:(unsigned int)arg5 timeColumnID:(unsigned char)arg6 durationColumnID:(unsigned char)arg7 visualConnectionUUIDLabelColumnID:(unsigned char)arg8 core:(id)arg9 inspectTime:(unsigned long long)arg10;
- (void)_updateHighlightsForChanges:(id)arg1 afterOp:(id)arg2;
- (void)_resetAndClearHighlights;
- (void)_clearHighlightsFromPlanes;
- (id)_createColumnSelectionValueSets:(id)arg1 schema:(id)arg2 uuid:(unsigned long long)arg3 route:(id)arg4;
- (void)resolutionDidChange:(unsigned long long)arg1;
- (id)_overlayPlane;
- (BOOL)createOverlayPlaneAndDecoratorForRunNumber:(long long)arg1 resolution:(unsigned long long)arg2;
- (BOOL)updateOverlayPlaneAfterModelChangeForResolution:(unsigned long long)arg1 planes:(id)arg2;
- (void)refreshConnectionsModelForRunNumber:(long long)arg1 planes:(id)arg2;
- (void)_createConnectionIntervalModelForRunNumber:(long long)arg1;
- (BOOL)createConnectionsIntervalDecoratorForRunNumber:(long long)arg1 resolution:(unsigned long long)arg2;
- (unsigned int)_connectionChainTableIDForRunNumber:(long long)arg1;
- (unsigned int)_connectionPlaneTableIDForRunNumber:(long long)arg1;
- (id)model;
- (void)setModel:(id)arg1;
- (void)dealloc;
- (id)initWithIdentifier:(id)arg1;

@end

