//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "XRBrushProvider.h"

@class DTTimelineGroupPlane, NSArray, NSMutableArray, NSString, XRInstrument, XRStrategyUIController, XRTrack;

@interface XRStrategyUIControllerTopLevelItem : NSObject <XRBrushProvider>
{
    long long _runNumberForTrack;
    NSString *_serializationString;
    id <XRTimelineRepresentedObject> _value;
    XRInstrument *_instrument;
    int _type;
    unsigned int _instance;
    BOOL _isPinned;
    BOOL _hidden;
    BOOL _brushLocked;
    XRStrategyUIController *_uiController;
    long long _deckUnits;
    XRTrack *_track;
    NSMutableArray *_targetFilterables;
    DTTimelineGroupPlane *_groupPlane;
}

+ (BOOL)convertSerializationString:(id)arg1 toType:(int *)arg2 identifier:(id *)arg3 instance:(unsigned int *)arg4;
+ (id)serializationStringForType:(int)arg1 identifier:(id)arg2 instance:(unsigned int)arg3;
@property(retain, nonatomic) DTTimelineGroupPlane *groupPlane; // @synthesize groupPlane=_groupPlane;
@property(nonatomic) BOOL brushLocked; // @synthesize brushLocked=_brushLocked;
@property(retain, nonatomic) NSMutableArray *targetFilterables; // @synthesize targetFilterables=_targetFilterables;
@property(nonatomic) BOOL hidden; // @synthesize hidden=_hidden;
@property(retain, nonatomic) XRTrack *track; // @synthesize track=_track;
@property(nonatomic) BOOL isPinned; // @synthesize isPinned=_isPinned;
@property(nonatomic) long long deckUnits; // @synthesize deckUnits=_deckUnits;
@property(nonatomic) __weak XRStrategyUIController *uiController; // @synthesize uiController=_uiController;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *currentBrushName;
@property(readonly, nonatomic) NSArray *brushNames;
- (void)handleBrushChange;
- (id)brushElements;
- (BOOL)isLegacyOrNonPinnedInstrument;
- (id)representativePlaneForManager:(id)arg1;
- (void)createTrackWithManager:(id)arg1 trace:(id)arg2 runNumber:(long long)arg3 participatingRuns:(id)arg4 resolution:(unsigned long long)arg5 object:(id)arg6 forEmbedding:(BOOL)arg7 inToolbar:(BOOL)arg8 needsTrackDisplayGlyph:(BOOL)arg9 displayName:(id)arg10 displaySubtitle:(id)arg11 userInfo:(id)arg12 filters:(id)arg13 targetFilterables:(id)arg14 icon:(id)arg15 accessoryImage:(id)arg16 accessoryImageLabel:(id)arg17 strategyIdentifier:(id)arg18;
- (void)_setupNewGroupPlane:(id)arg1 inToolbar:(BOOL)arg2 displayName:(id)arg3 displaySubtitle:(id)arg4 userInfo:(id)arg5 icon:(id)arg6;
@property(nonatomic) int type;
@property(nonatomic) unsigned int instance;
- (id)valueAsInstrument;
- (BOOL)isInstanceOf:(id)arg1;
@property(retain, nonatomic) id <XRTimelineRepresentedObject> value;
@property(readonly, nonatomic) DTTimelineGroupPlane *currentPlane;
- (id)serializationString;
- (void)_refreshSerializationString;
- (void)invalidate;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

