//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "NSSecureCoding.h"

@class XRIntKeyedDictionary;

@interface XRStrategyUIControllerState : NSObject <NSSecureCoding, NSCopying>
{
    BOOL _revealSelection;
    XRIntKeyedDictionary *_stateByRun;
}

+ (BOOL)supportsSecureCoding;
+ (id)stateForData:(id)arg1;
+ (id)dataForState:(id)arg1;
+ (id)encodedKeyClasses;
+ (id)archivableKeys;
@property(nonatomic) BOOL revealSelection; // @synthesize revealSelection=_revealSelection;
@property(retain, nonatomic) XRIntKeyedDictionary *stateByRun; // @synthesize stateByRun=_stateByRun;
- (void).cxx_destruct;
- (id)stateForRunNumber:(long long)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (void)updateLegacyUIStateForTrace:(id)arg1 withIdentifier:(id)arg2;

@end

