//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSImage, NSOrderedSet, NSString, XRAnalysisCoreDetailViewController;

__attribute__((visibility("hidden")))
@interface XRStrategyUIControllerTypeData : NSObject
{
    BOOL _checkedForCommonDetailView;
    NSString *_currentBrushName;
    NSOrderedSet *_brushNames;
    NSImage *_defaultTrackImage;
    XRAnalysisCoreDetailViewController *_commonDetailViewController;
}

@property(retain, nonatomic) XRAnalysisCoreDetailViewController *commonDetailViewController; // @synthesize commonDetailViewController=_commonDetailViewController;
@property(nonatomic) BOOL checkedForCommonDetailView; // @synthesize checkedForCommonDetailView=_checkedForCommonDetailView;
@property(retain, nonatomic) NSImage *defaultTrackImage; // @synthesize defaultTrackImage=_defaultTrackImage;
@property(retain, nonatomic) NSOrderedSet *brushNames; // @synthesize brushNames=_brushNames;
@property(retain, nonatomic) NSString *currentBrushName; // @synthesize currentBrushName=_currentBrushName;
- (void).cxx_destruct;
- (id)init;

@end

