//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "NSSecureCoding.h"

@class NSMutableArray, NSMutableDictionary, NSString;

@interface XRStrategyUIControllerRunState : NSObject <NSSecureCoding, NSCopying>
{
    NSMutableDictionary *_legacyUserInterfacePlansByIdentifier;
    unsigned int _nextInstanceNumber;
    double _timelineGraphYOffset;
    NSString *_trackSelection;
    NSMutableDictionary *_brushNamesMap;
    NSMutableDictionary *_deckHeightsMap;
    NSMutableArray *_sortedSerializationStrings;
}

+ (BOOL)supportsSecureCoding;
+ (id)encodedKeyClasses;
+ (id)archivableKeys;
@property(nonatomic) unsigned int nextInstanceNumber; // @synthesize nextInstanceNumber=_nextInstanceNumber;
@property(retain, nonatomic) NSMutableArray *sortedSerializationStrings; // @synthesize sortedSerializationStrings=_sortedSerializationStrings;
@property(retain, nonatomic) NSMutableDictionary *deckHeightsMap; // @synthesize deckHeightsMap=_deckHeightsMap;
@property(retain, nonatomic) NSMutableDictionary *brushNamesMap; // @synthesize brushNamesMap=_brushNamesMap;
@property(retain, nonatomic) NSString *trackSelection; // @synthesize trackSelection=_trackSelection;
@property(nonatomic) double timelineGraphYOffset; // @synthesize timelineGraphYOffset=_timelineGraphYOffset;
- (void).cxx_destruct;
- (void)_addLegacyUserInterfacePlan:(id)arg1 forIdentifier:(id)arg2;
- (id)legacyFormatArchivedPlanForIdentifier:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (id)_createDeckHeightsMap;
- (id)_createBrushNamesMap;

@end

