//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "XRInspectorSource.h"
#import "XRLazyKVOResponder.h"

@class NSString, XRLazyKVOAdapter, XRStrategyInspectionNavigator, XRStrategyUIController;

@interface XRStrategyUIInspector : NSObject <XRLazyKVOResponder, XRInspectorSource>
{
    NSString *_documentUUID;
    XRLazyKVOAdapter *_kvoAdapter;
    XRStrategyUIController *_owner;
    XRStrategyInspectionNavigator *_navigator;
}

@property(retain, nonatomic) XRStrategyInspectionNavigator *navigator; // @synthesize navigator=_navigator;
@property(readonly, nonatomic) __weak XRStrategyUIController *owner; // @synthesize owner=_owner;
- (void).cxx_destruct;
- (void)_detachInspector;
- (BOOL)canMoveLeft;
- (BOOL)canMoveRight;
- (void)_displayRelatedEventDetail;
- (void)_moveToNextEvent;
- (void)_moveToPreviousEvent;
- (id)documentUUID;
- (void)inspectorDismissed:(id)arg1;
- (void)handleLazyKVOUpdate:(id)arg1;
- (id)dataElementsForInspector:(id)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithStrategyUIController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

