//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary, XRStrategyController;

__attribute__((visibility("hidden")))
@interface XRStrategyUIControllerItemManager : NSObject
{
    XRStrategyController *_strategyController;
    NSMutableDictionary *_topLevelItems;
    NSMutableArray *_sortedTopLevelItems;
}

@property(retain, nonatomic) NSMutableArray *sortedTopLevelItems; // @synthesize sortedTopLevelItems=_sortedTopLevelItems;
@property(retain, nonatomic) NSMutableDictionary *topLevelItems; // @synthesize topLevelItems=_topLevelItems;
@property(retain, nonatomic) XRStrategyController *strategyController; // @synthesize strategyController=_strategyController;
- (void).cxx_destruct;
- (void)enumerateItemsOfType:(int)arg1 block:(CDUnknownBlockType)arg2;
- (void)clearItemsOfType:(int)arg1;
- (void)clearItems;
- (void)removeItemForSerializationString:(id)arg1;
- (void)addItem:(id)arg1 forSerializationString:(id)arg2;
- (id)init;

@end

