//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsKit/XRPreferencesModule.h>

#import "NSOpenSavePanelDelegate.h"
#import "NSTableViewDataSource.h"
#import "NSTableViewDelegate.h"
#import "NSTextFieldDelegate.h"

@class DVTBorderedView, DVTFilePathField, DVTGradientImageButton, DVTScrollView, DVTTableView, NSArrayController, NSButton, NSImage, NSMutableArray, NSNumberFormatter, NSOpenPanel, NSPopUpButton, NSString, NSTableView, NSTextField, NSView;

@interface XRSymbolsPreferencesModule : XRPreferencesModule <NSOpenSavePanelDelegate, NSTableViewDelegate, NSTableViewDataSource, NSTextFieldDelegate>
{
    NSOpenPanel *_currentDSYMScriptOpenPanel;
    NSMutableArray *_advancedOptions;
    NSView *_currentDetailView;
    unsigned char _currentDetailType;
    NSImage *_statusLightGreen;
    NSImage *_statusLightRed;
    NSArrayController *_searchPathController;
    NSPopUpButton *_dsymScriptUsagePopUp;
    DVTBorderedView *_searchPathsBox;
    DVTScrollView *_searchPathsScrollView;
    DVTTableView *_searchPathsTableView;
    DVTGradientImageButton *_addSymbolPathButton;
    DVTGradientImageButton *_removeSymbolPathButton;
    DVTFilePathField *_downloadScriptTextField;
    NSButton *_advanceButton;
    NSNumberFormatter *_integerNumberFormatter;
    NSView *_advancedOptionsView;
    DVTBorderedView *_settingsBorderedView;
    DVTBorderedView *_advancedOptionsDetailView;
    NSTextField *_detailNameLabel;
    NSTextField *_detailNameTextField;
    NSTextField *_detailDescriptionTextField;
    NSTableView *_settingsTableView;
    NSView *_detailPlaceholderView;
    NSView *_boolDetailView;
    NSButton *_boolDetailButton;
    NSView *_integerDetailView;
    NSTextField *_integerTextField;
    NSView *_argumentDetailView;
    NSTextField *_argumentTextField;
}

@property __weak NSTextField *argumentTextField; // @synthesize argumentTextField=_argumentTextField;
@property(retain) NSView *argumentDetailView; // @synthesize argumentDetailView=_argumentDetailView;
@property __weak NSTextField *integerTextField; // @synthesize integerTextField=_integerTextField;
@property(retain) NSView *integerDetailView; // @synthesize integerDetailView=_integerDetailView;
@property __weak NSButton *boolDetailButton; // @synthesize boolDetailButton=_boolDetailButton;
@property(retain) NSView *boolDetailView; // @synthesize boolDetailView=_boolDetailView;
@property __weak NSView *detailPlaceholderView; // @synthesize detailPlaceholderView=_detailPlaceholderView;
@property __weak NSTableView *settingsTableView; // @synthesize settingsTableView=_settingsTableView;
@property __weak NSTextField *detailDescriptionTextField; // @synthesize detailDescriptionTextField=_detailDescriptionTextField;
@property __weak NSTextField *detailNameTextField; // @synthesize detailNameTextField=_detailNameTextField;
@property __weak NSTextField *detailNameLabel; // @synthesize detailNameLabel=_detailNameLabel;
@property __weak DVTBorderedView *advancedOptionsDetailView; // @synthesize advancedOptionsDetailView=_advancedOptionsDetailView;
@property __weak DVTBorderedView *settingsBorderedView; // @synthesize settingsBorderedView=_settingsBorderedView;
@property(retain) NSView *advancedOptionsView; // @synthesize advancedOptionsView=_advancedOptionsView;
@property(retain) NSNumberFormatter *integerNumberFormatter; // @synthesize integerNumberFormatter=_integerNumberFormatter;
@property __weak NSButton *advanceButton; // @synthesize advanceButton=_advanceButton;
@property __weak DVTFilePathField *downloadScriptTextField; // @synthesize downloadScriptTextField=_downloadScriptTextField;
@property __weak DVTGradientImageButton *removeSymbolPathButton; // @synthesize removeSymbolPathButton=_removeSymbolPathButton;
@property __weak DVTGradientImageButton *addSymbolPathButton; // @synthesize addSymbolPathButton=_addSymbolPathButton;
@property __weak DVTTableView *searchPathsTableView; // @synthesize searchPathsTableView=_searchPathsTableView;
@property __weak DVTScrollView *searchPathsScrollView; // @synthesize searchPathsScrollView=_searchPathsScrollView;
@property __weak DVTBorderedView *searchPathsBox; // @synthesize searchPathsBox=_searchPathsBox;
@property __weak NSPopUpButton *dsymScriptUsagePopUp; // @synthesize dsymScriptUsagePopUp=_dsymScriptUsagePopUp;
@property __weak NSArrayController *searchPathController; // @synthesize searchPathController=_searchPathController;
- (void).cxx_destruct;
- (void)tableViewSelectionDidChange:(id)arg1;
- (id)tableView:(id)arg1 viewForTableColumn:(id)arg2 row:(long long)arg3;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;
- (long long)numberOfRowsInTableView:(id)arg1;
- (void)controlTextDidChange:(id)arg1;
- (void)detailSupportedClicked:(id)arg1;
- (void)doneClicked:(id)arg1;
- (void)_showSymbolSheetEnded:(id)arg1 returnCode:(int)arg2 contextInfo:(void *)arg3;
- (void)advancedClicked:(id)arg1;
- (void)_populateAdvancedOptions;
- (void)saveChanges;
- (void)dsymScriptUsageChanged:(id)arg1;
- (BOOL)panel:(id)arg1 validateURL:(id)arg2 error:(id *)arg3;
- (BOOL)panel:(id)arg1 shouldEnableURL:(id)arg2;
- (void)removeSearchPath:(id)arg1;
- (void)addSearchPath:(id)arg1;
- (void)_updateDSYMScriptTextField;
- (BOOL)isResizable;
- (id)imageForPreferenceNamed:(id)arg1;
- (void)initializeFromDefaults;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

