//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSTouchBarDelegate.h"

@class NSArray, NSString, PFTWindowController, XRInstrumentListPopoverController;

@interface XRTouchBarController : NSObject <NSTouchBarDelegate>
{
    PFTWindowController *_windowController;
    XRInstrumentListPopoverController *_popoverController;
}

@property(retain, nonatomic) XRInstrumentListPopoverController *popoverController; // @synthesize popoverController=_popoverController;
@property(readonly, nonatomic) __weak PFTWindowController *windowController; // @synthesize windowController=_windowController;
- (void).cxx_destruct;
- (id)touchBar:(id)arg1 makeItemForIdentifier:(id)arg2;
@property(readonly) NSArray *touchBarIdentifiers;
- (id)initWithWindowController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

