//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "XRToolbarManager.h"

@class NSString, NSToolbarItem, NSView, XRRecordStopToolbarItem, XRToolbar;

@interface XRToolbarManager : NSObject <XRToolbarManager>
{
    XRRecordStopToolbarItem *_recordItem;
    XRToolbar *_toolbar;
    NSString *_documentIdentifer;
    NSToolbarItem *_libraryToolbarItem;
}

+ (id)toolbarManagerWithIdentifier:(id)arg1 window:(id)arg2 documentIdentifier:(id)arg3;
@property(retain, nonatomic) NSToolbarItem *libraryToolbarItem; // @synthesize libraryToolbarItem=_libraryToolbarItem;
@property(copy) NSString *documentIdentifer; // @synthesize documentIdentifer=_documentIdentifer;
@property(retain) XRToolbar *toolbar; // @synthesize toolbar=_toolbar;
- (void).cxx_destruct;
- (id)toolbarDefaultItemIdentifiers:(id)arg1;
- (id)toolbarAllowedItemIdentifiers:(id)arg1;
- (id)toolbar:(id)arg1 itemForItemIdentifier:(id)arg2 willBeInsertedIntoToolbar:(BOOL)arg3;
@property(readonly, nonatomic) XRRecordStopToolbarItem *recordItem;
@property(readonly, nonatomic) NSView *libraryButton;
- (id)initWithToolbar:(id)arg1 documentIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

