//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DTTimelinePlane;

__attribute__((visibility("hidden")))
@interface XRTrackPlaneEntry : NSObject
{
    float _order;
    DTTimelinePlane *_plane;
    unsigned long long _type;
    double _height;
}

@property(nonatomic) double height; // @synthesize height=_height;
@property(nonatomic) float order; // @synthesize order=_order;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(retain, nonatomic) DTTimelinePlane *plane; // @synthesize plane=_plane;
- (void).cxx_destruct;
- (double)heightWithResizablePlaneHeight:(double)arg1;
- (id)initWithPlane:(id)arg1 type:(unsigned long long)arg2 order:(float)arg3;

@end

