//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsKit/XRTouchBarItemViewController.h>

#import "DTTimelineGraphDelegate.h"
#import "XRLazyKVOResponder.h"

@class DTTimelineGraph, DVTBorderedView, NSImageView, NSLayoutConstraint, NSPressGestureRecognizer, NSString, XRLazyKVOAdapter;

@interface XRTrackViewItemViewController : XRTouchBarItemViewController <DTTimelineGraphDelegate, XRLazyKVOResponder>
{
    BOOL _movingLeftHandle;
    BOOL _movingRightHandle;
    BOOL _viewportHasBeenDragged;
    DTTimelineGraph *_graph;
    XRLazyKVOAdapter *_observationAdapter;
    NSImageView *_leftHandle;
    NSImageView *_rightHandle;
    NSImageView *_handleMiddle;
    DVTBorderedView *_leftOutsideViewportView;
    DVTBorderedView *_rightOutsideViewportView;
    NSLayoutConstraint *_leftHandleConstraint;
    NSLayoutConstraint *_rightHandleConstraint;
    NSPressGestureRecognizer *_pressGestureRecognizer;
    double _viewportCenterOffset;
}

@property(nonatomic) BOOL viewportHasBeenDragged; // @synthesize viewportHasBeenDragged=_viewportHasBeenDragged;
@property(nonatomic) double viewportCenterOffset; // @synthesize viewportCenterOffset=_viewportCenterOffset;
@property(nonatomic) BOOL movingRightHandle; // @synthesize movingRightHandle=_movingRightHandle;
@property(nonatomic) BOOL movingLeftHandle; // @synthesize movingLeftHandle=_movingLeftHandle;
@property(retain, nonatomic) NSPressGestureRecognizer *pressGestureRecognizer; // @synthesize pressGestureRecognizer=_pressGestureRecognizer;
@property(retain, nonatomic) NSLayoutConstraint *rightHandleConstraint; // @synthesize rightHandleConstraint=_rightHandleConstraint;
@property(retain, nonatomic) NSLayoutConstraint *leftHandleConstraint; // @synthesize leftHandleConstraint=_leftHandleConstraint;
@property(retain, nonatomic) DVTBorderedView *rightOutsideViewportView; // @synthesize rightOutsideViewportView=_rightOutsideViewportView;
@property(retain, nonatomic) DVTBorderedView *leftOutsideViewportView; // @synthesize leftOutsideViewportView=_leftOutsideViewportView;
@property(retain, nonatomic) NSImageView *handleMiddle; // @synthesize handleMiddle=_handleMiddle;
@property(retain, nonatomic) NSImageView *rightHandle; // @synthesize rightHandle=_rightHandle;
@property(retain, nonatomic) NSImageView *leftHandle; // @synthesize leftHandle=_leftHandle;
@property(retain, nonatomic) XRLazyKVOAdapter *observationAdapter; // @synthesize observationAdapter=_observationAdapter;
@property(retain, nonatomic) DTTimelineGraph *graph; // @synthesize graph=_graph;
- (void).cxx_destruct;
- (void)_rescaleGraph;
- (void)_syncTimeline;
- (void)_rebuildTimeline;
- (id)_iconForInstrument:(id)arg1;
- (void)_addHandleToContainerView:(id)arg1;
- (id)_imageViewWithImageNamed:(id)arg1 containerView:(id)arg2;
- (id)_buildView;
- (void)_centerViewportOnPoint:(struct CGPoint)arg1 offset:(double)arg2;
- (void)_matchMainGraphToHandles;
- (void)_moveLeftHandleToPoint:(struct CGPoint)arg1;
- (void)_moveRightHandleToPoint:(struct CGPoint)arg1;
- (double)_viewportCenter;
- (BOOL)_pointHitsLeftHandle:(struct CGPoint)arg1;
- (BOOL)_pointHitsRightHandle:(struct CGPoint)arg1;
- (BOOL)_pointHitsWithinViewport:(struct CGPoint)arg1;
- (void)handlePressGesture:(id)arg1;
- (void)_coreSpaceNotification:(id)arg1;
- (void)handleLazyKVOUpdate:(id)arg1;
- (void)inputHandlerForGraph:(id)arg1 requestsHeight:(double)arg2 forPlane:(id)arg3;
- (void)inputHandlerForGraph:(id)arg1 requestsCollapsingGroupPlane:(id)arg2;
- (void)inputHandlerForGraph:(id)arg1 requestsExpandingGroupPlane:(id)arg2;
- (void)inputHandlerRequestsToClearInspectionInfoForGraph:(id)arg1;
- (void)inputHandlerForGraph:(id)arg1 requestsNanosecondsPerPoint:(unsigned long long)arg2;
- (void)inputHandlerRequestsToClearCurrentInspectionTimeForGraph:(id)arg1;
- (void)inputHandlerForGraph:(id)arg1 requestsCurrentInspectionTime:(unsigned long long)arg2;
- (void)inputHandlerRequestsToClearSelectedTimeRangeForGraph:(id)arg1;
- (void)inputHandlerDidFinishSelectionForGraph:(id)arg1;
- (void)inputHandlerForGraph:(id)arg1 requestsSelectedTimeRange:(struct XRTimeRange)arg2;
- (void)inputHandlerForGraph:(id)arg1 requestYOffset:(double)arg2;
- (void)inputHandlerForGraph:(id)arg1 requestsNanosecondOffset:(long long)arg2;
- (void)viewDidDisappear;
- (void)viewDidAppear;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

