//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, XRDevice;

@protocol XRTraceDelegate <NSObject>
- (void)restoreWithTemplateData:(NSDictionary *)arg1;

@optional
- (void)setTargetsDevice:(XRDevice *)arg1;
- (NSDictionary *)templateData;
@end

