//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "XRTimelineRepresentedObject.h"

@class NSString;

@interface XRUIStrategyProxyObject : NSObject <XRTimelineRepresentedObject>
{
    unsigned int _instance;
    id <XRTimelineRepresentedObject> _realObject;
}

@property(nonatomic) unsigned int instance; // @synthesize instance=_instance;
@property(retain, nonatomic) id <XRTimelineRepresentedObject> realObject; // @synthesize realObject=_realObject;
- (void).cxx_destruct;
- (id)_filterablesForRunListData:(id)arg1 runNumber:(long long)arg2;
- (BOOL)_planeShouldBeResizableForUIStrategy;
- (void)_createTrackForTopLevelItem:(id)arg1 uiStrategyController:(id)arg2 graph:(id)arg3 multipleBrushes:(BOOL)arg4 forEmbedding:(BOOL)arg5 inToolbar:(BOOL)arg6;
- (id)_topLevelItemForUIStrategy:(id)arg1 forEmbedding:(BOOL)arg2;
- (id)_topLevelItemForUIStrategy:(id)arg1 forEmbedding:(BOOL)arg2 instance:(unsigned int)arg3;
- (id)_keyForUIStrategy;
- (id)_UISerializationString;
- (int)_strategyUIType;
- (id)initWithObject:(id)arg1 instance:(unsigned int)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

