//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <InstrumentsKit/XREngineeringTypeFormatter.h>

@class XRAnalysisCoreValue;

@interface XRWeightFormatter : XREngineeringTypeFormatter
{
    long long _weightIdx;
    unsigned short _impliedType;
    XRAnalysisCoreValue *_resuableVal;
    BOOL _includePercentageOfTotal;
    BOOL _useSelfColumn;
}

@property(nonatomic) BOOL useSelfColumn; // @synthesize useSelfColumn=_useSelfColumn;
@property(nonatomic) BOOL includePercentageOfTotal; // @synthesize includePercentageOfTotal=_includePercentageOfTotal;
- (void).cxx_destruct;
- (id)stringForObjectValue:(id)arg1;
- (id)initWithTrace:(id)arg1 runNumber:(long long)arg2;
- (id)initWithTrace:(id)arg1 runNumber:(long long)arg2 impliedEngineeringTypeID:(unsigned short)arg3 weightIdx:(long long)arg4;

@end

